### ISSUE TITLE
Explore visual directions for the guide website

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#1]
Let's do some discovery on the overall feel, brand,  styling and other aspects of what we want the guide to look like in the end.

Pedro has started a [mood board on Figma](https://www.figma.com/file/0NbGBf0oEayCnKRGk8klj9/Bitcoin-Design-Guide-Webite-Planning?node-id=0%3A1) with references to comparable sites that we can discuss.

**Comment by BitcoinErrorLog** [comment]
Way too many options to review, maybe the designer can narrow down further. Otherwise I'd opt for the classic B&W style already in use at top right of Figma file.

**Comment by GBKS** [comment]
Closing this issue. The design direction convo is continued in #11 .
