### ISSUE TITLE
Refresh the projects page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#1010]
Our [projects page](https://bitcoin.design/projects/) on the website could use a refresher. Before opening a PR, I'd like to gather changes to make. Here's a starting point.

**Add projects**
- Bitcoin research kit
- [When Taproot](http://whentaproot.org)
- Wallet Scrutiny: we've collaborated on web design for 6 months now
- Saving Satoshi
- Summer of Bitcoin

**Update projects**
- JoinMarket: now called Jam, has a new website
- Bitcoin Core App: change link to bitcoincore.app

**Remove projects**
Let's discuss whether we actually remove projects or create an "archived" list.
- Bitcoin Design Sprints: we stopped after the first one
- Hello Bitcoin: I think this has came to a halt

**Questions**
- Add the Bolt12 & async payments project?
- Add [BDG Wallet](https://github.com/bdgwallet)? A question for Daniel
- Fedimint just started design calls. Add, or wait until clear momentum is there?

I'm sure I missed things... reply in the comments with your thoughts.

As we've discussed before, this is not a super precise list as open-source collaboration can be really fluent and sometimes has waves of momentum. So I wouldn't think too strictly about the categorizations. Goal is to have an easy way for readers to find and connect with projects that have some type of connection with the community.

**Comment by danielnordh** [comment]
Good initiative.

Maybe we keep old projects under a 'Previous projects' header instead of removing them.

I'd wait a bit to add BDG Wallet, not really forkable yet but hope lightning to be added in the coming month so should reconsider then. OR if work in progress is OK it could be included as:
"An open-source bitcoin wallet template for iOS. Work In Progress." or similar.

**Comment by GBKS** [comment]
Alright, I set up a PR for it with various changes. Please take a look.
