### ISSUE TITLE
Wallet Scrutiny case study

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Guide#1028]
**Add a case study about the Wallet Scrutiny redesign process**

If the community would like then we could add a case study about the re-design process of the Wallet Scrutiny website to the case study [section](https://bitcoin.design/guide/case-studies/) in the guide.

**Link to the page**
Link to [live](https://walletscrutiny.com/) redesigned website. 

**Why would you like to change the content?**
Adding in the collaboration to the guide would showcase the redesign process of this website from beginning to end and could provide other open source projects an idea of the steps that we as a community did during the redesign process.

**Suggestions**
The collaboration has been documented [here](https://github.com/BitcoinDesign/Meta/issues/415) and so we could use all of the notes to recall the steps that were done and so forth. 

**Additional context**
Redesign images before and after.
![image (15)](https://github.com/BitcoinDesign/Guide/assets/90313394/577c3014-290a-4f95-8ba4-846a4426e3ed)

**Comment by ShalomOhuegbe** [comment]
Hi Mo, I would like to take this up and collaborate with you and anyone else who's interested in documenting the case study. Thanks

**Comment by MrAjulo** [comment]
I'd also like to collaborate on this.

**Comment by ShalomOhuegbe** [comment]
Hi @mouxdesign I just sent you a DM, please check. Thank you

**Comment by GBKS** [comment]
@ShalomOhuegbe please don't send people reminders that you DM'd them. They will get around to your messages, no worries. Mo is just traveling back from vacation right now.

**Comment by ShalomOhuegbe** [comment]
@GBKS Oh I apologize, i didn't know that

**Comment by mouxdesign** [comment]
@ShalomOhuegbe @MrAjulo I've connected with you both on Twitter. Lets continue the convo there. Looking forward to collaborating with you both on this.

**Comment by mouxdesign** [comment]
Shalom and Dani and myself met this jumped on a quick call today to so that they could ask any questions and plan how they will work on creating the case study together.

Created a [Google doc](https://docs.google.com/document/d/1claIH7rWivj-jjIjhFtFAKEAYxsgC1D0XowfDcy8-l0/edit) where they can jam in together and with links to all the project resources. Looking forward to seeing what they put together.

**Comment by mouxdesign** [comment]
Spent some time today fleshing out the case study and adding links. The first [draft ](https://docs.google.com/document/d/1claIH7rWivj-jjIjhFtFAKEAYxsgC1D0XowfDcy8-l0/edit?usp=sharing)is ready for a review.

Essentially looking for a review in the following areas:
- Does the case study tell a story?
- Are there any areas that have been missed? Are there any areas that can be excluded?
- Readability suggestions: Suggestions on the copy itself

Visuals will then be created after there is more consensus of the current draft.
@ShalomOhuegbe @MrAjulo

**Comment by GBKS** [comment]
Great progress. I read through and left a few comments. Overall, I think we can be a bit more specific with some of the challenges, discussions, and solutions.

The product page, for example, took a really long time because the information is so complex and we had to understand it all first. Expert opinions, and how to balance the credibility of the security researchers with public opinion and external reviewers was also a big topic (and something that is not done yet).

There could also be a follow-up with that is happening now. Like improving onboarding, the Twitter Spaces, and iterating on feedback. It could end with a call for contributors.

**Comment by rabbitholiness** [comment]
I read through yesterday and really like it so far. Also left a few comments.

The only thing was that I got kind of lost in the different sections. I wouldn't change the content, but maybe give it a bit more structure to help with orientation. The suggestion below doesn't mean that numbers need to be used. I just wanted to illustrate the hierarchy. 

1. Intro  => 1.1 How it started; 1.2 About Wallet Scrutiny
2. Approach  => 2.1 Identify user groups 2.2 Project plan
3. Baseline testing
4. Design => 4.1 Branding; 4.2 Homepage; 4.3 Methodology page; 4.4 About page
5. Evaluation
6. Insights
7. Conclusion
8. Acknowledgements
9. Resources

**Comment by mouxdesign** [comment]
Continued to work today on the images for the case study. Dropping in some images which have now been added to the google doc.

Link to [Figma](https://www.figma.com/file/pU908ry0Q5tel5mvltRT9U/Wallet-Scrutiny-case-study-images?type=design&node-id=7%3A3155&mode=design&t=1NQFki8lXs5Iajqj-1) with the images.



![Image](https://github.com/BitcoinDesign/Guide/assets/90313394/6f7abb81-8ad3-428c-9719-5420213ec0df)



![Image](https://github.com/BitcoinDesign/Guide/assets/90313394/74e726be-0952-43d5-bc87-0673ee79a873)



![Image](https://github.com/BitcoinDesign/Guide/assets/90313394/aa7ba74b-a9dd-4c71-9abe-87b31ea2c197)



![Image](https://github.com/BitcoinDesign/Guide/assets/90313394/1d185e27-7abc-420b-b089-17e10c0d799d)

Next steps: Would really appreciate some thoughts on the images themselves. Will make more iterations to the images and create them in the mobile/desktop sizes.

**Comment by GBKS** [comment]
The images look good. Is the first one for the header? If so, a little wider might be helpful so it doesn't take up so much vertical space on desktop.

Do those circles represent the whole process? If, we could add initial discovery where we learned about the project, explored some directions, etc.

**Comment by mouxdesign** [comment]
Thank you for taking a look at the images Christoph. Continued to work on them today based on your comments and created a section in the Figma called export. 
Current sizes of the 4 images:

1. Header banner 1600 w X 600 h


![Image](https://github.com/BitcoinDesign/Guide/assets/90313394/0f546496-1c93-49b8-93c0-10bcbf7ee0ba)

2. Regular 800 w x 225 h


![Image](https://github.com/BitcoinDesign/Guide/assets/90313394/f00d4978-bbcf-4e75-93e9-322d1df8d0c2)

3. Regular 800 w X 220 h 



![Image](https://github.com/BitcoinDesign/Guide/assets/90313394/114be521-3806-465d-bd71-b38008ada851)

4.  Desktop inline 400w X 89 h (not too sure about this one and so opted for the inline version.) The regular version of this one would be pretty long. 


![Image](https://github.com/BitcoinDesign/Guide/assets/90313394/64c163a7-4fb4-49c9-a554-f534d568086a)
[
Figma](url)

**Comment by GBKS** [comment]
Just re-read the copy doc and left a few comments. I think it all looks good now and is ready to be moved to a PR.

**Comment by mouxdesign** [comment]
Thank you for the review. A PR has been opened #1045

**Comment by mouxdesign** [comment]
Closed the old PR and opened a new one #1048
