### ISSUE TITLE
Create page for Transaction History

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Guide#104]
```meta
parent: Managing Funds
permalink: /guide/managing-funds/transaction-history
```

A transaction history is usually displayed as a table or a list with items in chronological order.

- [ ] What is special about the bitcoin transaction history?
- [ ] State the primary attributes that need to be shown
- [ ] Saving meta data
- [ ] Define the available actions that are possible taking into consideration the different transaction states

#### Related
- Hide Amounts / Privacy Mode
- Amount Scanning / Gap Limit (troubleshooting)
- Labels

**Comment by pavlenex** [comment]
@johnsBeharry Is this issue still relevant to the payment section?

**Comment by johnsBeharry** [comment]
it is relevant to the managing funds page, but instead of being a subpage as described in this PR it would be a section on that page. ill open up an issue.
