### ISSUE TITLE
Add Start9 to the node page (Hardware section)

### ISSUE THREAD

**Issue by JesseMarkowitz** [BitcoinDesign/Guide#1054]
Please add Start9 to the node page (https://github.com/BitcoinDesign/Guide/blob/master/guide/how-it-works/node.md) in the Hardware section

The line that says:

Several plug-and-play hardware node options exist such as [Umbrel](https://getumbrel.com/), [MyNode](https://mynodebtc.com/), [RoninDojo](https://ronindojo.io/), and [Raspiblitz](https://raspiblitz.org/).

could be changed to:

Several plug-and-play hardware node options exist such as [Umbrel](https://getumbrel.com/), [MyNode](https://mynodebtc.com/), [RoninDojo](https://ronindojo.io/), [Start9](https://start9.com/), and [Raspiblitz](https://raspiblitz.org/).

**Comment by GBKS** [comment]
This was completed via #1055.
