### ISSUE TITLE
Integrate the Coinbits personas

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#1094]
Dave from Coinbits [shared 4 personas](https://coinbits.notion.site/Bitcoin-Personas-by-Coinbits-a66ba94de62d421795d36db66201e8c0) they developed in-house to guide their design process. Those could be a nice addition to the [user personas page](https://bitcoin.design/guide/designing-products/user-personas/), and probably also a good reference for the [Bitcoin UX Research Kit](https://bitcoinresearch.xyz/).

**Comment by mouxdesign** [comment]
Very good ideas to add these to both the Design Guide as well as the UX research toolkit.

Adding in the link here to the text version of the 4 personas. 

[Figma](https://www.figma.com/design/fnhmwGy3fR23wcVSOuTKNt/Personas-(External-Share)?node-id=623-137&t=BfxWmTvsyvVhWIIY-0)

**Comment by GBKS** [comment]
I can't open the Figma link. It was probably just shared with your personal account. I also don't think we necessarily need to copy much content into the guide. We can just reference the personas as an external resource.

**Comment by GBKS** [comment]
This was completed via #1095. [Check it out live](https://bitcoin.design/guide/designing-products/user-personas/#coinbits-personas).
