### ISSUE TITLE
Design V2 of the website

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#11]
V1, which is a placeholder site, is being discussed [here](https://github.com/BitcoinDesign/Guide/issues/10). For V2, @AlexaAker has kicked us off with some good design concepts and explorations, so I thought I'd create a dedicated issue for V2 to gather and continue this work.

- [Alexa's concepts](https://github.com/BitcoinDesign/Guide/issues/10#issuecomment-667183841)
- [Relevant Slack thread](https://bitcoindesign.slack.com/archives/C015856BDME/p1595842837251500)
- [Pedro's general mood board for the guide](https://www.figma.com/file/0NbGBf0oEayCnKRGk8klj9/Bitcoin-Design-Guide-Webite-Planning?node-id=0%3A1)

Since we are still figuring out both content and visual design for the site, I assume we'll go back and forth on a few different ideas and explorations. This should be a fun process. Please add any relevant links I missed.

**Comment by pedromvpg** [comment]
I've started working on some more mockup content for a "Output selection" page on the guide.

Using it to test the process of editing content in the jekyll, github, and figma flow.

Hoping this can be the starting point for discussion of how we're collaborating on content and what the design of the guide needs to accommodate. 

Working page here:
https://pedromvpg.github.io/bitcoin-design-guide/guide/wallet-components/output-selection

Some questions:
- does this process make it easy for designers and writers to edit and contribute, like a wiki?
- does figma offer an easy way to fork, duplicate, and version control projects?
- what other functionality needs to be tested? Zoom in on images, video, etc...

Any feedback greatly appreciated.

**Comment by mrsellars** [comment]
> Some questions:
> 
>     * does this process make it easy for designers and writers to edit and contribute, like a wiki?
> 

I like the approach with the forking for the article editing. It provides a nice history. I'm not sure how the process feels like for people without any git knowledge. Would be interesting if it's too difficult or not. But I think for a first start it's nice. Later on, we could evaluate things like https://www.netlifycms.org/ which has some nice workflows for static content.

**Comment by GBKS** [comment]
Can you explain a bit more what you are suggesting in terms of process and collaborating on content?

A few thoughts:

- I think a lot of first drafts will be written in Google Docs or elsewhere before they go into the repo. Much easier to collaborate that way. I can also imagine us directly help people who are not comfortable with Github do this import
- I would not expect any non-developers to use command-line git. For small changes, github.com direct editing works. Otherwise, the Github desktop app is pretty straightforward to use. Either way, we need to create good tutorials (or find tutorials elsewhere we can recommend, like the video [here](https://docs.btcpayserver.org))
- Figma has public community files that can be remixed (forked). There's no system for merging forked content back in though, so either we replace the Figma link in Jekyll to the new file, or update the original file manually
- I'd like to see some options around theming whole pages or parts of pages like in the image below. For pages maybe just black and white, and for sections maybe either a color, image, pattern or gradient (would have to be careful here not to go overboard)
- I'd also like to have to option of providing a large header image above the title
- What does "{: .no_toc }" do in your markdown file?

![Bitcoin guide site 200801](https://user-images.githubusercontent.com/695901/89383361-9fd72080-d6fc-11ea-993e-1f3bca0df1fb.png)

Thank you so much for tackling this.

**Comment by Bosch-0** [comment]
> Figma has public community files that can be remixed (forked). There's no system for merging forked content back in though, so either we replace the Figma link in Jekyll to the new file, or update the original file manually

Could we not just have a 'main' page in the figma file that is the designs that will be showcased then create seperate pages in figma for changes to the design which we can agree on as a community to 'merge' into the main page. 

Something like below:
![image](https://user-images.githubusercontent.com/55287964/89419149-98972d80-d763-11ea-9a5c-823ec6143680.png)

**Comment by GBKS** [comment]
@Bosch-0 beyond 3 editors per file, you need to upgrade to a paid plan.

**Comment by GBKS** [comment]
Just a bit of exploration on a possible V2. It's super rough. I tried to wrap my head around what content sections we might want to what could go in there, and tested out a few more illustrations (found on Behance) for the header to drive home the main tagline. Not married to anything here, but I thought I'd share. It's in the same Figma file as always ([main file](https://www.figma.com/file/K5ahSqVzoMVBuhT5hAVRJr/Bitcoin-Designers-Website?node-id=63%3A399) and [community file](https://www.figma.com/community/file/862622015964353400/Bitcoin-Designers-site)).

<img width="3180" alt="Home page V2 200811" src="https://user-images.githubusercontent.com/695901/89913702-5141ee80-dbf4-11ea-92a4-f320b53bff4a.png">

**Comment by GBKS** [comment]
![White canvas style 200828](https://user-images.githubusercontent.com/695901/91824397-fc195b80-ec3a-11ea-8232-bddd60f93217.png)

Reposting from Slack. This visual concept expands the idea of bitcoin as a blank canvas. Page content is super minimal, almost like a coloring book, and various different visual styles can be applied. This is super flexible and would allow for many different expressions, from corporate polished to artsy to cypherpunkish etc. This approach would be a way for different community members to put their own spin on things without feeling overly restricted.

**Comment by danielnordh** [comment]
Suggest closing this issue

**Comment by GBKS** [comment]
We're now on V3 of the website. V1 was a basic placeholder, V2 was a proper self-contained homepage and V3 added sub-pages and the guide to that. There is still some refinements needed on V3, which we can handle in separate issues. Whether we need a V4 or what that would include is up for discussion. The Figma file for the site is [here](https://www.figma.com/community/file/862622015964353400/Bitcoin-Designers-site).
