### ISSUE TITLE
Gather existing user research references

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#111]
This could be a good starting point for a page for user research resources and integrating findings into the guide. Please add any links you know to this [Google Doc](https://docs.google.com/document/d/1B3y0EnA7oaG9R_wrbddAOCJg7-PRMuyn41w1IVfnfBE/edit?usp=sharing), or in a comment.

**Comment by ConorOkus** [comment]
https://voskart.de/pdf/bits_under_mattress.pdf
