### ISSUE TITLE
Create a "Principles" page in "Foundations"

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#116]
Several sections outline principles, with some overlap already visible. Let's extract those and move them to a dedicated page. This will allow us to have a common basic understanding of those ideas. Each page then can focus on explaining how the relevant principles apply to that particular content.

Some principles I've seen described (there's probably a lot more, I just picked out ones I could quickly find):

- Permissionlessness
- Trust
- Privacy (onboarding, private key management, privacy)
- Security
- No loss of funds (private key management)
- Interoperability (private key management)
- Progressive security (private key management)

Links:

- [Private key management -> Principles](https://deploy-preview-90--sad-borg-390916.netlify.app/guide/private-key-management/principles/)
- [Onboarding draft doc](https://docs.google.com/document/d/1wK69vADJQVe2Aoh_b66LD4vclwVXIsJejplYNUhEJtY/edit?usp=sharing)
- [Payments PR preview](https://deploy-preview-62--sad-borg-390916.netlify.app/guide/payments/introduction/)

**Comment by pavlenex** [comment]
Related to this we may want to alter the description of newly-created [Foundations page](https://bitcoin.design/guide/foundations/) to avoid confusion.

> Learn about some of the basic principles to keep in mind when designing Bitcoin applications.

**Comment by danielnordh** [comment]
OK, until the content is close to ready I'm working on consolidating in [this doc](https://docs.google.com/document/d/14sGsOqEjEoMLMD1E4F_Khq6Lc5tErnb-VjDQzp97mPQ/edit?usp=sharing).
It's currently WIP and not ready for full feedback but sharing for transparency.

My starting point for the principles at the moment:

- Decentralization
- Accessibility
- Transparency
- Self-custody
- Security
- Privacy
- Interoperability

**Comment by danielnordh** [comment]
The doc is now ready for comments: 
https://docs.google.com/document/d/14sGsOqEjEoMLMD1E4F_Khq6Lc5tErnb-VjDQzp97mPQ/edit?usp=sharing

Won't create a PR until a first round of reviews have come back.

**Comment by danielnordh** [comment]
PR now here: https://github.com/BitcoinDesign/Guide/pull/144

**Comment by GBKS** [comment]
Moved to next sprint to get more feedback and iterate further.
