### ISSUE TITLE
Adding a javascript framework to help with interaction

### ISSUE THREAD

**Issue by pedromvpg** [BitcoinDesign/Guide#12]
Does any one have a preference over a javascript framework to be added to the website at its current state to help with interactions?

jquery
umbrella
cash

Should we just keep using vanilla js?

**Comment by GBKS** [comment]
I have no particular preference for the first version of the site. I'm also not 100% up-to-date on what JS fallbacks are still needed for older browsers. If it takes a ton of time to test and implement fallbacks, then maybe we should add jQuery or one of its relatives.

**Comment by ConorOkus** [comment]
I would start with vanilla for now or even CSS animations.

Here are some modern JS animation libraries - https://blog.bitsrc.io/11-javascript-animation-libraries-for-2018-9d7ac93a2c59

**Comment by GBKS** [comment]
5 months without comments, I assume we can close this one and open up a new issue if the need arises. RIP issue 12, it's been swell.
