### ISSUE TITLE
Create Payments section landing page

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Guide#131]
This issue creates the introductory page for the payments section and outlines the upcoming content that will be part of this section.

You can read the proposed section [here](https://hackmd.io/@BitcoinDesign/Sy5tozdy_/edit)

**Comment by danielnordh** [comment]
Sounds good. I think you should go ahead and create a PR for the first holding page, in the right place in the nav.
Here's an example of the holding page PR for the Private Key chapter, super simple:
https://github.com/BitcoinDesign/Guide/pull/49
