### ISSUE TITLE
Create page - Recovery backup storage 101 

### ISSUE THREAD

**Issue by danielnordh** [BitcoinDesign/Guide#139]
Create a simple best practice / backup storage options page for reference.
Somewhere we can point people to when creating new keys with a recovery phrase that needs to be backed up.

Consider:
- Redundancy (if, when and how to create several backups)
- Physical resistance (grades of resistance from paper --> metal)
- Resistance to usage on discovery (whoever finds the full recovery phrase can access funds)

Should cover:
- Basic paper backup
- Metal and other alternative materials
- Where to store
- Inheritance planning

Could also mention:
- Multiple hardware keys to the same wallet instead of backups
- An extra (13th or 25th) word that is memorized instead of written down 
- Splitting the recovery phrase to store in different locations

**Comment by danielnordh** [comment]
Here's a [draft doc](https://docs.google.com/document/d/1iZHxPcxXRfdRn9vRJDVnIkJBPP9kKnXWU7fY1p_bP94/edit?usp=sharing) of what this page could contain.
If people agree it's useful we can start working on the actual markdown page.

I'd suggest it goes in Foundations for now.

**Comment by GBKS** [comment]
This is complete with the merge of #305.
