### ISSUE TITLE
Header Theme Proposal | 3D abstract Bitcoin Design

### ISSUE THREAD

**Issue by mgaborr** [BitcoinDesign/Guide#143]
Hi all,
I'd like to contribute this header design for the [Bitcoin Design](https://bitcoin.design/) website.
thanks a lot!

<img width="1147" alt="Screen Shot 2021-02-12 at 14 32 28" src="https://user-images.githubusercontent.com/77788329/107741294-76e4b780-6d3f-11eb-9b00-ca369cf2a415.png">

# file on figma: 
[3D Abstract | Bitcoin Design Community Website Banner](https://www.figma.com/file/wxmAwmTFPe6dIt19lU4sf5/3D-Abstract-Bitcoin-Design-Community-Website-Banner?node-id=1%3A129)

 # full-res png image:
![bitcoin render](https://user-images.githubusercontent.com/77788329/107741909-a8aa4e00-6d40-11eb-923b-20edc3d100fe.png)

 # Contribute Your Own:
[How to Guide](https://bitcoin.design/submit-header-design)

[Template](https://www.figma.com/community/file/891254324897262700)

**Comment by ConorOkus** [comment]
LGTM, nice job. Reach out if you want help implementing it into the site 👍

**Comment by mgaborr** [comment]
I have no experience yet, but would love to watch and learn the process if possible:)

**Comment by ConorOkus** [comment]
Sure I can help out next week 👍

**Comment by sbddesign** [comment]
It's a very nice looking header!

I would suggest experimenting with alternate colors for the "Design Bitcoin for Everyone" header. It has very low contrast against the blue background. See it when converted to grayscale:

![bitcoin-design-guide_grayscale](https://user-images.githubusercontent.com/2414177/108213380-f63a0880-70fc-11eb-8fcc-aa98589df379.png)

And those two hex codes [fail a web accessibility test.](https://webaim.org/resources/contrastchecker/?fcolor=EA973D&bcolor=88E8F9)

**Comment by mgaborr** [comment]
Hi @sbddesign, 
Thx for your comment, 
Already had the same discussion abt colors with @GBKS
I like them as it is now, but if you wanna change it go ahead, I don't mind that ✌️
