### ISSUE TITLE
[Image] Better contrast for introduction.svg in the payments section

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#146]
World map in the background https://bitcoin.design/guide/payments/ should have better contrast.
This is good first issue for anyone interested in helping out.
![image](https://user-images.githubusercontent.com/36959754/107964035-2ec8cd80-6fa9-11eb-9a28-9b23a784710d.png)

Any takers?

**Comment by GBKS** [comment]
Whoever picks this up, make sure to ask @johnsBeharry for the source files.

**Comment by sbddesign** [comment]
I can take this one.

**Comment by pavlenex** [comment]
Awesome @sbddesign, feel free to ping @johnsBeharry on Slack in case you need source files.

**Comment by sbddesign** [comment]
![Screen Shot 2021-02-22 at 3 08 21 PM](https://user-images.githubusercontent.com/2414177/108763926-f2085380-751f-11eb-82bf-a092f73163a6.png)

![Screen Shot 2021-02-22 at 3 08 33 PM](https://user-images.githubusercontent.com/2414177/108763927-f2a0ea00-751f-11eb-8aa7-eb6dd0f01569.png)

I directly modified the SVG file in the master branch. Any preferences on color palette?

**Comment by pavlenex** [comment]
Looks good to me, but I'll let @GBKS be the judge on visuals 😄

**Comment by GBKS** [comment]
@sbddesign thanks for taking this one on. I prefer the top one. Bits of orange on black always look a bit gloomy to me.

**Comment by GBKS** [comment]
Closing this issue as it has been addressed and merged in the PR #158.
