### ISSUE TITLE
Create page for Sending bitcoin

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Guide#151]
Describe the operations involved in sending bitcoin.

> Bitcoin wallets don't have a balance in the conventional sense. Instead it keeps track of all the previously received [UTXOs](https://bitcoin.design/guide/glossary/#unspent-transaction-output-utxo). The balance applications usually show is actually a total of those UTXOs controlled by the private key to spend.
> 
> Because of this structure, choosing to optimise for privacy, lower transaction fees, or speed are things you need to consider when designing a payment experience. Your choice will directly impact the amount of steps the user needs to make.
> 
> You will also need to consider what environment the application will be used in. If you are paying a vendor at your local market you probably won't have their contact details to exchange a payment request via chat. Scanning a QR Code to get an address would likely make more sense in this situation also than manually typing it.

#### Operations

- Receiving a payment request
- Inputing the address
- Inputting the amount to send
- Adjusting the fee
- Reviewing the payment and approval
- Processing
- Confirmation

**Comment by johnsBeharry** [comment]
#### Update
- Missing sections of the page
 - Reviewing payment and confirmation
 - Processing
 - Confirmation

**Comment by pavlenex** [comment]
Done in #181
