### ISSUE TITLE
Add header images to contribute section

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#152]
There are quite a few pages in the contribute section that need some design love.

https://bitcoin.design/guide/contribute/
https://bitcoin.design/guide/contribute/propose-a-change/
https://bitcoin.design/guide/contribute/review/
https://bitcoin.design/guide/contribute/content-guidelines/
https://bitcoin.design/guide/contribute/formatting/

Here's an example of a [header image](https://bitcoin.design/assets/images/guide/private-key-management/private-key-management.jpg)

Jose Barrera (On Slack) is working on this issue.

**Comment by GBKS** [comment]
Maybe it's helpful, here's the Figma file with all the page headers I've created. [Check it](https://www.figma.com/file/qzvCvqhSRx3Jq8aywaSjlr/Bitcoin-Design-Guide-Illustrations-CO?node-id=236%3A454). Totally up to the designer what they want to do with the visual, but my approach has been to create something that expresses and complements the core idea of the page content (ideally you really understand what the page is about just from seeing the image (which your eye does first when you arrive one the page) and reading the page title). I've also tried to use this opportunity to experiment with different styles (it's a creative community after all).

**Comment by joseabarreram** [comment]
I´ve prepared this one in [Figma](https://www.figma.com/file/tq2R1zm2K866uCjCxdjkaD/design-system-course-btcpay?node-id=144%3A0) for content guidelines page. Not sure at 100% if I miss any size of them tho :/

**Comment by joseabarreram** [comment]
Updated with suggestions from @GBKS  ;)

![content-guidelines](https://user-images.githubusercontent.com/35522881/109048101-f7f46500-76d6-11eb-9909-f5ef7d818a21.png)

**Comment by GBKS** [comment]
Awesome. I usually post my header banners in the #art channel to get some feedback (and because I also want to encourage others sharing things they work on as I genuinely like to see what everyone is doing). Up to you if you want to do that.

**Comment by GBKS** [comment]
Feel free to go ahead and create a PR to add this image (let me know if you'd like some tips on doing that).

**Comment by GBKS** [comment]
Added images for the remaining pages in PR #196. The images aren't super awesome, but this will give us a starting point.
