### ISSUE TITLE
Add backwards compatibility and native application to foundations section

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#157]
Not sure if these two foundations, or what the foundations section should entail, fit here as they may be more of the developers role though they undoubtedly play a role in UX. 

Moved from [PR](https://github.com/BitcoinDesign/Guide/pull/142) to here. 

These are two foundations that all bitcoin focused applications MUST have before even considering any other kind of UX.

Imagine not touching your bitcoin stored in a wallet for several years (likely to be a common occurrence as people begin to store value in bitcoin) and you go to access your bitcoin only to find your outdated wallet is no longer compatible with the network - major UX issue that would result in someone losing all their funds. Bitcoin Core does a great job of this already for those wanting to view this in practice.

Native applications refers to having applications built from the ground up rather than having lots of dependencies to make it work. Security critical applications like bitcoin wallets really should all be native. This should be a standard we as designers push onto any bitcoin focused applications for optimal UX. Bitcoin Core, Nunchuk and Muun do a great job with regards to this.

**Comment by GBKS** [comment]
We discussed this briefly in the community call yesterday. Correct me if I'm wrong, but I think the result was that backwards compatibility is part of interoperability, which is one paragraph in the proposed principles page ([preview](https://deploy-preview-144--sad-borg-390916.netlify.app/guide/principles/principles/#interoperability)). Do you want to review that one and ensure it covers your points?

We also talked about your point about native applications, but I don't remember if there was some agreement. To me, it seems like a subset of security - reducing potential attack vectors. There is a "Do" that reads "Build with bad actors in mind", maybe we can expand on that a bit more. By itself, "Build with bad actors in mind" is not super clear and that extra context could help.

Let me know your thoughts.

**Comment by danielnordh** [comment]
Beefed up mentions of backwards compatibility (df4d515) and minimizing code dependency (8195bd2) in Principles.

**Comment by danielnordh** [comment]
Let me know if you think the above changes are sufficient @Bosch-0 or if you think something else is in order.

**Comment by danielnordh** [comment]
Unless there are further comments we can probably close this issue now that the Principles page has been merged.
#144
