### ISSUE TITLE
Header Theme Order Proposal | Latest Designs First

### ISSUE THREAD

**Issue by AlexaAker** [BitcoinDesign/Guide#160]
Hello everyone,

How would you feel about having new header designs display first? I just noticed @mgaborr 's Header Theme is live on the website. It looks great, but it is behind mine and mine has been there for a while. All designs should have the chance to be displayed when the website opens. It would help refresh the look of the site more often, and it may encourage more community participation too. I would love to see the header designs grow and change over time to reflect the diversity and creativity of the community.

**Comment by GBKS** [comment]
Currently the list of themes is randomized when the page loads, it shows the first one in the list right away, and clicking "Next" goes steps through the random order. If you always see yours first, then maybe there's a bug in the code. Could you maybe test by refreshing 10 times and seeing if you always see your design first?

**Comment by pavlenex** [comment]
For me it's randomized, so I cannot replicate the behavior. Ubuntu 20.04/Firefox.

**Comment by GBKS** [comment]
Closing this one, as I believe the banner works as @AlexaAker suggested.

We definitely need more banner contributions...
