### ISSUE TITLE
Create Onboarding Wallet Experience Pages 

### ISSUE THREAD

**Issue by ConorOkus** [BitcoinDesign/Guide#176]
This section will provide information on how to create an onboarding experience for a wallet primarily aimed at first time users. The content for this section can be found [here](https://docs.google.com/document/d/1wK69vADJQVe2Aoh_b66LD4vclwVXIsJejplYNUhEJtY/edit#heading=h.p0s44o7mnuf).

 - What a bitcoin wallet is
 - Creating a new wallet
 - Backing up a recovery phrase 
 - Protecting a wallet 
 - Restoring a wallet from a backup
 - Funding a wallet

**Comment by ConorOkus** [comment]
You can check out the work being done for the designs of these pages [here](https://www.figma.com/file/pI4W8hc1TpYC9kAbkyOwEw/Backing-up-a-Recovery-Phrase?node-id=0%3A1)

**Comment by Bosch-0** [comment]
Added a bunch of comments - looking great Conor!

**Comment by ConorOkus** [comment]
Updated navigation structure:

 - Getting to know your users
 - Creating a new wallet
 - Backing up a recovery phrase
 - Seedless backup
 - Manual backup
 - Protecting a wallet
 - Funding a wallet
 - Restoring a wallet from a backup

Preview of content to go in these pages - https://6061e8bfb8b80c000765a3de--lucid-mayer-522824.netlify.app/guide/onboarding/introduction/

**Comment by pavlenex** [comment]
After discussing with @ConorOkus 

Closing this in favor of #199 #201
