### ISSUE TITLE
Formatting page UI displays strangely on smaller screen sizes

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#183]
The UI of the [Formatting page](https://bitcoin.design/guide/contribute/formatting/) behaves strangely on smaller screen sizes. For example, when viewing on a tablet, the page has a slight horizontal scrollbar, which one can inadvertently scroll and shift the navbar partially offscreen. Also, when scrolling down the page, the sticky header gets cropped oddly to where the logo has no margin.

So far, I have only found this behavior on the Formatting page. Sorry I did not notice this when the PR #166 was still open. =)

Here is a video of what I am observing. Starting at 00:00, I demonstrate correct UI behavior. Around 00:24, I demonstrate incorrect UI behavior.
https://vimeo.com/525825688/085c4b5165

**Comment by GBKS** [comment]
I created a fix in PR #184. Could you please verify that it addressed the problem when you get a chance (no rush).

**Comment by sbddesign** [comment]
So I was reviewing PR #184 and yes, I can confirm that it did fix the problem I pointed out with this issue. However, I also uncovered another issue on the Formatting page. The issue is regarding the header width on iPad Pro. (Or any screen size about 1024px wide). I have confirmed the issue is present in both the *master* branch as well as your PR, and the issue is unique to the Formatting page. I do not witness it elsewhere.

Should I submit that as a separate issue, or would you like to address within the same PR?

See header below (does not extend full-width like on other pages):

![Screen Shot 2021-03-19 at 10 03 49 AM](https://user-images.githubusercontent.com/2414177/111792401-9a4cd600-889a-11eb-95b6-9afcbc8724d7.png)

**Comment by GBKS** [comment]
@sbddesign another good catch, thank you. Just pushed a fix. The "pre" tags with long lines of template code were causing the problem (which is why this only happened on for formatting page, as we don't display code elsewhere). Would you mind verifying the fix again?

**Comment by sbddesign** [comment]
Yes, it looks like it is fixed to me. 🥳 
I left an approval on #184 but it's still blocked until someone with write access leaves an approval.
