### ISSUE TITLE
Design Visuals for the Principles Section

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#190]
In #144 we've added the new `Principles` section in `Foundations`.

This page has great content but lacks some images as suggested by @GBKS 

This issue is currently up for grabs if you want to design the visuals for the page, just let us know. 🎨 🖌️

**Comment by sbddesign** [comment]
I'm in-progress working on some art for this issue, based on some ideas we discussed on a Jitsi call about a month ago. I will share when I am a little further along.

**Comment by pavlenex** [comment]
@sbddesign Do you need any help with this one?

**Comment by sbddesign** [comment]
Honestly, Miami happened and then I just got distracted with other tasks when I got back. I can pick this one back up.
I was toying around with an image for each principle. I can get this idea pushed a little farther along and then have something posted for critique this week. [Work In Progress](https://www.figma.com/file/xQ5eWVSOLbNGLmcls3qz7d/Principles?node-id=0%3A1)

**Comment by pavlenex** [comment]
@sbddesign How are you with the time this week? Do you think we'll be able to push this by EOW? Or next week? 
Just trying to clear up our to-do before we start big restructuring for the next content, LN included.

**Comment by sbddesign** [comment]
@pavlenex Yeah, I'll aim for progress report on Friday. I see you've added this to Sprint #6 which is set to finish by August 16. I think we can have this one all wrapped up by August 16th at latest.

**Comment by GBKS** [comment]
It's a pretty important section, so I would not rush this but shoot for quality.

**Comment by pavlenex** [comment]
2 weeks should be more than enough to design these though. We can always add what's missing or improve later on.

**Comment by GBKS** [comment]
I think it would be cool to find a minimal style that still clearly communicates the core of each principle. See [this video](https://youtu.be/6YDXBeGOtUk) for example.

**Comment by sbddesign** [comment]
Here are some more progressed designs to be discussed for using on the principles page.

![Screen Shot 2021-08-08 at 1 54 51 PM](https://user-images.githubusercontent.com/2414177/128648692-0030958e-0a32-414a-b892-4731630fb8dc.png)

[See Figma File
](https://www.figma.com/file/xQ5eWVSOLbNGLmcls3qz7d/Principles?node-id=0%3A1)

- Top row (incomplete) was my original hands concept I was toying with. I might forego that idea in the interest of not letting my toxic illustration maximalism suck up too much time, but it's there in case anyone absolutely loves it.
- Middle row - this was another idea I had of having each idea on a shield/coat-of-arms.
- Bottom row - a more Saul Bassy kind of thing, I started down this direction after watching the video Christoph linked.

I'm thinking of tweaking and improving the **middle row**. Thoughts anyone?

**Comment by GBKS** [comment]
One of the things I like about the bottom row is that it's less literal and more open for interpretation, which seems fitting for a set of principles. To give an example, for custody, the key makes me think very specifically about being in control of my private keys. The more abstract shapes can suggest the bigger concept of being an autonomous economic actor in control of my finances (and tech stack). Maybe this helps designers apply the principles more holistically to design decisions?

**Comment by pavlenex** [comment]
Really digging the third option. 🚀

**Comment by sbddesign** [comment]
3/3 commenters (2 here and 1 in Slack) like the bottom row.

I'll let it sit for a bit longer and see if other comments pour in, but that may be the direction to pursue. If so, I may try to do some more tweaks to the bottom row. Some of the principle designs have less energy than the others.

**Comment by Bosch-0** [comment]
I also like the third option as well. Feels less rigid / malleable, my thoughts as to why are pretty aligned with Christophs.

**Comment by pavlenex** [comment]
I think there's enough consensus to proceed and implement step 3. We have until 16th to make it into our [Sprint #6](https://github.com/BitcoinDesign/Guide/milestone/7).

**Comment by sbddesign** [comment]
On it.

**Comment by sbddesign** [comment]
Here's a PR for the Principles artwork. I couldn't resist putting on some jazz and fiddling with the art a little more:
[Deploy Preview](https://deploy-preview-453--sad-borg-390916.netlify.app/guide/designing-products/principles/)

There's some alternate header designs in the Figma file if anyone is interested in seeing:
[Figma File](https://www.figma.com/file/xQ5eWVSOLbNGLmcls3qz7d/Principles?node-id=0%3A1)

**Comment by GBKS** [comment]
Thanks for your work on this. The shadows and circle containers don't seem to go quite right with the Saul Bass reference. How about pushing the irregular shapes a bit further, like here? The inline images could also be in "distorted rectangles". Also think the self-custody image is a bit symmetrical compared to the others.
![principles](https://user-images.githubusercontent.com/695901/129531192-54c6d673-e200-42a4-b3e5-68a2cc92f774.png)

I don't think the formatting with the block quotes next to the images work. How about using bold text instead of block quotes?
