### ISSUE TITLE
Design visuals for Inputs and Outputs in the "Transactions" section.

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#195]
In #173 we've added new `Transactions` setion.
There's a paragraph explaining Inputs and Outputs.
Since that concept is usually better understood when visualized, would be great if someone can design a nice illustration that explains these.

![Screenshot 2021-03-29 at 11 55 35](https://user-images.githubusercontent.com/36959754/112820204-b06e4980-9085-11eb-93db-805ce6ff22fc.png)

If anyone wants to grab this one ping @johnsBeharry for guidance and help in understanding inputs and outputs.

**Comment by Bosch-0** [comment]
Relevant to #245
