### ISSUE TITLE
Apply new facts formatting across pages

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#198]
We should apply new formatting for facts across several pages we have.

![Screenshot 2021-03-29 at 17 25 41](https://user-images.githubusercontent.com/36959754/112860161-ddd1ec00-90b3-11eb-8060-d26b1104c226.png)

**Comment by GBKS** [comment]
Just created a PR to fix rendering of lists inside fact boxes, which is something we would need for this issue. See #206
