### ISSUE TITLE
Explore Github Pages for hosting the guide website

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#2]
There are several advantages to hosting the site via Github pages:

- Integrated with the Github collaboration tools
- Automatically reflects the latest codebase without any complex deploy processes
- Easy to configure due to Jekyll integration
- Integration with third-party tools like [Transifex](https://www.transifex.com) for localization

There are some known basics we can already explore (templating, search function, localization), but we will have to wait for the content and design to progress further to really know what all of our requirements are. We can either keep this issue open, or focus it on the basics and create more issues for future improvements.

**References:**
[Github pages marketing page](https://pages.github.com)
[Screencasts by Christoph](https://www.dropbox.com/s/k5vcheyd15na18i/Guide%20website%20structure%20200701.mov?dl=0)

**Comment by pedromvpg** [comment]
Some more progress done here:
https://pedromvpg.github.io/bitcoin-design-guide/

More structure, homepage, search, and more.

Still not going too much into design as I want to make sure this offers all the functionality we need and I also want to make sure we jumpstart the project with a more barebones/wireframy look and feel so the visual ui can emerge and evolve with the content of the guide.

**Comment by GBKS** [comment]
I believe we can safely assume that everybody is on board with this proposal. I'll close this issue on Monday, July 27, if there are no further comments.

**Comment by ConorOkus** [comment]
Happy to go with this, I would like us to look into if it's possible to do PR builds. So opening a pull request creates a "preview" version of the site so people reviewing can see the content on the site and not just in markdown.

**Comment by johnsBeharry** [comment]
@ConorOkus PR Commits can actually be easy if the fork has GitHub pages also enabled. Once the links resolve properly. Can be something added to the CONTRIBUTING.md

**Comment by GBKS** [comment]
@johnsBeharry that only works for forks and not for branches, right?

**Comment by pedromvpg** [comment]
I think it works with any PR: https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

**Comment by GBKS** [comment]
@pedromvpg that seems like feature by Netlify, no? So Github doesn't support it by default, but you can use Netlify to make it happen? Totally fine with me if that's the case.

**Comment by GBKS** [comment]
Pretty sure we can consider this one done for now. We are using Github Pages. Any changes can be discussed in new issues.
