### ISSUE TITLE
Onboarding - Protecting a wallet, funding a wallet & recovering a wallet (Designs needed)

### ISSUE THREAD

**Issue by ConorOkus** [BitcoinDesign/Guide#201]
This is issue is to create some page layout designs in Figma for the following pages:
 - [Protecting a wallet](https://docs.google.com/document/d/1wK69vADJQVe2Aoh_b66LD4vclwVXIsJejplYNUhEJtY/edit#heading=h.scvn97qkq6um) 
 - [Funding a wallet ](https://docs.google.com/document/d/1wK69vADJQVe2Aoh_b66LD4vclwVXIsJejplYNUhEJtY/edit#heading=h.877et24oemzl)
 - [Recovering a wallet](https://docs.google.com/document/d/1wK69vADJQVe2Aoh_b66LD4vclwVXIsJejplYNUhEJtY/edit#heading=h.rx85hgj9ikaz)

The content for these pages can be found in Google [docs](url)

**Comment by ConorOkus** [comment]
Page layout designs now available [here](https://www.figma.com/file/pI4W8hc1TpYC9kAbkyOwEw/Protecting-a-Wallet?node-id=168%3A2)

**Comment by GBKS** [comment]
Is there any feedback you want on the page layouts?

**Comment by ConorOkus** [comment]
I think some feedback on improving the pros on cons sections would be good. Maybe we already have a component that fits well already?

**Comment by GBKS** [comment]
What do you think can be improved about the Pros and Cons? How it's written, the actual tips, or how it's presented?

**Comment by GBKS** [comment]
I updated all screens in the wallet UI kit that are referenced in the designs and left comments in Figma. Feel free to use those, or not, as you'd like.

**Comment by ConorOkus** [comment]
I was going to say the visual layout for the pros and cons, we do use them in other areas of the guide, so it might be time to settle on a nicely styled component for them
