### ISSUE TITLE
Holistic guide review

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#202]
General review of the guide:
    - Cross-linking
    - Proof-reading (grammar, typos)
    - Proof-reading (does it make sense)
    - Consolidate

**Comment by danielnordh** [comment]
**WIP - Review dump** 
(will organize and tackle actions later)

- [bitcoin.design](https://bitcoin.design) 
  - Guide is not very prominent (Slack, Github, bitcoin.org all more prominent), Assume most visitors will want to consume content before contributing or joining slack to ask questions
  - Add Guide button among Slack/Github buttons? Replace Github? 
  - Remove link to bitcoin.org in subtitle
- [bitcoin.design/guide](https://bitcoin.design/guide/)
  - Tweak wording, feels a bit clunky and long, get straight to the content instead about talking about 'the guide project'
  - More focus on the chapter list (bigger styling?) 
- [bitcoin.design/guide/getting-started/](https://bitcoin.design/guide/getting-started/introduction/)
  - Shorten intro text
  - Feels like a lot of content to get through when looking at the subpages list
  - lowercase bitcoin in sidenav 'Why bitcoin is unique'
  - Review description of each subpage and see if core points can be incorporated (to potentially deliver 80% of the value of the chapter on this one page?)
  - Why design for bitcoin (do we need to convince people if they have managed to find this page?)
    - Be on the cutting edge / Blaze the trail, can these be combined? feel similar
  - Open design is a good page but does a reader really need to get through this before learning about bitcoin? (move?)
  - 'Personal finance' -> 'Personal finance and use cases'? (Link to case studies from the different use cases?)
  - Is User research page needed here / in the right place (has some unique things for bitcoin but most is not specific to bitcoin?)
  - Visual language
    - Unicode symbol - 'few fonts support...' mention Inter / other efforts to increase support?
  - Usage life-cycle is a good page, but has no bitcoin-specific info, cut/move?
  - Common user flows 
    - shorten intro text
    - 'Orientation' -> 'Awareness' ?
    - Onboarding - link to onboarding section
    - Creating a new wallet - mention common pk management schemes (link)
    - Securing a wallet - mention helping the user with backups (link)
    - Send bitcoin - show mobile example as well / instead of desktop
    - Receiving bitcoin - 'knowing when HAS BEEN sent and confirmed', missing words
    - 'Switch wallets' -> 'Migrate wallets' (import/export?)
    - Wallet maintenance - doesn't mention what might be required (oh, it does, but subheading is almost indistinguishable plus has the same size/type icon)
  - Technology primer
    - Bitcoin or bitcoin - explain Capitalized first to be consistent with subheading
    - 'Addresses are generated on your own computer', make less specific to include mobile etc., mention HD wallets / many under one master key? 
  - Split 'Getting started' in two? -> Getting started with Bitcoin / Designing bitcoin products
    - Getting started with Bitcoin
      - Why Bitcoin is unique
      - Visual language
      - Technology primer
      - Software overview
      - Hardware overview
    - Getting started design Bitcoin products (clunky name)
      - User research
      - Usage lifecycle
      - Personal finance
      - Common flows 

- Replace 'non-custodial' throughout with 'self-custody' ?

(to be continued)

**Comment by johnsBeharry** [comment]
From @Bosch-0 in #240 

> say native segwit instead of just segwit (segwit is written in all lower case also https://github.com/bitcoinops/bitcoinops.github.io/blob/master/STYLE.md)

**Comment by pavlenex** [comment]
I feel like we can close this issue as it's quite broad. We can open up issues per page/chapters to have a more focused to-do.
