### ISSUE TITLE
Website tech review

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#203]
General site optimization and device testing.
- SEO
- Performance
- Accessibility
- Mobile
- Search functionality
- Theme clean-up

**Comment by Bosch-0** [comment]
Great to see 'bitcoin design' search shows bitcoin.design as the first result!

**Comment by GBKS** [comment]
Performed [Lighthouse](https://developers.google.com/web/tools/lighthouse) tests on several pages for a general evaluation. Overall we are doing very well. There are some accessibility issues we need to fix, not all of which Lighthouse can capture (as they rely on interaction once the page has loaded).

<img width="2725" alt="image" src="https://user-images.githubusercontent.com/695901/114870426-74aee000-9df8-11eb-8540-916a69f25e28.png">
