### ISSUE TITLE
Add Satoshi symbol concepts to the "Visual language" page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#205]
There are various concepts for Satoshi symbols that should also be featured on the page for the [visual language of Bitcoin](https://bitcoin.design/guide/getting-started/visual-language/). I tried to gather the concepts [here in Figma](https://www.figma.com/file/ceVqp2xyQttnGc2h0AbZ8g/Bitcoin-Visual-Language?node-id=294%3A14).

**Comment by Bosch-0** [comment]
Relevant to #245

**Comment by Bosch-0** [comment]
Sat concept: https://github.com/bitficus/theSat

**Comment by pavlenex** [comment]
@GBKS Is this related to #61 a bit more? If so we can close it in favour of that one and add additional context there.

**Comment by GBKS** [comment]
It's a different thing, more about the creative explorations the Bitcoin community is doing. I just need to get this done, it won't take a long time and I have already gathered the visuals for it.

**Comment by pavlenex** [comment]
Ah I see, you want those random "sats symbol" attempts. In that case yeah, visual lang makes more sense.

**Comment by GBKS** [comment]
This is completed with #475.
