### ISSUE TITLE
Improve the Send Bitcoin page copy

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#209]
@danielnordh [suggested](https://github.com/BitcoinDesign/Guide/pull/181#issuecomment-811985424) some things that can be improved in the Send Bitcoin page.

Whoever prefers can tackle it, as Daniel clearly explained what to change on that page.

See it here:

https://github.com/BitcoinDesign/Guide/pull/181#issuecomment-811985424

**Comment by johnsBeharry** [comment]
just a note one the comments about the Dos and Don'ts if we use the "[Facts](https://bitcoin.design/guide/contribute/formatting/#facts)" component to show them it may resovle the problem of it sounding like a double negative.

**Comment by pavlenex** [comment]
#236
