### ISSUE TITLE
what License is this repo?

### ISSUE THREAD

**Issue by jdabs** [BitcoinDesign/Guide#211]
I see 4 license files and not much in the way of readme

![image](https://user-images.githubusercontent.com/6774432/113512347-3715a180-9532-11eb-9d7b-a1f522f05ed7.png)

**Comment by GBKS** [comment]
See the LICENSE file for an explanation. For more background on the licensing decision, please take a look at [this issue](https://github.com/BitcoinDesign/Meta/issues/15). Let me know if you still have questions.

**Comment by jdabs** [comment]
thanks for the explanation.
