### ISSUE TITLE
Add more bottom margin to some sections on visual language page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#226]
Should be some extra margin at the bottom of the paragraphs on the illustrations, the gold metaphor, memes, update by Bitboy and original symbol sections on the visual language page in the getting started part of the Guide. Issue shown below. 

![Frame 2](https://user-images.githubusercontent.com/55287964/114507936-66c95580-9c66-11eb-9b99-e0d407f4b042.png)

**Comment by GBKS** [comment]
100%. We need to review how margins and padding works across the various content elements. This is not a one-line CSS solution, as some of our layouts and components are a bit more intricate and basic spacing can throw things off in those advanced layouts.

**Comment by GBKS** [comment]
Related to #231 .

**Comment by Bosch-0** [comment]
Maybe we need a design system for the Guide for things like this?

**Comment by GBKS** [comment]
Yep, needs to go in this [Figma file](https://www.figma.com/community/file/862622015964353400/Bitcoin-Designers-site).

**Comment by Bosch-0** [comment]
Closing in favour of https://github.com/BitcoinDesign/Guide/issues/231
