### ISSUE TITLE
Make Contribute and Projects page banner image full width 

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#228]
Just a personal preference but having the banner images full container width looks nicer. Other areas of the guide such the top banner image on the Introduction page also are full container width so making these full width would be more consistent with that. Mock up before (top) and after (bottom) below:

![Frame 2](https://user-images.githubusercontent.com/55287964/114512388-a7779d80-9c6b-11eb-9922-e9fd9f043a8c.png)

**Comment by GBKS** [comment]
Totally agree on mobile. On desktop, we would run into the issue of taller headers pushing down the content too far that you have to first scroll before being able to read anything. According to [statcounter](https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide), the most common desktop resolutions are 1920x1080 and 1366x768. Both are widescreen, which makes full-width images easily take over a lot of space. Maybe there is solution somehow to stretch further on proportionally taller screens?

**Comment by Bosch-0** [comment]
Good point, for reference to those reading this is how it would look at the above mentioned resolutions - 1920x1080 aint so bad but 1366 is getting a little squished. 

![Frame 8](https://user-images.githubusercontent.com/55287964/114521971-7b611a00-9c75-11eb-8aa1-9ad5e5fb4de7.png)

For the projects image you could just insert a color fill into the container instead of stretching the image like so: 

![Frame 9](https://user-images.githubusercontent.com/55287964/114522931-68027e80-9c76-11eb-86df-bccd80cf2de4.png)

The Contribute image this can not be done though due to the textures in the image.

**Comment by GBKS** [comment]
Fixing spacing on mobile is addressed in #231 .

**Comment by GBKS** [comment]
Is this still relevant?

**Comment by GBKS** [comment]
Is this still relevant?

**Comment by Bosch-0** [comment]
I still think it's an, albeit minor, improvement aesthetically
