### ISSUE TITLE
Fix keyboard-only navigation of the site

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#239]
[Here's an overview](https://webaim.org/techniques/keyboard/) on this topic. This is generally in good shape, but there are a few things to fix. Here's what I am aware of:

- A hidden "Skip to content" button so screen readers don't have to tab through the nav on every page. [More here](https://webaim.org/techniques/skipnav/)
- Focus management of the search and mobile nav overlays
- Review all the components on the formatting page

[axe](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd), in addition to Lighthouse, is a good tool for accessibility testing.

**Comment by pavlenex** [comment]
Slightly related to #372

**Comment by Mogashni** [comment]
I performed a keyboard only navigation test of the main guide menu page, here's a link to my experience there, still will need to test it on mobile.
https://docs.google.com/document/d/1Ml6eKyshNzIF_VSmYEDG8mRVXmybjXltyw6yArCtshE/edit?usp=sharing

**Comment by Mogashni** [comment]
Continued with the accessibility check. Here's what I found:
1) Skip to navigation needs to be fixed (you are already aware of this on though :-))
2) Looked at the alt text of the images, 90% of the images had alt texts only the two small button like images right at the top of the page did not have alt text.

https://docs.google.com/document/d/1Ml6eKyshNzIF_VSmYEDG8mRVXmybjXltyw6yArCtshE/edit?usp=sharing

Will continue checking these last two and then update:

- Focus management of the search and mobile nav overlays
- Review all the components on the formatting page 
- Appropriate aria tags
