### ISSUE TITLE
Onboarding - Protecting a Wallet Page 

### ISSUE THREAD

**Issue by ConorOkus** [BitcoinDesign/Guide#242]
This issue is to add the protecting a wallet page to the website.

The Figma design can be found here - https://www.figma.com/file/pI4W8hc1TpYC9kAbkyOwEw/Protecting-a-Wallet?node-id=168%3A2

Please feel free to leave comments on the designs if you have any feedback.

**Comment by pavlenex** [comment]
Done in #302 🚀
