### ISSUE TITLE
Onboarding - Restoring a Wallet Page

### ISSUE THREAD

**Issue by ConorOkus** [BitcoinDesign/Guide#243]
This issue is to add the restoring a wallet page to the website.

The Figma design can be found here - https://www.figma.com/file/pI4W8hc1TpYC9kAbkyOwEw/Protecting-a-Wallet?node-id=187%3A22

Please feel free to leave comments on the designs if you have any feedback.

**Comment by Bosch-0** [comment]
Is the current up to date copy also included in this design? Would be nice if that was the case so feedback could be given for both copy and the design :)

**Comment by ConorOkus** [comment]
Yeah this is the latest so feel free to leave feedback on Figma or here.

**Comment by Bosch-0** [comment]
Cool, left some comments yesterday will go over it again today in more detail :)

**Comment by pavlenex** [comment]
Done in #302 🚀
