### ISSUE TITLE
Onboarding - Funding a Wallet 

### ISSUE THREAD

**Issue by ConorOkus** [BitcoinDesign/Guide#244]
This issue is to add the funding a wallet page to the website.

The Figma design can be found here - https://www.figma.com/file/pI4W8hc1TpYC9kAbkyOwEw/Protecting-a-Wallet?node-id=192%3A0

Please feel free to leave comments on the designs if you have any feedback.

**Comment by Bosch-0** [comment]
> This issue is to add the protecting a wallet page to the website.

Typo in your OP btw ConorOkus - should be ...funding a wallet page to the webiste...

**Comment by pavlenex** [comment]
Done in #302 🚀
