### ISSUE TITLE
[Image Request] Foundations page banner image

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#250]
A minimalist concept I did for the foundations page banner image following a similar suite to the banner images used in the private key management pages. 

![Frame 28](https://user-images.githubusercontent.com/55287964/115379437-1b81ea80-a204-11eb-8368-fd2ec40191d4.png)

I will be posting some more detailed concepts soon. It would be great to get others posting concepts in this thread and we can vote and settle on one. It would be good if this process was repeated for other designs contributed by the community for the guide. 

Relevant to #245

**Comment by pavlenex** [comment]
@Bosch-0 LGTM, let's do a PR and make the Foundations page pop a bit more?

**Comment by Bosch-0** [comment]
Here is one with a little color + shadow

![Frame 33](https://user-images.githubusercontent.com/55287964/115548947-a46b5580-a2da-11eb-9ef6-1b2a08b840db.png)

**Comment by GBKS** [comment]
If we keep using minimalist images (which I'd be careful not to over-use), I'd like to see if we can add depth somehow. What is a foundation in general, and in this context? The principles page is a helpful tool for making decisions. How do you visualize solid decision-making? This is different than the foundation of a house, which is meant to be immovable. Will try to think in this direction a little more.

**Comment by Bosch-0** [comment]
Foundations page no longer exists so closing this issue.
