### ISSUE TITLE
[Image Request] Create a wallet page banner image 

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#255]
A banner image is needed to be designed for the onboarding/Create a wallet page which is currently under [PR review](https://github.com/BitcoinDesign/Guide/pull/225). Feel free to post your design ideas below! 

Relevant to #245

**Comment by paulosacramento** [comment]
Working on some ideas for the header.

**Comment by paulosacramento** [comment]
Here's my suggestion for the image header, that has already received some support from @ConorOkus and @sbddesign on Slack:

- https://drive.google.com/open?id=1pIhLL1bN80tdiL1SyMew5yE86egf0aHn

![header3](https://user-images.githubusercontent.com/76049494/116263376-9ce3fa80-a779-11eb-82be-c98a27a11f8c.jpg)

**Comment by paulosacramento** [comment]
![header-creating-a-new-wallet-2](https://user-images.githubusercontent.com/76049494/119857423-d6905880-bf13-11eb-9b38-f069092b7b57.jpg)

What do you guys think about this version?

**Comment by Bosch-0** [comment]
I like the second one :)

**Comment by pavlenex** [comment]
Nice @paulosacramento do you need any help with making a pull request for this one, let's get this baby added.

**Comment by paulosacramento** [comment]
> Nice @paulosacramento do you need any help with making a pull request for this one, let's get this baby added.

I will need some help to create this pull request... What is the easiest to set a new image header for the page?

**Comment by paulosacramento** [comment]
I will check it right now. Thank you very much! :D

**Comment by Bosch-0** [comment]
Do we have a Figma file with a template for all the required sizes? If not, would be handy!

**Comment by GBKS** [comment]
Header image sizes are described [here](https://bitcoin.design/guide/contribute/illustration-guidelines/#export-images-at-the-right-sizes) and link preview [here](https://bitcoin.design/guide/contribute/illustration-guidelines/#link-preview-images).

**Comment by paulosacramento** [comment]
I found the guidelines regarding size and etc here: https://bitcoin.design/guide/contribute/illustration-guidelines/

**Comment by ConorOkus** [comment]
Looks great @paulosacramento .

Wanted to bring up some designs @GBKS has been working on for the entire section that I quite like as well.

https://github.com/BitcoinDesign/Guide/issues/358

I like the concept & the consistency it provides, how do people feel about going in this direction?

**Comment by ConorOkus** [comment]
I also appreciate it might reduce the ability for people to add their own individual creatives to the headers.

**Comment by paulosacramento** [comment]
Oh, wow. Awesome stuff. Let's move forward with @GBKS designs. I wasn't aware of his work.

**Comment by ConorOkus** [comment]
He won't be around to finish them up, so do you want to help with that?

**Comment by paulosacramento** [comment]
I will try to work create different headers based on his file (one for each page) following his initial concept. Let's see how this goes.

**Comment by paulosacramento** [comment]
https://www.figma.com/file/Oujucpquq1Ftk4FJVtritF/header?node-id=1527%3A0

Here's the Figma file.

**Comment by pavlenex** [comment]
#366
