### ISSUE TITLE
Move 'Foundations' section higher up on menu

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#257]
Would it not make sense to include the foundations closer to the start of the Guide? If somewhere were to read from start to finish, laying out the foundations first makes the other sections of the Guide make more sense.

 When reviewing the create a wallet page for on boarding today I couldn't help but think 'what kind of wallet' are we creating. It mentions selfy-custody wallets but had I read the foundations first things would of pieced together nicely in my mind.  Maybe include it after Getting started like below: 

![Group 201](https://user-images.githubusercontent.com/55287964/115681210-e520a880-a386-11eb-8b04-bf7fb928d02f.png)

**Comment by GBKS** [comment]
Make sense to me.

**Comment by danielnordh** [comment]
The contents of Foundations is currently just

- Principles
- Wallet interoperability (which in itself is one of the Principles)

Moving Principles up on it's own makes sense in my view as it is a good primer for how we have approached the guide.
That leaves Foundations rather empty, but I wouldn't worry to much about that now as it's always been more of an 'appendix' or grab bag that doesn't fit elsewhere.

**Comment by Bosch-0** [comment]
Just a suggestion but the principles page makes more sense being in the 'Getting started' chapter and the wallet interoperability page could be removed and we just make sure that this concept is discussed in the relevant sections of the guide.

For example, the multi signature wallet content in wallet interoperability could be intertwined into the multi-key page in PKM chapter.

**Comment by GBKS** [comment]
Is this still relevant with [the comments](https://github.com/BitcoinDesign/Guide/issues/330#issuecomment-844632776) around moving the foundations pages to the new "Designing Bitcoin products" section?

**Comment by danielnordh** [comment]
I could see the Principles fitting early into 'Designing Bitcoin products'.
Thoughts?

**Comment by Bosch-0** [comment]
> I could see the Principles fitting early into 'Designing Bitcoin products'.
> Thoughts?

Yep I agree. Was going to open a PR moving principles / wallet interoperability into designing bitcoin products. Will close this after that.

**Comment by GBKS** [comment]
Created PR #346 for this. Check the [preview](https://deploy-preview-346--sad-borg-390916.netlify.app/guide/designing-products/principles/).
