### ISSUE TITLE
Create a custom 404 page

### ISSUE THREAD

**Issue by ConorOkus** [BitcoinDesign/Guide#26]
Go crazy!

Here is some inspiration - https://www.creativebloq.com/web-design/best-404-pages-812505

**Comment by GBKS** [comment]
I really like the 404 page by the financial times. Not very visual, but highly targeted to the audience - [check it out](https://www.ft.com/banana).

**Comment by mrsellars** [comment]
![Bitcoin Design 404](https://user-images.githubusercontent.com/9872/94199756-962a9780-feb9-11ea-8fe4-3aaa89571bec.png)

First draft made with Sketch. Font is `Inter` and the nice illustration is from Icons8 (https://icons8.com/illustrations/style--flame).

**Comment by ConorOkus** [comment]
Nice one @mrsellars . I wonder if this is another candidate for theming, similar to the banner? - https://github.com/BitcoinDesign/Guide/pull/27

**Comment by GBKS** [comment]
I like it. And cool that Icons8 has free illustrations, the low-res PNG (high-res and SVG are paid) is good enough for our needs here.

Licensing-wise, we can use this as long as we put two links on the site, one to Icons8 and one to the illustration page (that HTML can be copied from the site). More [here](https://icons8.com/vue-static/landings/pricing/icons8-license.pdf). According to the license, we cannot modify the illustrations, but adding a background like in this design should be good.

**Comment by mrsellars** [comment]
@ConorOkus @GBKS happy that you like it. I think also that the low-res version should be good enough for a start.

Theming sounds like a good idea too. Will have a look to the mentioned ticket from Conor.

Do we have a Figma file somewhere? I would upload it there.

**Comment by AlexaAker** [comment]
Nice choice of image, and wording too @mrsellars ! 

Christoph's template files for images that can become themes on Figma: https://www.figma.com/file/RZfxlwn0SyRpIQiCl02PQb/Bitcoin-Design-Community-Website-Banner-Template?node-id=1%3A129

& the GitHub issue: https://github.com/BitcoinDesign/Guide/pull/27

**Comment by GBKS** [comment]
So far the template and theming support is specifically for the home page banner. We could choose to use the banner component and theming technique here also, but I am not sure whether we want to invest a lot of time into 404 pages. What do you think?

**Comment by ConorOkus** [comment]
Yeh I think the design can just be rotated every few months for this, agree with not investing too much time

**Comment by mrsellars** [comment]
@AlexaAker great that you like the wording and image and thanks for the feedback. 

I will put the 404 draft somewhere in Figma and will leave the Theming part out of scope for the time.

**Comment by GBKS** [comment]
@mrsellars thanks for sharing the Sketch file on Slack. I imported it to Figma into the main file for the website, [see here](https://www.figma.com/file/K5ahSqVzoMVBuhT5hAVRJr/Bitcoin-Designers-Website?node-id=0%3A1). I added responsive layouts (so those considerations don't have to happen during development) and a top navigation which we don't need right now, but we'll have later with the full site and will give users on this page a few more options to find what they are looking for. As this is your design, please hop in and make any tweaks you'd like. I tried to stay as close as possible to your Sketch file.

<img width="1640" alt="404-201020" src="https://user-images.githubusercontent.com/695901/96554312-a5cdae00-12b6-11eb-9f67-9e881da96291.png">

**Comment by mrsellars** [comment]
@GBKS cool, thank you. I like the different screens. Going to write some HTML/CSS for the 404 page this week and will provide a pull req. for it.

**Comment by GBKS** [comment]
Awesome. Make sure to sync with Conor, he was also thinking about working on this.

**Comment by mrsellars** [comment]
Ah, good to know. Will reach out to him via Slack.

**Comment by GBKS** [comment]
@mrsellars @ConorOkus are you still planning to make these final tweaks to the 404 page?

**Comment by ConorOkus** [comment]
Yeh we spoke about this recently, @mrsellars is hoping to finish up soon 👍
