### ISSUE TITLE
Use a better example on Getting started/common user flows software onboarding

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#266]
Currently blockchain.com's wallet is used as an example for [software onboarding](https://bitcoin.design/guide/getting-started/common-user-flows/#software-onboarding) in the Getting started/common user flows section of the Guide. I think it would align more with our principles if we used a better, more trust-less, non-custodial, wallet as an example - maybe Muun, Breez or Bluewallet?

**Comment by GBKS** [comment]
Good call. I have a ton of [Muun screenshots here](https://www.figma.com/file/rPyJ0Y8xg0kN4FrHFCeDRg/Muun-wallet?node-id=0%3A1) we can use. Could also switch to use the image slide gallery component.

**Comment by Bosch-0** [comment]
Yep Muun is a great option. +1 on using the slide gallery as well here that would be cleaner :)
