### ISSUE TITLE
Website Homepage Banner Proposal • Abstract Bitcoin Banner Design

### ISSUE THREAD

**Issue by Rama-Krushna** [BitcoinDesign/Guide#272]
Hey everyone,
I would like to contribute this header design for the Bitcoin Design website.

Thanks
[Rama Krushna](https://ramakrushna.com)

Figma Link to Design: [Click Here](https://www.figma.com/file/sdau9c1gmd8QFXEFkRe4uT/bitcoin.design-Website-Cover?node-id=0%3A1)

![image 4](https://user-images.githubusercontent.com/39101209/116608710-27cb1d80-a951-11eb-91d6-48056137ef92.jpg)

![Desktop v1](https://user-images.githubusercontent.com/39101209/116608745-30235880-a951-11eb-9927-bb97afddfb2a.jpg)

**Comment by Rama-Krushna** [comment]
**Image Credits:**

- Statue: https://unsplash.com/photos/wZfndoCA1rA
- Bitcoin: https://unsplash.com/photos/aX1hN4uNd-I
- Flowers: https://unsplash.com/photos/5TK1F5VfdIk
- Map: https://unsplash.com/photos/0XUnd0bXqTE
- Hand: https://unsplash.com/photos/jaWqPEPemvU

**Comment by GBKS** [comment]
This design is live now. Great work @Rama-Krushna .
