### ISSUE TITLE
Unable to scroll in the menu section

### ISSUE THREAD

**Issue by Niekon01** [BitcoinDesign/Guide#276]
![Capture](https://user-images.githubusercontent.com/55133485/116665173-09980880-a9b7-11eb-9e74-b19cf226021a.PNG)

**Comment by GBKS** [comment]
Thanks for reporting. This should be fixed in #277. Could you please take a look at the preview link and verify it's fixed for you? [Preview link](https://deploy-preview-277--sad-borg-390916.netlify.app/guide/).

**Comment by Niekon01** [comment]
Yup, it works fine!
