### ISSUE TITLE
Restructure private key management pages

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#280]
As you can see in the screenshots below, the [Personal schemes page](https://bitcoin.design/guide/private-key-management/single-user-schemes/) is super long. It covers 5 techniques that can be easily split out into their own pages, making the content easer to navigate. It will also allow us to go a bit deeper into each technique as we don't have to be worried about page length.

![Frame 3](https://user-images.githubusercontent.com/695901/117019401-a7604000-acf5-11eb-9fb2-89addc770a55.png)

Here is a proposed new page structure.

<img width="908" alt="Frame 60" src="https://user-images.githubusercontent.com/695901/117020009-4be28200-acf6-11eb-89c8-9b1aa4ebab4f.png">

@danielnordh I'm curious to get your thoughts on this.

**Comment by Bosch-0** [comment]
+1 this - I much prefer this layout it communicates things a lot more clearly.

**Comment by danielnordh** [comment]
I'm OK with splitting it up.
It will require some re-framing as it's currently written with the personal/shared split (which in itself may not make much sense so I'm not precious about it)

**Comment by GBKS** [comment]
What's the best process here? I could create a PR with a pure split-up and then we can all take a look at the preview and see what needs adjusted?

**Comment by GBKS** [comment]
Created a rough preview of this in #283. [See the preview](https://deploy-preview-283--sad-borg-390916.netlify.app/guide/private-key-management/introduction/). Haven't rewritten anything, just split up the pages and updated URLs and some links so we can feel this change out.
