### ISSUE TITLE
Extract address content from Glossary into a sub-page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#281]
[The information](https://bitcoin.design/guide/glossary/#address) is good, but too much for the glossary, which is meant for short explanations. We could put this new "Addresses" page under foundations, or under glossary. Glossary doesn't have sub-pages at the moment, but this is something we've discussed before.

![bitcoin design_guide_glossary_ (5)](https://user-images.githubusercontent.com/695901/117020403-b267a000-acf6-11eb-9be2-8cf4bc1fa272.png)

**Comment by johnsBeharry** [comment]
FYI issue #107 outlines more user facing content for such an address page in foundations.
