### ISSUE TITLE
Extract wallet content from Glossary into a sub-page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#282]
[The information](https://bitcoin.design/guide/glossary/#wallet) is good, but too much for the glossary, which is meant for short explanations. We could put this new "About wallets" page under foundations, or under glossary. Glossary doesn't have sub-pages at the moment, but this is something we've discussed before.

![bitcoin design_guide_glossary_ (8)](https://user-images.githubusercontent.com/695901/117021012-3faaf480-acf7-11eb-9ff8-231fd6352978.png)

**Comment by pavlenex** [comment]
@GBKS Fair suggestion. How can we connect that, Wallet Kit UI and `Create a new wallet` into onboarding? 
Seems like there are a few overlapping parts, all of them relate to `wallet`.

**Comment by Bosch-0** [comment]
This overlaps with https://github.com/BitcoinDesign/Guide/pull/256/files, I'll get on to that asap for it to be merged

**Comment by GBKS** [comment]
I think the wallet UI kit is something totally different. As far as the topic of wallets, I'd focus the glossary sub-page solely on the disambiguation of the terms (list terms with descriptions including some small amount of technical detail as needed). Designing experiences is covered by the onboarding section.

**Comment by GBKS** [comment]
This is complete with the merge of #410.
