### ISSUE TITLE
[Image Request] Visual Language page needs a header image

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#288]
The [visual language page](https://bitcoin.design/guide/getting-started/visual-language/) needs a [header image](https://bitcoin.design/guide/contribute/formatting/#images).

![Screenshot 2021-05-06 at 18 15 36](https://user-images.githubusercontent.com/36959754/117331498-188b2900-ae97-11eb-9fe9-f0fd41a3726b.png)

This one is available for grabs to whoever wants to design such a header image. Feel free to comment here if you want to help out.

**Comment by sbddesign** [comment]
I started a slack thread for this issue:
https://bitcoindesign.slack.com/archives/C015856BDME/p1620857550319600

**Comment by sbddesign** [comment]
From our slack thread:
> I’ve been doing some thinking for issue #288 (designing a header for the visual language of Bitcoin page). The page goes into detail about how there is no official art direction for Bitcoin — things can range from minimalist to highly expressive. So I have been sketching out ideas where we could try to collage existing Bitcoin graphics. Perhaps a person is speaking and the graphics are exploding outwards. Perhaps we take Bitcoin visuals and place them in the speech bubbles. Or we could just go super Swiss and make a typography specimen filled with Bitcoin terms and symbols. Ok, that’s what I got for today.

![visual-1](https://user-images.githubusercontent.com/2414177/118150554-af4c6e00-b3e0-11eb-923e-8b0dbe179431.png)
![visual-2](https://user-images.githubusercontent.com/2414177/118150557-afe50480-b3e0-11eb-907d-a6877c5909c1.jpg)
![visual-3](https://user-images.githubusercontent.com/2414177/118150559-afe50480-b3e0-11eb-9a8d-28956c12bcd8.png)

**Comment by pavlenex** [comment]
Looks nice @sbddesign do you intend to continue with the PR for this one?

**Comment by sbddesign** [comment]
@pavlenex Yes, but it's not quite PR ready yet. I'll be bringing some newer drafts of this art to the Design Jam call today.

**Comment by sbddesign** [comment]
After discussing my image ideas on the last Design Jam call and doing some more thinking, I arrived at this concept. It's simpler, but hopefully conveys that the same idea can be expressed in different ways.

## Figma Mockup
Look for the MacBook pro mockups at the bottom of the page to see what the art would look like in the Guide.
[See Figma File](https://www.figma.com/file/3RmrEH8560q4IgzVsvDm65/Bitcoin-Visual-Language?node-id=0%3A1)

## Realistic Palette
![visual-language-sample@0 5x_noised](https://user-images.githubusercontent.com/2414177/119241503-c7c93080-bb24-11eb-95f2-c53cb8eecea6.png)

## Stylized Palette
![visual-language-sample-alt@0 5x_noised](https://user-images.githubusercontent.com/2414177/119241506-cac42100-bb24-11eb-985f-e74daf3e6d00.png)

Any thoughts on colors? The "realistic" warm palette is kind of nice, but the stylized would be more in line with what I did for the [Sending Bitcoin](https://bitcoin.design/guide/payments/send/) page.

**Comment by pavlenex** [comment]
I like both, ack for whatever you guys decide, please don't use the wrongly tilted B. That's a nack on my end 😄

**Comment by sbddesign** [comment]
Updated with centered and uniformly tilted Bs:

![bitcoin-visual-language](https://user-images.githubusercontent.com/2414177/119359508-b6446d80-bc77-11eb-8bcd-ad03175dee63.jpg)

**Comment by pavlenex** [comment]
Looks great @sbddesign ,loving it!

**Comment by pavlenex** [comment]
Done in #344, great work @sbddesign 🔥
