### ISSUE TITLE
Header Theme Proposal | Bitcoin Quilt Design

### ISSUE THREAD

**Issue by jleahwolff** [BitcoinDesign/Guide#289]
### **Bitcoin Quilt**

Hi everyone, 

I'd like to contribute my Bitcoin Quilt design as a proposed addition to the homepage of [Bitcoin.Design](https://bitcoin.design). 
[Figma file](https://www.figma.com/community/file/970562086971594298/Bitcoin.Design-Website-Banner)

![github-img](https://user-images.githubusercontent.com/54365640/117332769-d98cb180-ae5d-11eb-9c63-da8fdf25428d.jpg)

Working with Andy, we'd like to have it animated. [Here is his work ](https://satsymbol.com/promote/jessicaillos1.html) so far to some of the quilt squares. (Click the animation to cycle through the designs). 

Thanks! 
_Jess_

**Comment by AndyRibetz** [comment]
Animation examples here (10 sec loop)
![animation_500_kod5ubg1](https://user-images.githubusercontent.com/83780625/117340160-739c2c00-ae55-11eb-839d-3742786fd7b7.gif)
![animation_500_kod5riiw](https://user-images.githubusercontent.com/83780625/117340174-7860e000-ae55-11eb-8a3f-38936fca5ed4.gif)
![animation_500_kod5p0f0](https://user-images.githubusercontent.com/83780625/117340185-7b5bd080-ae55-11eb-9517-4189d0bb7dec.gif)

**Comment by sqcken** [comment]
This is great. I love it.

**Comment by pavlenex** [comment]
@jleahwolff @AndyRibetz you guys are killing it 🚀

**Comment by Bosch-0** [comment]
Love it!

**Comment by johnsBeharry** [comment]
These are awesome!

**Comment by GBKS** [comment]
Thanks for posting. I implemented the static design in PR #292. You can [preview it here](https://deploy-preview-292--sad-borg-390916.netlify.app). We don't have Lottie implemented on the site, but we can figure that out whenever you're ready with the animations.

Two small things I noticed in Figma. The droopy syrup graphic is slightly cut off at the top and bottom, probably half a pixel, maybe due to centered or outlines strokes getting cut off in whichever tool you used to create them. The second thing is that that images are a little bit too small for export on desktop/retina. Could you please update them to at least 1440px width/height?

Let me know if you'd like to tweak anything else.

**Comment by AndyRibetz** [comment]
> We don't have Lottie implemented on the site, but we can figure that out whenever you're ready with the animations.

Thank you Christoph, without knowing how the embedding works on bitcoin.design in my experience embedding Lottie is as easy as posting a jpg in html. 2 lines of code - see source [here](https://satsymbol.com/promote/jessicaillos3.html) for example.

What I'd like to do is send you the entire quilt as one Lottie file (animations will run automatically). Would you be willing to do that? 

Thanks,

Andy

**Comment by AndyRibetz** [comment]
@GBKS @jleahwolff preview animated quilt here: https://satsymbol.com/promote/bitcoindesignquilt.html

This is really all you need - just change the size params, all vector so we can't lose image quality :) Let me know if you have any questions.

`<script
                    src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script><lottie-player src="https://assets1.lottiefiles.com/private_files/lf30_1t3b29q1.json" background="transparent" speed="1" style="width: 800px; height: 800px;" loop autoplay></lottie-player>`

**Comment by GBKS** [comment]
thanks @AndyRibetz . The trick with the banner is just that we rotate themes. The existing Javascript uses CSS variables to update the theme, so I need to add code to switch between that method and a Lottie animation when needed. Nothing too complicated, just need to do it. And it will be nice to have Lottie available throughout the site, I think there are some areas where animation would help to communicate things more effectively (specifically certain technical aspects around transactions and the network).

**Comment by pavlenex** [comment]
>  I think there are some areas where animation would help to communicate things more effectively

Oh yeah, baby! This this this 💯

**Comment by paulosacramento** [comment]
OMG! I love this!

**Comment by jleahwolff** [comment]
Sorry I didn't see this before, @GBKS. Here is the honey and bee's for the document. 
![honey+bees](https://user-images.githubusercontent.com/54365640/118054348-b83f3000-b34b-11eb-8e58-9acfec1cd92b.png)

**Comment by GBKS** [comment]
Just a heads up, the live version uses static images. Getting the animated ones in there will require some dev work which we can tackle in a new issue/PR.

**Comment by sbddesign** [comment]
Update: the animated version was launched on the site in #805
