### ISSUE TITLE
Auto highlight textfield when clicking search button

### ISSUE THREAD

**Issue by danielnordh** [BitcoinDesign/Guide#297]
Expected behavior: When clicking on the 'search' icon in the menu bar, visitor should be able to start typing on the keyboard

Current behavior: Visitor need to click again, on the search field that popped up after clicking search icon

**Comment by GBKS** [comment]
That's how it works for me. Which OS & browser are you on? And which page did you test this on?

**Comment by GBKS** [comment]
I tested in desktop Safari 14.1 and can't reproduce it.

**Comment by danielnordh** [comment]
Closing as it seems too random to worry about.
