### ISSUE TITLE
Create recommendations for the display of amounts

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#3]
Every Bitcoin software will display amounts of Bitcoin or Satoshi, but there are various details to consider around how the numbers are formatted. There have been discussions in Slack, and since it's a common "problem", maybe we should come up with recommendations to include in the guide.

[Slack conversation](https://bitcoindesign.slack.com/archives/C014J9ZKXB4/p1593409185490700)
[Figma summary](https://www.figma.com/file/iUhCkFNFwn29j5w4YFDsQq/Bitcoin-address-and-amount-display?node-id=0%3A1)

**Comment by BitcoinErrorLog** [comment]
For BTC, I prefer Decimal Period, as I think non-americans grasp it better than americans grasp commas.
For SAT, I prefer Satoshi + Spaces -- millisats is still an issue though... maybe best to treat as a 3rd unit type

**Comment by GBKS** [comment]
Closing this one as the topic is being tackled in #61 .
