### ISSUE TITLE
Change case studies 'checking account' to 'savings account'

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#307]
Checking account is not as universal globally. We don't really use the term here in Australia for example. We should change it to something that is more universally understood like savings account. 

This page is also called 'multisig-wallet' when it should be called the name of the page.

**Comment by GBKS** [comment]
I also think "Savings" is better.

By "page is called" you mean the file name and URL segment, right?

**Comment by Bosch-0** [comment]
Yep sorry, meant the markdown file and URL is called multisig-wallet.
