### ISSUE TITLE
Add shamir backup to 'Bitcoin backups' page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#310]
Shamir backups is another, not so widely adopted, form of backup that is not mentioned in this section of the guide. 

Shamir backup - https://trezor.io/shamir/
SLIP-0039 - https://github.com/satoshilabs/slips/blob/master/slip-0039.md

**Comment by GBKS** [comment]
If I remember correctly, Shamir is not recommended because it has a single potential point of failure since you rely on a central party to create the key, split it, and distribute it. You don't have this with other multisig approaches where the keys are created independently. But there is probably more to this topic (maybe this property is even desired in certain scenarios?), and could be worth discussing.

**Comment by danielnordh** [comment]
This depends a bit how we see the page:

- As a quick-start guide to simple backup strategies for USERS
- As a complete list of all possible backup strategies

It started as the former.
I personally don't feel comfortable recommending Shamir over using a pass-phrase (which achieves the same protection against *theft-on-discovery*).

However, we could add a section with references to other available options, like Shamir, but not cover it in detail.

**Comment by pavlenex** [comment]
> I personally don't feel comfortable recommending Shamir over using a pass-phrase (which achieves the same protection against theft-on-discovery).

I'm in the same boat regarding this. ⛵ 

> add a section with references to other available options, like Shamir, but not cover it in detail.

Agreed, we shouldn't recommend what we don't feel comfortable with, but if it can be beneficial for certain users, we can cross-reference.

**Comment by Bosch-0** [comment]
>  I personally don't feel comfortable recommending Shamir over using a pass-phrase (which achieves the same protection against theft-on-discovery).

> Agreed, we shouldn't recommend what we don't feel comfortable with, but if it can be beneficial for certain users, we can cross-reference.

It has its own dedicated page, I think that's more of a recommendation than having it as part of the backups page. We can give details on it and then say it's _not_ recommended - it's important we advise against it. 

Shamir's is a bad way to backup / share keys though yes, completely agree. Regardless it is adopted by one of the biggest hardware wallet products on the market, Trezor, through SLIP-0039 so people will encounter it so its worth having some detail. 

https://docs.keys.casa/wealth-security-protocol/rejected-key-schemes/key-sharding-shamirs-secret-sharing

> As a complete list of all possible backup strategies

It reads a lot more like this to me currently. Now we have the pages split up though it makes more sense to include the backup details for that scheme within the respective page

**Comment by danielnordh** [comment]
PR for this #316

**Comment by pavlenex** [comment]
Done in #316
