### ISSUE TITLE
Revise home page call-to-actions

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#320]
This issue is based on @danielnordh's review and ideas about ensuring that the home page guides users to all the right places.
- Primary buttons lead to Slack and Github. Should one of those go to the guide?
- Should we list projects on the home page like the icon set, UI kit, etc?
- Should the page content mention and link to the Contribute and Projects pages?
- Should we include a link to FOSDEM or Config presentation videos?

If you have more ideas, please leave a comment below.

**Comment by pavlenex** [comment]
> Primary buttons lead to Slack and Github. Should one of those go to the guide?

I'd go with replacing the `GithHub button` wit the `Bitcoin Design Guide` at least for the launch, we can always modify this later on.

> Should we list projects on the home page like the icon set, UI kit, etc?

Since we agreed we don't want to push them just yet and focus on the design guide, perhaps it's out of scope for the Milestone 5, but we should def consider prominently displaying them in the future.

> Should the page content mention and link to the Contribute and Projects pages?

I think this is a good middle ground for the above question as well, easy to do a quick fix and add a link without overthinking about the layouts etc, since we want to act quickly.

> Should we include a link to FOSDEM or Config presentation videos?
 
I don't have a preference here, I would add it unless it requires lots of layout changes, as we don't have much time, we can always add this in a blog post announcement.

**Comment by danielnordh** [comment]
I'm supportive of replacing the Github button with the Guide
Agree with Pavlenex on the other points as well.
No preference on the video for now.

**Comment by Bosch-0** [comment]
If we aren't planning on updating our slack plan, GH should be the primary button and slack secondary. A lot of content is being expunged from slack making it less useful. At least with GitHub we have a more solid history of discussions / contributions etc.

**Comment by moneyball** [comment]
It would cost $120,000 a year and increasing over time.

**Comment by Bosch-0** [comment]
Damn, definitely not worth it then.

**Comment by moneyball** [comment]
It is really unfortunate Slack does not have better options for free,
open-source communities. $6.67/month/user is a non-starter for such
communities. Also there is no distinction between "regular contributor" and
"joined Slack to check it out but haven't been back since."

**Comment by pavlenex** [comment]
If we're talking about using alternatives, we should open a new discussion. Regular contributors usually don't mind switching over to whatever platform. Keeping a historic track of conversations is important. Mattermost is what we've been using for BTCPay. 
However, most designers are familiar with and use slack so joining yet another workspace is easy, some people who are not regulars as Steve mentioned, wouldn't bother joining and using yet another app unless they have a good use-case/need to join. But perhaps that's not bad either, active contributors is what counts, come-and-go ones aren't something we should worry too much, and this can all be bridged with a mirror bot that would post from slack to mattermost or whichever platform we pick in the future.

**Comment by GBKS** [comment]
Created a PR with the changes. You can [preview it here](https://deploy-preview-328--sad-borg-390916.netlify.app). Let me know if there's anything else you'd adjust.
