### ISSUE TITLE
Make ordered page navigation lists more consistent

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#325]
Ordered lists are currently something that are used quite sparingly and inconsistently in the guide. 

For example, in the Getting Started chapter the _Common user flows_ page users an ordered list to help navigate that pages content whilst no other page in this chapter (or the whole guide for the matter) uses an ordered list in this manner. Is this a style we want to apply to the other sections in this chapter / guide? If not, should we remove the list in the common user flows page? If so, should we apply this nav styled ordered list to all relevant pages?

**Note**
Formatting and the principles pages have a navigation list but it is un-ordered.

**Comment by GBKS** [comment]
For some context, I added the list after writing the page content and finding it hard to navigate. Most pages tell a clear story from top to bottom - a linear read. This page hits on many individual actions a user might take through their Bitcoin experience. So coming to this page as a reader, it's helpful to get a quick overview of what's on the page, and then navigate to just the part I am interested in. If you look at the [visual review Figma file](https://www.figma.com/file/5amvNM95DkHFpOnVzzoAyK/Guide-visual-review-210504?node-id=0%3A1), it's also the longest page in "Getting started".

The only other page where we have taken this approach is the Glossary. It has a table of contents at the top as it is similarly a laundry list of various bits of information. We could take the styling from the glossary and apply it to the "Common user flows" page.

Generally, I'd only use this if it's really needed and appropriate for the page content, as a response to interacting with the page (not as an imposed standard).

**Comment by Bosch-0** [comment]
Just to add, this is also used on the personal finance page. This page is quite small but still has this styling. We should either remove it or apply this styling to all the pages. 

What about the formatting and principles unordered lists? Shouldn't they be ordered lists also. 

It is kinda nice to have a quick overview of what the page covers though. Some pages are almost as long as the common user flows page and could use with an ordered list. For consistency it looks cleaner to either have a ordered list or not on each page.

**Comment by GBKS** [comment]
Created a PR for this and updated the pages mentioned here.
