### ISSUE TITLE
Split "Getting started" in two sections?

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#330]
Per @danielnordh's review in #202. Splits info specific to design from the "Bitcoin for beginners" content.

> Getting started with Bitcoin
> - Why Bitcoin is unique
> - Visual language
> - Technology primer
> - Software overview
> - Hardware overview
> 
> Designing Bitcoin products
> 
> - Why design for Bitcoin
> - Open design
> - User research
> - Usage lifecycle
> - Personal finance
> - Common flows

Would also create a space for more purely design-related resources (like how to collaborate on design in open-source, see #35).

This is a question to discuss. Cool if we decide against it.

**Comment by johnsBeharry** [comment]
##### Getting started with Bitcoin
- Principals 
- Why Bitcoin is unique
- Visual language
- Units and symbols 
- Technology primer
- Software overview
- Hardware overview
- Interoperability

I support this split, as well as merging foundations with "getting started with bitcoin".

**Comment by pavlenex** [comment]
Concept ACK.

**Comment by Bosch-0** [comment]
Concept ACK! It is quite a big chapter currently.

Principles / interoperability would make more sense in _designing Bitcoin products_ rather than getting started with Bitcoin.

**Comment by GBKS** [comment]
Created a PR for this (#333). Please [preview](https://deploy-preview-333--sad-borg-390916.netlify.app/guide/designing-products/introduction/) and review thoroughly.

Moving other pages can be handled in separate PRs.
