### ISSUE TITLE
Add some styling / spacing to unordered lists

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#335]
Currently unordered lists in their standard markdown styling look quite compact and are not very visually enticing. 

It would help with readability to increase the spacing between list items as well as add at some styling to the dots to make it more visually enticing and 'feel' more designed. It would also help break up those very text heavy pages that have a lot of lists. Here is a suggestion, but it would be good to explore some other concepts as well. 

![Frame 130](https://user-images.githubusercontent.com/55287964/119075079-c57ead80-ba22-11eb-97dc-211a87bb43ea.png)

**Comment by IamSanjana** [comment]
![list-styling](https://user-images.githubusercontent.com/85779625/154814576-f01f08f7-d27d-4da1-ba8c-c284ecee840f.png)

> List styling idea

**Comment by Bosch-0** [comment]
Not sure if the grey bubble around the text is required, seems like unecessary visual clutter. The color used for the people is also a bit off brand, a orange would be more suitable.

**Comment by IamSanjana** [comment]
Sure, I understand

**Comment by GBKS** [comment]
Can we close this one? It's a really minor thing and been around for over a year. Personally, I think the lists are fine and we don't need to do anything. Better to avoid pages with lots of lists in the first place.

**Comment by Bosch-0** [comment]
Yeah I'm fine with closing it. I just avoid using them now, the content looks too compacted.
