### ISSUE TITLE
Add header image to the Designing Bitcoin products page

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#336]
As requested by @danielnordh 

This issue is for creating a visual header image for the upcoming Designing Bitcoin products page.

This page will appear in the guide after #333 is merged. In the meantime here's a [preview of that page.](https://deploy-preview-333--sad-borg-390916.netlify.app/guide/designing-products/introduction/)

**Comment by mau211** [comment]
I would like to take this up

**Comment by GBKS** [comment]
@mau211 awesome. The first step is the design part. If you'd then like some help with implementing it, we're here to help.

**Comment by pavlenex** [comment]
Awesome @mau211 it's all yours, looking forward to what you come up with, feel free to share it here or on our Slack 🚀

**Comment by mau211** [comment]
Do you have sizing specs for the header and/or design guidelines?
Also what is the timeline for delivery for this?

**Comment by pavlenex** [comment]
@mau211 yeah [check this out](https://bitcoin.design/guide/contribute/illustration-guidelines/#export-images-at-the-right-sizes). There are no visual guidelines, we encourage creativity and diversity and artistic freedom when it comes to that. So feel free to get your creative juices flowing.

If you need an example of a pull request you can do check it in #344. As for the time frame, no strict deadlines on this one, though if you can get it in in the next 5 days that would be awesome, so we can include it in the v1 of the guide which we intend to launch early next month.

**Comment by GBKS** [comment]
I keep all the headers I've created in [this Figma file](https://www.figma.com/file/qzvCvqhSRx3Jq8aywaSjlr/Bitcoin-Design-Guide-Illustrations-CO?node-id=236%3A454), maybe it's of interest. Here's [another Figma file](https://www.figma.com/file/5amvNM95DkHFpOnVzzoAyK/Guide-visual-review-210504?node-id=0%3A1) with screenshots of all pages, also helps to get an idea of the variety of illustrations that have been done already.

**Comment by sbddesign** [comment]
@mau211 Just checking in. We are hoping to have in image for this page for our Guide launch this week. I can create a header for this page, but I wanted to see if you had something in-progress since you expressed interest in taking on this issue. 🙂

**Comment by mau211** [comment]
> @mau211 Just checking in. We are hoping to have in image for this page for our Guide launch this week. I can create a header for this page, but I wanted to see if you had something in-progress since you expressed interest in taking on this issue. 🙂

@sbddesign yes I can post my progress here later today :) in the evening.

**Comment by mau211** [comment]
![designingBitcoinProducts_header_WEB](https://user-images.githubusercontent.com/24661071/120407147-8a318800-c31a-11eb-8c58-afafff004a4d.png)

**Comment by mau211** [comment]
I have a 1600 px for desktop and 400 px for mobile.

**Comment by pavlenex** [comment]
@mau211 The next step is to do a pull request for it 😄 
I already mentioned how to do it [here](https://github.com/BitcoinDesign/Guide/issues/336#issuecomment-848036403), but if you need any help join our slack and ping me or @ConorOkus to help you with implementation.

**Comment by mau211** [comment]
Excited 🥳 😊

**Comment by pavlenex** [comment]
Closed in #369 thanks to @mau211 🎉

**Comment by GBKS** [comment]
@mau211 thanks for the contribution. Quick heads up that the images are not the right sizes, the alt text should be updated to describe the image content, and `layout = "full-width"` is added 4 times on the include (once is enough). I can create a PR tomorrow to fix things up.

**Comment by mau211** [comment]
> @mau211 thanks for the contribution. Quick heads up that the images are not the right sizes, the alt text should be updated to describe the image content, and `layout = "full-width"` is added 4 times on the include (once is enough). I can create a PR tomorrow to fix things up.

@GBKS , the image widths were followed via the guidelines. Curious, was it the height or resolution that was not accurate?
Sorry, for the late reply I was on vacation.

**Comment by GBKS** [comment]
@mau211 no worries. If you look at the 2x desktop version of the image ([source is here](https://github.com/mau211/Guide/blob/2de5964c93547b96315dc4c4832c560993b209fd/assets/images/guide/designing-products/designing-bitcoin-products/designing-bitcoin-products-web%402x.png)), the image is 6667x2501, while it should have been 3200x1201 (the width is really the main restriction and image height can be flexible based on the design). Could you let me know which guidelines you followed? Maybe there's incorrect information somewhere.

**Comment by mau211** [comment]
> @mau211 no worries. If you look at the 2x desktop version of the image ([source is here](https://github.com/mau211/Guide/blob/2de5964c93547b96315dc4c4832c560993b209fd/assets/images/guide/designing-products/designing-bitcoin-products/designing-bitcoin-products-web%402x.png)), the image is 6667x2501, while it should have been 3200x1201 (the width is really the main restriction and image height can be flexible based on the design). Could you let me know which guidelines you followed? Maybe there's incorrect information somewhere.

@GBKS https://bitcoin.design/guide/contribute/illustration-guidelines/ There should be both with and height details as well as resolution. Let me know if you need assistance updating this info. Also I could resize the images I sent previously once I get all the dimensions as its really an illustration before exporting it to a png.

**Comment by GBKS** [comment]
Thank you for double-checking. I already submitted a PR to address the size changes. The [PR is here](https://github.com/BitcoinDesign/Guide/pull/380), and the changes are live on the site. Hope that's OK, please take a look and let me know if there are any changes you'd like to make.

Yes, it maybe have been the DPI setting. DPI is a print-only thing, I am not sure why Adobe products still make it a default thing for exports in digital use. I've been creating my illustrations in Figma primarily, as I find Illustrator et al overly complex in many ways (like the export settings with 500 options).
