### ISSUE TITLE
Add specs for social preview image to formatting guidelines page

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#338]
I propose that we update the [Illustration Guidelines](https://bitcoin.design/guide/contribute/illustration-guidelines/) page to include the sizing details for social preview images.

The social preview image for a page should be 1200 x 630 pixels and should be a separate image according to @GBKS in [this comment](https://github.com/BitcoinDesign/Guide/pull/296#issuecomment-834476224).

**Comment by GBKS** [comment]
Added something to the illustration guidelines page in PR #345. You can preview it [here](https://deploy-preview-345--sad-borg-390916.netlify.app/guide/contribute/illustration-guidelines/#link-preview-images).
