### ISSUE TITLE
Visual concept proposal for the onboarding section page headers

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#358]
I came up with this concept for the headers in the Onboarding section. Idea is that this section, unlike other sections, describes a fairly linear process (or user experience). So each icon in the image represents one page. The section landing page would have all icons highlighted (top image), and each sub-page only the icon it stands for (bottom image). So when you land on a page, you understand where you are in the flow. This was meant as a concept, I didn't worry about the visual style (colors, line patterns) much.

@ConorOkus likes the concept. However, I'll be camping the next days and won't have time to work on it. So if anyone thinks we should use this concept and wants to help wrap it up, please go ahead, that would be super cool. Here's the 
[Figma file](https://www.figma.com/file/qzvCvqhSRx3Jq8aywaSjlr/Bitcoin-Design-Guide-Illustrations-CO?node-id=1425%3A8268). Otherwise, if we don't have headers for the section by late next week, I'll try to wrap this up.

![Onboarding section header image sequence idea 210525](https://user-images.githubusercontent.com/695901/119951659-78f41e80-bf9c-11eb-82c0-1eaf51968514.png)

**Comment by Bosch-0** [comment]
Really like this concept, has a more interactive element to it!

**Comment by paulosacramento** [comment]
![Screen Shot 2021-05-28 at 11 23 54](https://user-images.githubusercontent.com/76049494/119962351-3edc4a00-bfa7-11eb-8e7a-dba2fe4caaea.jpg)

I think that's the idea, right?

**Comment by paulosacramento** [comment]
Cool. Let's see if I can make it a pull request.

**Comment by pavlenex** [comment]
#366
