### ISSUE TITLE
Break glossary.md into sub glossaries

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#37]
Might be worth breaking the glossary.md file up into sub glossaries to prevent this page becoming too unruly. 

Some examples of sub glossaries:

Lightning 
Wallets
Nodes
BIPS

**Comment by GBKS** [comment]
What about adding a bit of interaction, so each definition is collapsed by default and you click to expand it and read the details? That way we start with just a list of terms and people can dig into what interests them.

The site search will also index the glossary, which should make it a lot more useful.

**Comment by GBKS** [comment]
See https://github.com/BitcoinDesign/Guide/issues/43 for a design proposal on styling and interaction.

Tricky thing with sub-glossaries is that if somebody is looking for a term, they already need to know which sub-glossary it belongs to. Search helps with that (and also having things on a single page).

**Comment by GBKS** [comment]
Closing this one, as we are going with an interaction model via [#43](https://github.com/BitcoinDesign/Guide/issues/43).
