### ISSUE TITLE
Create a button for the > next chapter segment 

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#372]
Chethan made a great point on Slack:

> Would be great to have a much more clear indicator for the next chapter/segment. Right now the text link does not feel like it gives great clarity on how to navigate to the next page.

![image (1)](https://user-images.githubusercontent.com/36959754/120689296-4e2a2e80-c4a4-11eb-91cb-c18ecae6b424.png)

**Comment by GBKS** [comment]
Let's tackle this in design first and come up with a button system for the site that we can use as needed. I believe we also talked at some point about adding buttons to other pages for bigger call-to-actions..

**Comment by Bosch-0** [comment]
We could also have the primary button on the right and a secondary button on the left returning to the previous section. As this guide is mostly reference material I imagine some may go back and forth.

**Comment by Bosch-0** [comment]
We should also include this button at the bottom of chapter landing pages that re-directs to the next chapter skipping over the internal content. 

So a button at the bottom of Designing Bitcoin Products would re-direct to Onboarding.

**Comment by GBKS** [comment]
How about something like this? It's a bit more subtle and Includes a back link to the previous page. With the back link being just an icon, it also work on mobile. The black outline link works well with the footer style.

![Bitcoin design site next previous 210628](https://user-images.githubusercontent.com/695901/123639596-a55fbc80-d820-11eb-808d-6eeb84727a91.jpg)

**Comment by pavlenex** [comment]
Concept ACK @GBKS I love it.

**Comment by Bosch-0** [comment]
Concept ACK from me! Maybe try having the next on the right hand side rather than both on the left.

**Comment by GBKS** [comment]
Here's what that would look like. I prefer left-aligned.

![Bitcoin design site next previous 210701](https://user-images.githubusercontent.com/695901/124135311-fa4f3d00-da83-11eb-8eb8-72e3c60969ac.jpg)
