### ISSUE TITLE
Review how we use footnotes

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#385]
I don't think we use footnotes well. For example, a footnote in the [Coin Selection page](https://bitcoin.design/guide/payments/send/coin-selection/#fn:1) consists of a URL, and there's one in the [glossary](https://bitcoin.design/guide/glossary/#fn:1) that's just a link.

Links don't need to be footnotes, they can just be in the content. Footnotes should be for additional information that would interrupt the content flow, but is still important to have on the page. If it's about attributing a source, then the footnote should not just be a URL or link, but also provide a summary.

My recommendation would be to review the footnotes we have and write a better usage guide for the [Formatting](https://bitcoin.design/guide/contribute/formatting/#footnotes) page.

**Comment by Bosch-0** [comment]
Just an idea but we could pick an academic citation style such as APA (used in engineering disciplines).

https://apastyle.apa.org
