### ISSUE TITLE
Add short summaries to the User Research Resources page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#401]
The [User Research Resources page](https://bitcoin.design/guide/designing-products/user-research/resources) lists various research papers, surveys, blog-posts, and other write-ups. It would be incredibly helpful to add a short summary for each reference, so readers can more easily identify what interests them.

A second part to this issue could be to identify content that is relevant to other parts of the guide (for linking, block quotes or otherwise), or could be shared and discussed in the community.

**Comment by Bosch-0** [comment]
Could just copy and paste the abstracts (for research papers anyways). Contains most the useful insights.
