### ISSUE TITLE
Ensure that editor's notes for all pages include links to the design source files

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#408]
- Suggested by: @danielnordh
- Timeframe: short-term

**Comment by danielnordh** [comment]
Many/most pages currently missing this.
Here's a quick check for which chapters have it:

- [ ] Getting started
- [ ] Designing Bitcoin products
- [ ] Onboarding
- [ ] Private key management - PR #424 
- [ ] Payments (some do, some don't)
- [ ] Case studies
- [ ] Contribute to the guide
- [ ] Glossary (some do, some don't)
