### ISSUE TITLE
Add 'BIPS' section to 'Technology primer' page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#416]
We should include a section on this page explaining what a BIP is. here's why:

Understanding what a BIP is and what BIPs exist is extremely important for designers and we do not discuss it often in the guide. Designers building Bitcoin products may may way to support BIPs that aren't widely supported but suit their product needs. An example is Samurai wallets support of BIP47 (called PayNyms by them). By just looking at the majority of Bitcoin wallets a designer may think this concept does not exist. Educating them that BIPs exist and what they are can remediate this and help designers / product builders craft better products. 

Understanding BIPs (and also BOLTs but we'll keep that for another discussion) will also help us 'think ahead' when offering design recommendations.  

Somewhere later in the guide we should also suggest to designers that they should state what BIPs their product supports on their website, I think this is a good practice that more apps should do.

We could link them to this resource: https://bips.xyz/ or the official GH BIPs repository.

**Comment by GBKS** [comment]
We already have an issue for adding BIP info in #291. How about continuing the discussion there and closing this one?

**Comment by Bosch-0** [comment]
This would just be a short paragraph in the primer section on BIPs not relating to the own page but yeah can move discussion there.
