### ISSUE TITLE
Change image on 'onboarding/Backing up recovery phrase.'

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#417]
Few issues with the image used on this page.

- Downloading your recovery phrase as a PDF is a very insecure method to backup your recovery phrase (except maybe if its encrypted). 
- Printing your recovery phrase is also insecure.
- Backing up to iCloud should be encrypted (say with a user entered PIN setup in frames prior to showing this seed). 

This image should just show a frame with a recovery phrase without these other options just to illustrate what a recovery phrase is and how it would be show on a mobile device. 

Image in question below:

![image](https://user-images.githubusercontent.com/55287964/124092550-90399680-da89-11eb-81a8-24a3b0aaceed.png)

**Comment by Bosch-0** [comment]
Suggested changes, before and after:

![image](https://user-images.githubusercontent.com/55287964/128455715-665bf0fb-c470-4748-bf27-b461fbdc6dd3.png)

**Comment by GBKS** [comment]
Looks good. You can shorten the screen to 812px for iPhone 11 proportions to match the other screens. I had only made it taller in the original design so all buttons fit.

What about keeping one button to "Print template", an idea we've discussed before? That way people don't write the seed on a random scrap of paper they might lose.

**Comment by Bosch-0** [comment]
> Looks good. You can shorten the screen to 812px for iPhone 11 proportions to match the other screens. I had only made it taller in the original design so all buttons fit.

Will do!

> What about keeping one button to "Print template", an idea we've discussed before? That way people don't write the seed on a random scrap of paper they might lose.

Great idea :) 

![image](https://user-images.githubusercontent.com/55287964/128464051-a1c3c48b-7c58-4402-8fca-4aa4bf2194cd.png)

**Comment by GBKS** [comment]
How about creating a PR for this and getting it reviews & merged?

**Comment by Bosch-0** [comment]
On to it :)

**Comment by Bosch-0** [comment]
PR for this issue https://github.com/BitcoinDesign/Guide/pull/457
