### ISSUE TITLE
Add 'It is extensible' to why "Why Bitcoin is unique" page.

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#440]
As part of the larger efforts to integrate LN into the design guide, adding a section in 'Why Bitcoin is unique' titled 'It is extensible' is a good step to take.

This section would detail how Bitcoin can be 'extended' beyond it's base layer to enable unique use cases, tools and much more. The primary example being the Lightning Network. This could be added in a PR alongside https://github.com/BitcoinDesign/Guide/issues/433

**Comment by pavlenex** [comment]
The "extensibility" and "layering" will also be added in #415 Johns and I are working on.

**Comment by GBKS** [comment]
Is this part of the "It is open-source" paragraph at the bottom, meaning that people are invited to contribute and improve and build?

**Comment by Bosch-0** [comment]
> Is this part of the "It is open-source" paragraph at the bottom, meaning that people are invited to contribute and improve and build?

I see it being a little different, you can have an open-source project that isn't extensible in the way in which Bitcoin is.

**Comment by pavlenex** [comment]
Closing due to #463
