### ISSUE TITLE
Header Theme Proposal | Bridging Bitcoin Design

### ISSUE THREAD

**Issue by AlexaAker** [BitcoinDesign/Guide#45]
<h1>Bridging Bitcoin</h1>
<p>Hello everyone.</p>
<p>I'd like to contribute this header design for the <a href="https://bitcoin.design" alt="Bitcoin Design Website" target="new">Bitcoin Design </a> website.</p>
<p>Thank you for your time.</p>
<img src="https://user-images.githubusercontent.com/66574310/98195650-e13bbf80-1ee7-11eb-8f7d-c68797c85550.jpg">
<h2>File On Figma:</h2>
<a href="https://www.figma.com/file/SE2DcuEiIqhc9DJyBZ8grL/Bridging-Bitcoin?node-id=1%3A129" alt="Bridging Bitcoin Figma File" title="On Figma" target="new">Bridging Bitcoin &#10530;</a>
<h2>Contribute Your Own:</h2>
<p><a href="https://bitcoin.design/submit-header-design" alt="How To Guide" target="new">How To Guide &#10530;</p>
<p><a href="https://www.figma.com/community/file/891254324897262700" alt="Template On Figma" title="On Figma" target="new">Template &#10530;</a></p>
<p>Guide & template by @GBKS</p>

**Comment by BitcoinErrorLog** [comment]
ACK, good one!

**Comment by AlexaAker** [comment]
> ACK, good one!

Thank you. 🙏

**Comment by GBKS** [comment]
110% ACK.

**Comment by ConorOkus** [comment]
ACK 🔥 🔥 🔥

**Comment by johnsBeharry** [comment]
ACK awesome work @AlexaAker!

**Comment by Bosch-0** [comment]
Love it, ACK

**Comment by GBKS** [comment]
Just created a PR for this with the code and images to add the theme to the site.

@AlexaAker the images in the Figma file are a bit pixelated. Can you maybe add vector versions that I can export at a higher resolution? If vectors are not available, then static images are good, too. The desktop image should be be at least 1600x1600 and the mobile image 800x800. Thanks.

**Comment by AlexaAker** [comment]
Thank you 🙏 @GBKS, @ConorOkus, @johnsBeharry, @Bosch-0.
