### ISSUE TITLE
Add ⚡️ content to `Getting Started` > `Why Bitcoin is unique` 

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#463]
**Describe your content request**

Duplicate and related to #440

It's been discussed on a Jam Session that we open up the issues for the pages in the `Getting Started` section that should be revised and require Lightning Network content.

**Link to the page**

https://bitcoin.design/guide/getting-started/why-bitcoin-is-unique/

_Please add a link to the page you're requesting content change for (if applicable)_

** Discussing what needs to be added to the page** 

Please, review the current state of the page and feel free to discuss what kind of LN content should be added (if any).

**Content guidelines**
If you're a contributor looking to tackle the issue, you can [preview our content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/).

**Comment by pavlenex** [comment]
One thing @Bosch-0 pointed out is `Extensibility` as a property. This will also be touched in the #415 but is probably worth mentioning here a bit. Maybe not introduce LN on this page, but talk about multiple layers, etc.

**Comment by Bosch-0** [comment]
> One thing @Bosch-0 pointed out is Extensibility as a property.

If it is mentioned here it would be in a more much general sense explaining that Bitcoin CAN be extended with things like Lightning, Liquid etc. Could link to the tech primer entry for a more detailed dive, specific dive on LN.

**Comment by pavlenex** [comment]
Slightly related #433
