### ISSUE TITLE
Add ⚡️ content to `Getting Started` > `Software overview`

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#465]
**Describe your content request**

It's been discussed on a Jam Session `Call 13` that we open up the issues for the pages in the `Getting Started` section that should be revised and require Lightning Network content. Google Doc [here](https://docs.google.com/document/d/1gQ1Bu0nD9AJL0QtmHmNqts_uCFYPwRgPnNSPYb7uZtg/edit?usp=sharing)

**Link to the page**

https://bitcoin.design/guide/getting-started/software/

_Please add a link to the page you're requesting content change for (if applicable)_

** Discussing what needs to be added to the page** 

Please, review the current state of the page and feel free to discuss what kind of LN content should be added (if any).

**Content guidelines**
If you're a contributor looking to tackle the issue, you can [preview our content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/).

**Comment by pavlenex** [comment]
@sbddesign mentioned we should:
- add Lightning explorers
- Talk about lightning in all relevant places (wallets etc)

**Comment by Bosch-0** [comment]
I opened a discussion about this a couple weeks ago also for some other suggestions: https://github.com/BitcoinDesign/Guide/discussions/444

**Comment by danielnordh** [comment]
Created a doc with the existing content and will start to comment and suggest changes:
https://docs.google.com/document/d/1p534PoTgBfqJvQGX4K2gpOwt8iDoINGitB9Td1Io-3c/edit?usp=sharing

**Comment by danielnordh** [comment]
Updates now in this PR - #473

**Comment by danielnordh** [comment]
PR for the changes available here #473
