### ISSUE TITLE
Add ⚡️ content to `Getting Started` > `Hardware overview`

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#466]
**Describe your content request**

It's been discussed on a Jam Session `Call 13` that we open up the issues for the pages in the `Getting Started` section that should be revised and require Lightning Network content. Google Doc [here](https://docs.google.com/document/d/1gQ1Bu0nD9AJL0QtmHmNqts_uCFYPwRgPnNSPYb7uZtg/edit?usp=sharing)

**Link to the page**

https://bitcoin.design/guide/getting-started/hardware/

_Please add a link to the page you're requesting content change for (if applicable)_

** Discussing what needs to be added to the page** 

Please, review the current state of the page and feel free to discuss what kind of LN content should be added (if any).

**Content guidelines**
If you're a contributor looking to tackle the issue, you can [preview our content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/).

**Comment by pavlenex** [comment]
It's been mentioned on a call that we can add LN mentions in the: 

- Nodes cc @Bosch-0 this may be something you'll like
- Hardware wallets`?`


Also related to #460

**Comment by Bosch-0** [comment]
> Nodes cc @Bosch-0 this may be something you'll like

Yep happy to take on this one on!

**Comment by Bosch-0** [comment]
Just dropping the active Google doc for the changes for this issue, will be opening a PR for this most likely tomorrow once current feedback is addressed: https://docs.google.com/document/d/1NlON15hbDdu1gyK0eq8HQt4ARF-vFnDORwa2AhFl-SQ/edit#
