### ISSUE TITLE
Add ⚡️ content to `Designing Bitcoin Products` > `Common User flows`

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#470]
It's been discussed on a Jam Session `Call 13` that we open up the issues for the pages in the `Design Bitcoin Products` section that should be revised and require Lightning Network content. Google Doc [here](https://docs.google.com/document/d/1gQ1Bu0nD9AJL0QtmHmNqts_uCFYPwRgPnNSPYb7uZtg/edit?usp=sharing)

The `Common User flows` is the meat 🍖 of this entire chapter and would require major revision and edits to cater to the Lightning Network content.

https://bitcoin.design/guide/designing-products/common-user-flows/

We should discuss how to tackle this since it'll be a big undertaking and lots of refactoring will be needed.

Tasks

- [x] Analyse and identify which areas in the page need to be updated
- [x] Propose a structure, and details of what needs to be updated with what
- [x] Start writing [collaborative doc](https://docs.google.com/document/d/1Fu-EPdUu9mK3Rsyk_yurWaxUdzGVV1gVD859XMqnQgY/edit?usp=sharing
- [ ] Design and layout)
- [ ] Implement design & Open PR
- [ ] Review process

**Comment by danielnordh** [comment]
**Sections that should include Lightning content or be updated**
- Creating a new wallet
- Importing an existing wallet
- Sending bitcoin
- Requesting bitcoin
- Receiving bitcoin
- Managing transactions (mentions that transactions can be traced)
- Switch wallets
- Wallet maintenance
  - Sweeping dust
  - Mixing coins

**Comment by danielnordh** [comment]
Started suggesting changes in this doc: https://docs.google.com/document/d/1Fu-EPdUu9mK3Rsyk_yurWaxUdzGVV1gVD859XMqnQgY/edit?usp=sharing

Since there are so many sections that need updating, I'm thinking of splitting this page into several PR's starting with creating and importing a wallet.

**Comment by pavlenex** [comment]
@danielnordh Def makes sense to split to allow faster progress, good idea.
