### ISSUE TITLE
Add a ⚡️ WIP disclaimer on the landing page or on the affected pages 

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#472]
**Describe your content request**

Since we're adding LN content incrementally to pages and sections the readers may find themselves confused LN isn't mentioned on some pages. 

@GBKS posted this on Slack

![Screenshot 2021-09-08 at 19 06 39](https://user-images.githubusercontent.com/36959754/132553618-87346399-f6c0-4df6-a80e-625553288b12.png)

**Link to the page**
_Please add a link to the page you're requesting content change for (if applicable)_

https://docs.google.com/document/d/1WSogCAEHiaL6g8VxDsFy0vVf_BzlOHLvuHdRFKhau5w/edit

**Content guidelines**
If you're a contributor looking to tackle the issue, you can [preview our content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/).

**Comment by danielnordh** [comment]
If we are OK with using the 'Tip' styling I can create a PR for adding a general disclaimer on the main Guide page:

![image](https://user-images.githubusercontent.com/3393669/133247618-1c8ed386-7533-4789-ae99-b5f82a62041c.png)

**Comment by pavlenex** [comment]
@danielnordh  ACK for making it visually more obvious, so the `tip` styling works good for me, I'd also recommend that you take a glance at what @GBKS has been proposing in a google doc, maybe we can find a middle ground there or implement both in a PR. https://docs.google.com/document/d/1WSogCAEHiaL6g8VxDsFy0vVf_BzlOHLvuHdRFKhau5w/edit

**Comment by GBKS** [comment]
I like it! I think this disclaimer can be separate from the other preamble copy.

I am still debating whether the preamble needs a dedicated page, or whether it's enough to state on the intro page of each section as to what assumptions are being made. For example, the focus on a mobile, Lightning-first, self-custodial wallet is primarily relevant to the Onboarding and Payments sections. Is it better to group this in one place, or let each section speak for itself?

**Comment by pavlenex** [comment]
Done in #479
