### ISSUE TITLE
Improve recommendations and visuals in the `Onboarding` > Protecting a wallet > `hiding-sensitive-information`

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#474]
**Describe your content request**

A community member on Slack, Justin, had a question about hiding balances. 

Below is a conversation from Slack.

![Screenshot 2021-09-15 at 18 51 41](https://user-images.githubusercontent.com/36959754/133476051-ceaf088f-5a43-4638-9473-484cfb9c8b28.png)

**Link to the page**
_Please add a link to the page you're requesting content change for (if applicable)_

https://bitcoin.design/guide/onboarding/protecting-a-wallet/#hiding-sensitive-information

**Suggestions**
_If you have a concrete suggestion on how to change/add the content, write it up here_

1. Improve the visuals to resemble wallet kit UI
2. Be a bit more explicit on what we recommend for hiding a balance on that page (it seems that's an `eye icon`)

**Additional context**

_Add any other context about the request here._

**Content guidelines**
If you're a contributor looking to tackle the issue, you can [preview our content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/).

**Comment by Bosch-0** [comment]
My 2 sats

I'm a fan of the 'hold balance' to hide and tap to switch units. If you are constantly switching units and have to skip past the hidden view as it is part of the 'tap' action its extra work the user needs to take. Holding is also more of a involved process, say if you were showing someone the app it would be much harder for them to tap and hold then just tap and see your balance. You could include a nudge the first time the user opens the app directing them to hold the balance to discover this feature.

**Comment by GBKS** [comment]
I think this one should be addressed via the larger page overhaul in #537. Let me know if you disagree, otherwise we can close this issue.
