### ISSUE TITLE
Add ⚡️ content to `Designing Bitcoin Products` > `Principles`

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#481]
It would be unfortunate if we'd discovered that LN sacrifices certain principle. 

Some [notes](https://docs.google.com/document/d/1JwNSJj_2_IxUcx81cbl7sa6XdPZEGduRiprTm3Y2E4o/edit?usp=sharing) from [Jam Session #14](https://github.com/BitcoinDesign/Meta/issues/120).

- Change do's and don't
- Address re-use
- Automation, abstraction, design product in a way where users do not have to think about layers? Design products by abstracting on and off chain

**Comment by sbddesign** [comment]
Will do

**Comment by pavlenex** [comment]
#494
