### ISSUE TITLE
Explore ways to encourage typeface designers to include bitcoin symbol U+20BF

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Guide#5]
There are also a large amount of typefaces missing the Bitcoin symbol on fonts.google.com as these are very widely used on the web.

- How many? Could be a good starting point to for analysis.

> _“How to include” is not the hard part, any pro type designer can do this easily. Motivation to include this glyph in the font vs many other currency symbols, other punctuation, other language accents, etc is the difference. If we are not sure it will be used it doesn't get a high priority, but a bounty would change that_

From a discussions in #BitcoinDesign slack
- https://bitcoindesign.slack.com/archives/C015856BDME/p1593063808128000?thread_ts=1591373945.177200&cid=C015856BDME

Example
- https://github.com/rsms/inter/issues/284

**Comment by GBKS** [comment]
I like your idea of analysis first. We could also talk to foundries and type designers to ask about their typical process of deciding which glyphs to include and which ones not to include. I am sure bitcoin is not the only symbol where this question is asked.

I just wrote a quick script to check bitcoin symbol support on Google Fonts, and only 22 of 998 fonts have it. Here's the list:

`[
  "PT Sans",
  "PT Serif",
  "PT Sans Narrow",
  "Source Serif Pro",
  "IBM Plex Sans",
  "IBM Plex Serif",
  "Bebas Neue",
  "PT Sans Caption",
  "Encode Sans",
  "IBM Plex Mono",
  "Markazi Text",
  "PT Mono",
  "PT Serif Caption",
  "Encode Sans Condensed",
  "IBM Plex Sans Condensed",
  "Bellota Text",
  "Bellota",
  "Manrope",
  "Encode Sans Semi Condensed",
  "Encode Sans Expanded",
  "Encode Sans Semi Expanded",
  "Scope One"
]`

A long way to go...

**Comment by Bosch-0** [comment]
This could be a good 'soft' project that BDC members could help out with - maybe add this to collaborations on the meta repo?

**Comment by GBKS** [comment]
@Bosch-0 I'm thinking that before adding anything to collaborations, we should make sure we have somebody who is dedicated to driving the project (meaning that there's a plan and work will get done and it doesn't stay in the idea stage). I'd keep it as an issue or discussion beforehand. We haven't really discussed that distinction, but I think that approach matches our [project life cycle](https://github.com/BitcoinDesign/Meta/blob/master/Projects.md). What's your take?

**Comment by Bosch-0** [comment]
Yeah on second thought keeping it up as an issue until someone picks up the project is probably a more suitable way to go about things.

**Comment by pavlenex** [comment]
Is this issue really related to the BDG? Isn't this more of an initiative?

With our capacity atm, and lack of interest, I propose we move on and close this issue for now, so we're able to focus on our other goals. We can always re-opened if anyone in the community is interested into pushing it forward.

**Comment by Bosch-0** [comment]
I agree with Pav, maybe someone could open a repo that tracks typefaces that have a Bitcoin symbol / ones who are working on integrating it / have the option to open issue for someone to design a Bitcoin symbol for a specific typeface. This could be added as a BDC collaboration project if so.
