### ISSUE TITLE
Sticky header nav obscures the heading when clicking deep links in wallet glossary

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#500]
When clicking on a deep link to a term in the ["wallet glossary"](https://bitcoin.design/guide/glossary/wallet/), the term's heading is obscured by the Guide's sticky header nav. I have replicated this behavior in macOS in Brave, Safari, and Firefox. [Try clicking this link to the "Bitcoin wallets" term](https://bitcoin.design/guide/glossary/wallet/#bitcoin-wallet) and see if the heading is obscured.

This problem does **not** occur on the main glossary page -- here is an [example link to the BIP term](https://bitcoin.design/guide/glossary/#bip---bitcoin-improvement-proposal).

This could confuse people. If you click a link to the term, it would be a lot clearer if you could see the heading.

<img width="1622" alt="Screen Shot 2021-10-03 at 2 09 00 PM" src="https://user-images.githubusercontent.com/2414177/135766344-b3790b3a-4930-4c94-9bd2-5b3b3d36eb47.png">

**Comment by GBKS** [comment]
Weird that this is happening again,  I thought we fixed this in #79 and #102. Will have to take another look.
