### ISSUE TITLE
Define audience for the guide

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#51]
A common understanding of the audience is helpful for writers to adopt appropriate language and weight off what to include and exclude.

This [Google doc](https://docs.google.com/document/d/1XCd8dxZIt6dXNtanXzPlizhgvuTD4Tn_Rk9j2AgcJUk/edit?usp=sharing) started by @johnsBeharry and I is a starting point we can iterate and then turn into a PR.

**Comment by pavlenex** [comment]
That google doc seems to have decent amount of information. If we decide to go with it, is there any particular section of the guide where this should be fitted, or is this more of a guideline for anyone wanting to contribute to the guide? Seems to me like later, but just want to be sure.

I think defining audience, language, tone and structure for chapters would help us have consistency.

**Comment by GBKS** [comment]
How about a new "Contribute" section, as I suggested [here](https://github.com/BitcoinDesign/Guide/discussions/92#discussioncomment-262513)?

**Comment by pavlenex** [comment]
@GBKS What's expected of this page, should we just copy over the content from the Google Doc and iron out later on? Any examples of good `target audience` pages, I can take inspiration from?

**Comment by pavlenex** [comment]
#263
