### ISSUE TITLE
Create glossary term for "block reward"

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Guide#511]
**Describe your content request**

Hello, I would like to request a new term added to the glossary for "Block Reward". 

**Link to the page**
- https://bitcoin.design/guide/glossary/
- file: `guide/glossary/index.md`

**Suggestions**
some points / keywords for reference of the flow of this content
- initial reward
- halving events
- inflation
- last bitcoin to be mined
- miner incentives
- any other useful details

**Content guidelines**
If you're a contributor looking to tackle the issue, you can [preview our content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/).

**Comment by pavlenex** [comment]
Done in #566
