### ISSUE TITLE
Add ⚡️ content to `Onboarding` > `Creating a new wallet`

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#515]
**Describe your content request**

Notes from [Jam Session 15](https://github.com/BitcoinDesign/Meta/issues/156)
- `First use` vs `creating a new wallet`? Should we rename it?
-  Worrying about backup vs worry when you receive funds

**Link to the page**
_Please add a link to the page you're requesting content change for (if applicable)_

https://bitcoin.design/guide/onboarding/creating-a-new-wallet/

**Why would you like to change the content?**
_If you're requesting a change to existing content, please describe concisely why you would like to change it?_

**Suggestions**
_If you have a concrete suggestion on how to change/add the content, write it up here_

**Additional context**

_Add any other context about the request here._

**Content guidelines**
If you're a contributor looking to tackle the issue, you can [preview our content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/).

**Comment by danielnordh** [comment]
Doc with suggested edits [here](https://docs.google.com/document/d/1tPB4c0tgkEJC66rs5haFrLWiumyrDfpy-jbsqNI0oao/edit?usp=sharing), for comments before a PR.
