### ISSUE TITLE
Add ⚡️ content to `Onboarding` > `Protecting a wallet`

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#517]
The task is to review for the page for changes so it covers on-chain and Lightning.

**Comment by pavlenex** [comment]
Some things that we may want to consider here:
- Node always beeing online?
- Watchtowers
Maybe these two fall into "protecting" a wallet, but perhaps it's a far-fetch. Couldn't think of anything else.

**Comment by Bosch-0** [comment]
An interesting feature Blixt has that I haven't seen other wallets implement is the option to delete the recovery phrase from blixt once it's been backed up. Might be worth adding here!
