### ISSUE TITLE
Glacier protocol - replace with a more user-friendly multi-sig solution

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#522]
![image](https://user-images.githubusercontent.com/2414177/137034745-831a7bb7-2137-404e-b3ab-d87c137b58be.png)

While I think [Glacier Protocol](https://glacierprotocol.org/) is a very interesting project, I also think it's an example of a highly-technical solution with UX to be desired. I think it seems out of place in the [Savings](https://bitcoin.design/guide/designing-products/personal-finance/#savings) section of the Personal Finance page.

The point of this section is to indicate that the greater the level of security, the greater the level of complexity.
Would it make more sense to include an example of a 3-of-5 multi-sig setup? For example, perhaps we portray it as consisting of 3 hardware wallets, 1 mobile wallet, and 1 custodied key. Something like this is easier for the user to setup and maintain, but still conveys the feeling of complexity.

**Comment by moneyball** [comment]
Totally agree Glacier protocol is extremely advanced and very involved.

**Comment by Bosch-0** [comment]
I'd go with 2 of 3 for savings as the guide is mostly focused on products for individuals. I think 3 of 5 is overkill for an individual are more suited for businesses, trusts etc. 

Personally I would have: 

**- Daily spending:** A standard LN wallet with a spending account
**- Monthly budget:** Standard LN wallet with a separate account with some kind of payment restrictions or just a separation from daily spending accounts funds. 
**- Emergency funds:** Single hardware wallet maybe with a passphrase for extra security
**- Savings:** 2 of 3 multisig wallet using a mobile app + 2 hardware wallets (or one hardware wallet and one desktop generated wallet as the redundant backup key.)

**Comment by sbddesign** [comment]
@Bosch-0 I guess it depends on your threat model and how we define "savings". If we define emergency funds as being 3-6 months salary, I like the idea of 6 months salary being secure from physical coercion; therefore, multi-sig. I think of "savings" as an amount of money ranging from making a down-payment on a house all the way to leaving behind for one's children; therefor, ultra multi-sig, and perhaps one of these keys sits with a custodian or lawyer.

**Comment by GBKS** [comment]
How about this? Picking up on Stephen's initial comment:

> Would it make more sense to include an example of a 3-of-5 multi-sig setup? For example, perhaps we portray it as consisting of 3 hardware wallets, 1 mobile wallet, and 1 custodied key.

![image](https://user-images.githubusercontent.com/695901/191905921-cc478652-782d-461f-914c-48982360b308.png)

**Comment by Bosch-0** [comment]
The savings outlined in that image is overkill for personal finance imo. That's getting more into the realm of treasury / business territory. I'd just make it one hardware signing device and stick with 2 of 3

**Comment by GBKS** [comment]
Alright, so how about this?

For emergency funds, recommend the app, hardware wallet + custodial key.

![image](https://user-images.githubusercontent.com/695901/206436587-d04782e9-092d-4c6c-817a-5e51cb22aca1.png)

And for savings, go for full self-custody via desktop, app, and hardware wallet.

![image](https://user-images.githubusercontent.com/695901/206436672-e2d9be84-b6aa-49fe-a635-47458fd561ff.png)

This allows us to show two different 2-of-3 multi-sig configurations and security models on the page.

**Comment by sbddesign** [comment]
@GBKS I like the Emergency Funds. Makes sense: you might need to access it more frequently, so you want to be able to get to it through your smartphone or have the custodied key be used in a pinch.

I find the Savings wallet strange. For something like "savings" which is a use-case beyond just emergency funds, seems like you'd want extra security. Why have 2/3 of the keys in the set running on hot devices connected to the internet? Seems reasonable to have 2 or maybe even 3 hardware wallets.

**Comment by sbddesign** [comment]
But I agree with the general principle that they're both 2-of-3 multisigs, just with different devices for each.

**Comment by mouxdesign** [comment]
Was just having a look at the bitcoin design guide to understand some of these concepts. Would the 1 custodied key be referring to a key that is stored automatically on the cloud? Similar to this image in the guide:
![PersonalKeys](https://user-images.githubusercontent.com/90313394/208440438-fe4bd695-10b9-42c9-a222-fb63c60bbe55.jpg)
[Link](https://bitcoin.design/guide/how-it-works/private-key-management/overview/)

It might then be an idea to include an image of a key in the cloud to match with the page currently in the bdg or refer to it as "automatic cloud backup".

Agree with Stephen for the Savings one; to keep much/some of the setup offline.
Perhaps a two different suggestions for savings might be an idea. One for the security conscious and one for the highly security conscious.

**Comment by GBKS** [comment]
@sbddesign I like that proposal based on the logic of having two offline devices. Here's an updated image.

![image](https://user-images.githubusercontent.com/695901/208468556-a3d6e71d-8021-4d58-9efe-0f06d5d3dd01.png)

I'll put together a PR for this tomorrow. Last call for changes. This seems like a tricky one to get consensus on, but let's get up an improvement on what we have right now, which is the total-overkill Glacier Protocol.

@mouxdesign the custodian key is held by a service provider. For example, a Muun wallet is a 2-of-2 setup. You hold one key, they hold the other one. Both keys are required to make transactions. When you make a transaction, they automatically sign it. Since they only hold one, they can't mess with your funds. But if someone steals your key, you can tell Muun and they will stop signing transactions, rendering the wallet inaccessible to the thief.

**Comment by GBKS** [comment]
OK, I created PR #959 for this. It's different than my last comment above. Main reason is that we have a savings wallet reference design, so we should just use that for the savings wallet example here. Then I turned the emergency wallet example into a 2-3 multi-key with a desktop app and 2 hardware wallets. Reviews appreciated. Thanks in advance for your sharp eyes and whip-smart comments.
