### ISSUE TITLE
Make personal finance comparisons consistent

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#528]
The Guide is somewhat inconsistent in how it makes comparisons to traditional personal finance.

The main issue that I have found is thus: the [Personal Finance](https://bitcoin.design/guide/designing-products/personal-finance/) page has a paragraph about "Monthly Budgeting" which depicts a single-sig desktop wallet with the key stored on a hardware wallet. In that paragraph, we link to the ["Savings Account" case study](https://bitcoin.design/guide/case-studies/savings-account/) which depicts a 2-of-3 multi-sig workflow. It seems strange that we are offering up a case study on multi-sig as an "an exploration of this user experience" for a single-sig wallet.

To complicate matters further, farther down the Personal Finance page we refer to the 2-of-3 wallet as being for "Emergency Funds", and we then use the term "Savings" to refer to the complicated 6 key Glacier protocol setup (related to #522).

I think we need to be consistent with our labels and metaphors, especially when cross-link between articles like this.

## Proposed Changes
1. Review the Guide for situations where these personal finance metaphors are in use
2. Make them consistent across pages

I first uncovered this during a discussion on PR #512. I am opening this as a separate issue as that PR is scoped to adding Lightning content to the page.

**Comment by pavlenex** [comment]
Related to #522 @GBKS is tackling it.
