### ISSUE TITLE
Create content for a "Contribute" page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#53]
The site nav currently has "Contribute" navigation item. The content for that page has not been really defined. However, we do have some good info in the readme of the Meta repo we could use, [right here](https://github.com/BitcoinDesign/Meta).

So I see three options:
1. Make that nav item link out to the Guide readme (meaning we won't have a nicely designed page, but people will have to read a Github page for that info)
1. Create new content for the "Contribute" page based on the Guide readme (so we will have a nice-looking page in the Guide repo, and the info in the Meta readme. There may be some content duplication)
1. Move the Meta readme content over to the Guide repo so we can have an nicely designed page there

I'm for option 2. It allows us to have a more approachable visitor-facing page, and then more functional Meta readme with additional info for experienced contributors.

**Comment by GBKS** [comment]
Here's what it would look like if we took the content from the Meta readme and put it on the site.

![Contribute page 201120](https://user-images.githubusercontent.com/695901/99789121-68ad4380-2b22-11eb-96cd-1bf7e43f6427.jpg)

**Comment by GBKS** [comment]
It might suffice to rewrite the page intro and keep the list of resources as is. I think the intro should speak to the idea of contributing on a higher level. Many people probably come here and don't even know what contributing means or what types of skill sets are needed, etc. To sort that out, I started a [Google Doc](https://docs.google.com/document/d/12jXgCa0iFS68G0-ubqo1jgib6ta4T4MqdT2Qa_AHef0/edit?usp=sharing). Please take a look.

@sqcken would be amazing if you could help out with this.

**Comment by ConorOkus** [comment]
ACK #option 2

**Comment by sqcken** [comment]
Yup. Happy to help. I’ll be able to dig into the docs you guys sent over shortly. Just knocking a couple other things out of the way first.

**Comment by GBKS** [comment]
Some reference points I found.

- [BTCPay - How to contribute](https://docs.btcpayserver.org/Contribute/): Has a nice breakdown by interest/skillset (coding, testing, writing, designing...)
- [Bisq contributor checklist](https://docs.bisq.network/contributor-checklist.html) better top-level intro than BTCPay, but also less depth (seems almost identical to the [Wasabi wallet contributor checklist](https://docs.wasabiwallet.io/building-wasabi/ContributionChecklist.html))
