### ISSUE TITLE
Expand on onboarding carousel on the "First use" page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#530]
Per [this comment](https://github.com/BitcoinDesign/Guide/pull/525#issuecomment-944436637).

**Comment by Bosch-0** [comment]
I think we should include this expanded carousel as part of the Funding a wallet page as @sbddesign pointed out [here](https://github.com/BitcoinDesign/Guide/pull/525#issuecomment-944436637) rather than in the first use.

**Comment by Bosch-0** [comment]
Addressed in the funding a wallet PR
