### ISSUE TITLE
Add explicit distinction between `create a wallet` and `restore a wallet` on the initial screen as primary and secondary buttons

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#535]
**Describe your content request**

While we reviewed wallets in #493 I noticed one thing that we constantly recommend wallets to do, and that's better visual distinction between create a wallet and restore a wallet buttons.

Obviously, create a wallet is primary action for majority of users. 

We visually already showcase this, but perhaps there needs to be a small note somewhere to make it more explicit?

**Link to the page**

_Please add a link to the page you're requesting content change for (if applicable)_

https://bitcoin.design/guide/onboarding/first-use/

**Why would you like to change the content?**
_If you're requesting a change to existing content, please describe concisely why you would like to change it?_

**Suggestions**
_If you have a concrete suggestion on how to change/add the content, write it up here_

**Additional context**

![Screenshot 2021-10-22 at 12 36 46](https://user-images.githubusercontent.com/36959754/138440964-8fe29901-0b6f-4070-adfa-e4b1c280e250.png)
![Screenshot 2021-10-22 at 12 42 28](https://user-images.githubusercontent.com/36959754/138440983-bf784ac6-be8f-4f4c-a601-732b6b7d4465.png)

_Add any other context about the request here._

**Content guidelines**
If you're a contributor looking to tackle the issue, you can [preview our content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/).

**Comment by GBKS** [comment]
Addressing the main topic of this issue in #549.

**Comment by GBKS** [comment]
Created an issue for the page re-ordering with #550.
