### ISSUE TITLE
Decide whether we need a dedicated  "About" page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#54]
The site nav currently has an "About" option with placeholder content.

Do we need that page or is the info on the home page enough? If we need it, what information would go on there?

**Comment by ConorOkus** [comment]
I think we can probably remove it for now. I see the homepage changing quite a lot over time, doing the heavy lifting and becoming are more fleshed out landing page linking to all the various things the community is working on.
 - Guide
 - Blog
 - Tutorials
 - Showcase 
 - Newsletter
 - Wallet

**Comment by pavlenex** [comment]
Personally I think the About page for the bitcoin.design would be helpful, but at this moment and by looking at the homepage it seems to be unnecessary.

**Comment by digitalforus** [comment]
Hi ! I am Hakeem, a User Interface Designer. If there's any way I can contribute please do let me know

**Comment by ConorOkus** [comment]
Hi @digitalforus, thanks for showing interest in the community. If you are free, please join us for our [community call](https://github.com/BitcoinDesign/Meta/issues/56) tomorrow.

**Comment by digitalforus** [comment]
I've done that. Thanks 😊

**Comment by GBKS** [comment]
Closing this issue as it's been lingering for 2 months, there were only 2 comments, both pointing towards not having that page. Clearly not an urgent thing to have an "About" page at the moment.
