### ISSUE TITLE
Add ⚡️ content to `Private key management` > Section landing page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#542]

**Comment by danielnordh** [comment]
Having looked at this page I don't think it needs to change.
The first introduction to Lightning should probably be on the 'Overview' page.

**Comment by pavlenex** [comment]
I agree, doesn't look we need to add anything here. The only updates that could be done are after page re-ordering in ##550

I think we can close this one.

**Comment by Bosch-0** [comment]
Yep agree this doesn't require any additions.
