### ISSUE TITLE
Add ⚡️ content to `Private key management` > `Overview`

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#543]
First step is to review [the page](https://bitcoin.design/guide/private-key-management/overview/) for additions and changes.

Ideas:
- Add extra consideration about how the choice of scheme should also depend on Lightning support, since this requires storing channel data (and syncing regularly instead of just once) as well as key being hot. Probably requires a larger revision of this page.

**Comment by danielnordh** [comment]
Suggest:

- A 'tip' bubble explaining Lightning requirements/limitations in terms of hot key, channel state data)
- Revise summary description of schemes
- Review all text for needed changes

**Comment by pavlenex** [comment]
Done in #563
