### ISSUE TITLE
Add ⚡️ content to `Private key management` > `Automatic cloud backup`

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#544]
First step is to review [the page](https://bitcoin.design/guide/private-key-management/cloud-backup/) for additions and changes.

Ideas:
- Add info about versatility of this solution. It can easily also be used for backing up Lightning channels, etc.

**Comment by sbddesign** [comment]
I can take this one. There will be some overlap with what I have been working on in the Onboarding > Backups section.

**Comment by danielnordh** [comment]
Closed by #559
