### ISSUE TITLE
Add ⚡️ content to `Private key management` > `Manual backup`

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#545]
First step is to review [the page](https://bitcoin.design/guide/private-key-management/manual-backup/) for additions and changes.

Ideas:
- Add note about potentially backing up derivation path, fingerprint, etc
- Add note about limits of manual backup - descriptors, Lightning channels, etc are all too complex to write down

**Comment by sbddesign** [comment]
I can take this one as well. There will be some overlap with what I have been working on in the Onboarding > Backups section.

**Comment by danielnordh** [comment]
Closed by #559
