### ISSUE TITLE
Add ⚡️ content to `Private key management` > `Bitcoin backups`

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#548]
First step is to review [the page](https://bitcoin.design/guide/private-key-management/backups/) for additions and changes.

Ideas:
- Define page scope - is this only about cold-storage key backups? Do we expand it to Lightning? Do we also talk about restoring wallets or using backups for migration, and the complexities involved?

**Comment by pavlenex** [comment]
Done #565
