### ISSUE TITLE
Decide whether we want a "Projects" page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#55]
The site nav currently has a "Projects" option with a list FOSS bitcoin projects (Wasabi, bisq, etc). I believe the idea is to present projects the community likes or is involved in.

Is this something we want? The idea generally sounds good, but might not be so easy to implement since it could be tricky to identify requirements for projects to be included.

**Comment by ConorOkus** [comment]
I was thinking this might refer more to projects specifically initiated by this community e.g The Design Guide. Or maybe upcoming/future projects e.g a reference mobile wallet designed by the community. 

Like you say not sure what the requirements would need to be included, but I definitely feel we should link to other valuable FOSS projects and encourage designers to get involved in those.

**Comment by GBKS** [comment]
Resolved with #67 .
