### ISSUE TITLE
Add ⚡️ content to `Payments` > `Transactions`

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#571]
First step is to review [the page](https://bitcoin.design/guide/payments/transactions/) for additions and changes.

Ideas:
- Add ideas for changes here...

**Comment by Bosch-0** [comment]
Quick overview recommendations: 

- Change title from `Transactions overview` to `What is a bitcoin payment?` 
- Change the focus giving a big picture overview of how the Lightning network works:
    - Channel construction - could salvage some of the current content around what a transaction is for this.
    - Lifecycle of a payment channel.
    - Overview of routing on LN
    - Payments structure (HTLCs onion wrapping etc.)
    - Lightning network fees.

We should keep a lot of this on-chain content for in the future when we eventually focus on an on-chain vault type product case study. 

Happy to tackle this page if no one else is offering.
