### ISSUE TITLE
Add ⚡️ content to `Payments` > `Sending bitcoin`

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#572]
First step is to review [the page](https://bitcoin.design/guide/payments/send/) for additions and changes.

Ideas:
- Add ideas for changes here...

**Comment by Bosch-0** [comment]
Quick overview: 

Pretty much a whole new page needed.

- Sending payments - how its done
    - Basic flow overview at the start.  
    - How payment routes are worked out.
    - Invoices / Lightning addresses. 
- Cover other payment protocols to consider (LNURL-Pay, BOLT11, BOLT12, AMP invoices). 
- Add details about LN sent payment confirmation UX: https://github.com/BitcoinDesign/Guide/issues/560
- Add details around sending LN error states: https://github.com/BitcoinDesign/Guide/issues/505. I don't think we need a whole new page for this like that issue says.
- Should we have details around contacts UX? I'd recommend having a `Wallet management` page that covers meta topics like contacts, networking, soft channel management and other things usually found in wallet settings.

**Comment by moneyball** [comment]
We can cover privacy tradeoffs with various solutions too. For example, is pathfinding done on the user's client device? On a 3rd party server (loss of privacy)? Trampoline is somewhere in between.

**Comment by GBKS** [comment]
I put together a flow diagram for payment UI, there's a [video overview](https://youtu.be/O2ZRvBtCH6w) and a [Figma file](https://www.figma.com/file/0VkkjgsB2Ymfl1OOJZ6XX3/Lightning-pay-diagram?node-id=0%3A1).

Just from looking at the many steps in this diagram, my hunch is to minimize technical details on this page, and instead link to other pages that cover these things. There are 5 entry points (identifier, contact, QR code, link, NFC) that could each be unique flows to showcase, then there's the send screen with its complexities (on-chain, Lightning, fees, liquidity, channel opening, routing...), and the transaction process (broadcast, pending, success, failure). It's very intricate.

**Comment by GBKS** [comment]
Here's a second video with an effort to try to turn the diagram into UI mockups. Mostly trying to rough in the various pieces, there are still a lot of things to work through. https://youtu.be/_1oSor7SNeE
