### ISSUE TITLE
Add ⚡️ content to `Payments` > `Coin selection`

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#573]
First step is to review [the page](https://bitcoin.design/guide/payments/send/coin-selection/) for additions and changes.

Ideas:
- Add ideas for changes here...

**Comment by Bosch-0** [comment]
Quick overview:

- For the type of product this section is focusing on this page isn't really needed anymore. We can still keep it though and include it in later case studies we work on in the future.
- Alternatively we could have some kind of `Advanced` page in the payments section that covers things like this, channel management etc. I think it is still handy for complete noob wallets to have this features but they should be hidden well and only accessible to the users who seek it.

**Comment by danielnordh** [comment]
Agree with @Bosch-0, this page is only for advanced use cases.
It's worth keeping but doesn't need to appear in the side nav (IMO), but can be linked to from the updated Sendin bitcoin page.

I have made a few small tweaks to the introduction, mentioning how for Lightning, coin selection is only relevant to the transaction that opens the channel.

**Comment by pavlenex** [comment]
Done #586
