### ISSUE TITLE
Add ⚡️ content to `Payments` > `Receiving bitcoin`

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#574]
First step is to review [the page](https://bitcoin.design/guide/payments/receive/) for additions and changes.

Ideas:
- Add ideas for changes here...

**Comment by Bosch-0** [comment]
Quick overview:

Whole new page needed.

- Receiving payments - how its done
    - Basic flow overview at the start.
    - Sharing invoice / Lightning address
    - Cover other payment protocols to consider when receiving (LNURL-Pay, BOLT11, BOLT12, AMP invoices). How are these shared with the recipient. 
- Add details about LN receive payment confirmation UX. 
- Add details around receiving LN error states: https://github.com/BitcoinDesign/Guide/issues/505
- Like I mentioned on the sending bitcoin issue, I'd recommend having a Wallet management page that covers meta topics like contacts, networking, privacy soft channel management and other things usually found in wallet settings.
