### ISSUE TITLE
Add ⚡️ content to `Payments` > `Transaction privacy`

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#575]
First step is to review [the page](https://bitcoin.design/guide/payments/privacy/) for additions and changes.

Ideas:
- Add ideas for changes here...

**Comment by Bosch-0** [comment]
Quick overview:

- Rename page from `Transaction privacy` to `Payments privacy`. 
- Add content about being careful where invoices / are shared. 
- Add content around connecting your application over Tor.
- Add content around using un-broadcasted channels if offering Pay-to-open Lightning service.
- Move CoinJoin details to an advanced section and add Lightning context.
- Experimental techniques? Rendezvous, trampoline nodes/payments, statechains, minimint. 

Resources:

https://abytesjourney.com/lightning-privacy/
https://blog.wasabiwallet.io/1-btc-ln-privacy-grant/
https://en.bitcoin.it/wiki/Privacy#Lightning_Network
https://medium.com/@RubenSomsen/statechains-non-custodial-off-chain-bitcoin-transfer-1ae4845a4a39
https://blog.blockstream.com/en-blockstream-sponsors-minimint-a-privacy-focused-community-led-scaling-solution-for-bitcoin/

**Comment by GBKS** [comment]
To get this rolling, I started a Google Doc with the page copy and start revising it. Goal is to create a minimal update that covers Lightning basics. Then @johnsBeharry (and/or others) can do future revisions as they desire with more depth and detail.

[Here's the doc](https://docs.google.com/document/d/1dsmUcgiGOxATPrN2xQdtOfouwnwSyzcwHroPR1nDpXc/edit?usp=sharing). Please review and leave comments.
