### ISSUE TITLE
Add info around hiding home screen balances by default

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#578]
A UX blind spot I think many Bitcoin mobile wallets have is when you open your application the first thing you see is your wallet balance. When using your wallet in the real world, pointed out by @sbddesign during his trip to [El Salvador](https://d.elor.me/2021/11/hiding-wallet-balances/), it's a major privacy issue to have your balance shown straight away as a peering on-looker / camera etc. could easily see how much bitcoin you have. 

Bitcoin mobile spending wallets haven't been used widely in the real world so this problem hasn't been so evident but many have reported this now with [people on the ground in El Salvador](https://twitter.com/zndtoshi/status/1462929195512827907?s=21) the past week making payments.

A good design practice we should add to the guide is not showing wallet balances as the first screen when opening your application. Below is an example of cashapps initial screen which does not show a balance and jumps straight into a user pay flow as an example.

![image](https://user-images.githubusercontent.com/55287964/143165801-e1c8b039-edb1-48a9-8f97-bd1b90f638ed.png)

I much prefer this approach rather then using a hide balance toggle (although this should always be an extra option) as users may forget to have this toggled on, or they may need to apply the toggle when opening the app which by that time a peering on-looker likely has already seen the balance. 

Guide sections to add details around this:

- [ ] [Protecting a wallet](https://bitcoin.design/guide/onboarding/protecting-a-wallet/)
- [x] [Sending bitcoin](https://bitcoin.design/guide/payments/send/)
- [x] [Receving bitcoin](https://bitcoin.design/guide/payments/receive/)
- [ ] [Transactions privacy](https://bitcoin.design/guide/payments/privacy/)

**Comment by paulosacramento** [comment]
Hi guys.

On the [Security/Spending Wallet](https://bitcoin.design/guide/daily-spending-wallet/security/) we already have recommendations about:

- Quickly hiding/displaying balance by tapping: https://bitcoin.design/guide/daily-spending-wallet/security/#quickly-hiding-balances
- Moving the hide/display balance toggle from the home: https://bitcoin.design/guide/daily-spending-wallet/security/#an-application-wide-setting

But I would like to support @Bosch-0 proposal of adding a third recommendation, described by him here: 

> A good design practice we should add to the guide **is not showing wallet balances as the first screen when opening your application**. Below is an example of cashapps **initial screen which does not show a balance and jumps straight into a user pay flow** as an example.

I think we should also add this specific recommendation to https://bitcoin.design/guide/daily-spending-wallet/security/ 

I can see that this issues has been closed, but I think this is very important and that @sbddesign would also support this addition.
