### ISSUE TITLE
Feedback request for the "Open design" page of the "Getting started" section

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#58]
I'd love to get your feedback on this page. Please view [this short video](https://youtu.be/keTOgnQQtSw) for details.

I have a [PR](https://github.com/BitcoinDesign/Guide/pull/20) for this page, but might be easier to iterate on copy in the doc linked below.

[Google doc](https://docs.google.com/document/d/1KkPc6RaYlc6Gc4WEfT0zUKtuE-QdTkupR6Zrnmku0I0/edit?usp=sharing)
[Preview link](https://gbks.github.io/Guide/guide/getting-started/open-design/)

Please let me know what questions you might have. As far as feedback, everything is helpful, whether it's your overall response to the page, to editing copy, coming up with better illustrations, or anything else.

**Comment by AlexaAker** [comment]
Thank you Christoph, you have a thorough explanation on the spirit of Open Design and how it relates to bitcoin. Appreciate the values section and how Open Design is about contributing to projects that feel meaningful to its participants.

Only note would be on licensing. Its primary objective is to allow freedom of access to the use of information and resources. It isn’t so much about control, but about opening doors to share and build upon the content, in almost any manner. 

It does protect the creator from being held liable, and it asks for attribution, as well as retaining some publicity and trademark rights. 

But it is meant to be open-- including the right to use, modify, and redistribute, even for commercial purposes.

**Comment by pavlenex** [comment]
@GBKS this one seems to be finished, ready to close or do we still need feedback considering the PR is merged?

**Comment by GBKS** [comment]
@pavlenex thanks for the reminder.

@AlexaAker that is a very good point. How about we address this in a new issue?
