### ISSUE TITLE
Add Lightning address content to guide

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#581]
This another yet-to-be UI/UX flow that we could design for in the guide. 

[Lightning addresses](https://lightningaddress.com/) are a simplified way to send Lightning payments using an address like bosch@zeusln.app instead of sharing a QR or invoice data. As the website states `Like an email address, but for your Bitcoin!`

A great addition we could add to the guide is around recommending that mobile wallets make use of this feature. Lightning addresses also pave the way for UX friendly contact lists which will be something we will cover in the guide soon. 

Lightning address content recommendations for the guide: 

- [x] Add Lightning address support (send + receive) to `Interoperability` payments section.
- [x] Add content around having users generate a receiving Lightning address once in the wallet app `Funding a wallet`, `Payments`
- [x] Add content around sending to a Lightning address to `Payments` > `Sending bitcoin`.
- [x] Add content around receiving to a Lightning address to  `Payments` > `Receiving bitcoin`

A later addition once we know how we will integrate contacts info into the guide: 
- [x] Add content around creating contact lists using Lightning addresses 

Throughout these sections it may also be relevant to discuss potential trade-offs of supporting and using Lightning addresses.

**Comment by GBKS** [comment]
Lightning addresses are a great idea, but I am concerned that they will be mixed up with email addresses. The format is identical, so how can I tell the difference? People might mistakenly send emails to Lightning addresses. Any chance we can provide UX guidance around this? I am not convinced the label "Lightning address" is enough, as "Lightning" might be interpreted as a service like Gmail or Yahoo Mail.

**Comment by Bosch-0** [comment]
Completely agree with those concerns. Maybe it could be worth discussing this with the people working on the protocol / creating the servers. Not sure of any UX guidance to give right now. 

Two possible protocol solutions:

- They could be all be presented with a `pay` sub-domain format like bosch@pay.zeusln.app? 
- For sharing Lightning addresses we may need a URI format, something like `pay:bosch@zeusln.app` to distinguish it from emails which use emailto:bosch@zeusln.app. 

At least it isn't like on-chain and the payment will just fail.

**Comment by Bosch-0** [comment]
Closing this as we have a decent amount of content on Lightning address in the payments requesting and sending pages now. 

One other addition may be to add something about generating a Lightning address during on-boarding.
