### ISSUE TITLE
Add ⚡ POS terminals to `Hardware overview` page. 

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#584]
As per discussions [here](https://bitcoindesign.slack.com/archives/C0191UWDHBP/p1638187623003000?thread_ts=1638139393.001200&cid=C0191UWDHBP) offline Lightning POS terminals are likely something that will become more commonplace in the future as being mobile + maintaining a node at the same time is not very practical. We should add this to the hardware overview page as well as potentially discuss this in the payments / receiving sections in the payments chapter. 

[Offline LNURLPos repo](https://github.com/arcbtc/LNURLPoS)

**Comment by GBKS** [comment]
Can this be just in general about POS terminals, with offline and Lightning being properties of some terminal types?

**Comment by Bosch-0** [comment]
Yep for sure, changed title name
