### ISSUE TITLE
Add ⚡ info around route reliability and fee trade-off

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#585]
Letting users decide if they would like to optimize payments for fees or reliability is something we should cover in the guide. 

> In Lightning pathfinding the two main variables to optimize for are routing fee and reliability. Routing fee is concrete. It is the sat amount that is paid when a payment succeeds. Reliability is a property of a route that can be expressed as a probability. The probability that a route will be successful.
> 
> During pathfinding, route options are compared against each other. So for example:
> 
> Route A: fee 10 sat, success probability 50%
> Route B: fee 20 sat, success probability 80%
> 
> Which one is the better route? That depends on user preference. A patient user will probably go for route A in the hope of saving on fees whereas for a time-sensitive payment route B looks better.
> 
> It would be great to offer this trade-off to the user in a simple way. Preferably a single [0, 1] value that controls the selection process. At 0, the route is only optimized for fees and probabilities are ignored completely. At 1, the route is only optimized for reliability and fees are ignored completely.
> 
> But how to choose between the routes A and B for a value somewhere in between 0 and 1? For example 0.5 - perfect balance between reliability and fee. But what does that mean exactly?
> 
> Anyone got an idea on how to approach this best? I am looking for a simple formula to decide between routes, preferably with a reasonably sound probability-theoretical basis (whatever that means).
> 
> Joost

A UI worth exploring when thinking about this problem is how maps apps like Google maps, Apple maps, Waze etc. give various routes to a destination and the user can choose which one they want based on select variables.

Relevant to your payments -> sending page @GBKS 

[From this weeks optech](https://bitcoinops.org/en/newsletters/2021/11/24/)
[Lightning dev mailing list post](https://lists.linuxfoundation.org/pipermail/lightning-dev/2021-November/003342.html)

**Comment by Bosch-0** [comment]
Quick example I did using Zeus's UI

![image](https://user-images.githubusercontent.com/55287964/144169052-430060a4-4041-4ee0-b484-dbfa6987c1fc.png)

**Comment by GBKS** [comment]
I would only show this to users if absolutely necessary (fee is half of the amount transferred, 5x difference in fees, etc), or hide it in some advanced setting.

A second aspect, and this is something I am not 100% on, is whether these fee predictions can be accurate. As far as I know, the initial route probe is just an estimate and can't guarantee that the necessary liquidity is actually available in the selected channels.

A third thought is whether probability even matters if a transaction takes a split-second. Why not go for the low probability one and wait another second if it doesn't work out?

Lots of questions...

**Comment by Pornprasert** [comment]
Hi

**Comment by Bosch-0** [comment]
> A second aspect, and this is something I am not 100% on, is whether these fee predictions can be accurate. As far as I know, the initial route probe is just an estimate and can't guarantee that the necessary liquidity is actually available in the selected channels.

From my understanding currently this is a no, but things are getting better with time. 

Yeah having it automatically start from the lower bound probability then scale up if the payment keeps failing behind the scenes would be good but there could be a big difference in fees that should be communicated to users. As the LN grows and mobile nodes need to start using trampoline nodes fees will get bigger and something similar to what is shown above may need to be used.

**Comment by GBKS** [comment]
This is now covered in the [Sending bitcoin](https://bitcoin.design/guide/payments/send/#advanced-options) page. Good to close this issue?

**Comment by Bosch-0** [comment]
Yep!
