### ISSUE TITLE
Proposal for Bitcoin community homepage theme banner 

### ISSUE THREAD

**Issue by Rutuja-Kelkar** [BitcoinDesign/Guide#592]
Hello All,

I'd like to contribute for bitcoin homepage theme banner, Here's the [figma file ](https://www.figma.com/file/DFu3VQNe3CjpUsCShkH5QV/Bitcoin-design-community-contributions?node-id=0%3A1)
Quick image glance is attached below, please have a look.

I came up with this design since it represents "A bitcoin wallet, which are gateways to global authentic transactions".
Happy to hear your feedback, Thanks :)

![WebV1](https://user-images.githubusercontent.com/66067675/145701721-57aff727-ff92-470c-a743-26eaf05e00f1.png)

![MobileV1](https://user-images.githubusercontent.com/66067675/145701768-94977b59-dddc-4af3-b916-abcdfabc7fa3.png) ![MobileV2](https://user-images.githubusercontent.com/66067675/145701772-08712db7-07bc-43bf-89ce-9e740910e658.png)

![WebsiteFrame](https://user-images.githubusercontent.com/66067675/145701810-c8655181-c872-4bcd-874e-2de8c6c0c719.png) 
![MobileFrame](https://user-images.githubusercontent.com/66067675/145701817-380faf13-b38b-4997-bf1a-b25a79597fb7.png)

![ColourPallate](https://user-images.githubusercontent.com/66067675/145701873-e5939c0e-104b-46aa-b550-af24518f703f.png)

**Comment by danielnordh** [comment]
Thank you for the contribution!
Are you comfortable adding this to the `theme.js` file yourself and create a pull request?
If not I'm sure someone could help you out.

**Comment by sbddesign** [comment]
My one suggestion would be to make "Open source design for..." a lighter color (maybe white) for contrast and legibility.

**Comment by Rutuja-Kelkar** [comment]
Thank you @GBKS and @sbddesign for your suggestions, I have taken your comments into consideration and changed the design, Please have a look
![WebV1](https://user-images.githubusercontent.com/66067675/145864015-06bb0366-3aea-446a-9c12-225d74baddc7.png)

**Comment by Bosch-0** [comment]
Great stuff @Rutuja-Kelkar, love it :) Agree with @sbddesign though, a white font has more clearer contrast:

![image](https://user-images.githubusercontent.com/55287964/145922910-77da381b-6581-4e26-a2a0-75fdea6fd3f7.png)

**Comment by Rutuja-Kelkar** [comment]
Thanks you @Bosch-0

**Comment by pavlenex** [comment]
#609
