### ISSUE TITLE
Set up "jekyll-compress-images" plugin to auto-optimize images

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#60]
Best to automate this so our source images are high-res and crisp and we don't have to remember to manually compress images.

[Plugin link](https://github.com/valerijaspasojevic/jekyll-compress-images)

**Comment by danielnordh** [comment]
Yes please!

**Comment by Bosch-0** [comment]
Great tool, concept ACK on using it for the Guide!

**Comment by GBKS** [comment]
OK, so this does not seem to be as simple. Make somebody with more experience with Github Pages and Jekyll can look into this. Here's what I found:
- Github Pages only allows for certain specific [plugins](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages-and-jekyll#plugins) to be installed (for security probably). The plugin above is not included in [that list](https://pages.github.com/versions/).
- I tried running the plug-in locally, got it to run after some debugging, but it didn't compress images. Could not figure out why.

So this particular plugin seems like a dead-end. However, I found a different solution, a Github app called [ImgBot](https://imgbot.net), that does the same thing. Main difference is that images are not optimized during build, but this app keeps an eye on the repo and when it finds new images, it optimizes them and creates a new PR. This app is free for open-source projects and seems to be pretty freely configurable. How about we try this one?

**Comment by johnsBeharry** [comment]
I attempted to do this with a workflow but realised today that the site does not actually use Github Pages - it's hosted on netlify - which has some image optimisation options available its dashboard so @GBKS or @pedromvpg would have to configure it.

Furthermore we can ask why do we need additional optimisations of source files?

1. If it's to keep the overall repository size smaller when contributors are cloning, then we have to accept that it will add more friction for contributors as the way to achieve this would be to compress the images in PRs before they are merged.
2. To optimise the site load time can be simply be done at build (netlify)

**Comment by pedromvpg** [comment]
Activated Image Optim plug-in on netlify.
![image](https://user-images.githubusercontent.com/807505/101800456-4aac8080-3adb-11eb-8143-bfb90322594d.png)

But it is already getting deployment errors. Would propose keeping the optimization more on the designer side and make sure the markdown is calling web-ready images

![image](https://user-images.githubusercontent.com/807505/101801931-df63ae00-3adc-11eb-89eb-8a908232038e.png)

**Comment by GBKS** [comment]
Completed via #73 .
