### ISSUE TITLE
Add `Payments are final` to `Why Bitcoin is Unique` page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#600]
One thing I feel that is missing here is explaining how bitcoin payments are final, meaning that payments can not be reversed. Within the same section we should also briefly mention how it compares to the traditional finance system in that it is a push, not pull, payment system.

**Comment by GBKS** [comment]
The "[You own it](https://bitcoin.design/guide/getting-started/why-bitcoin-is-unique/#you-own-it)" section addresses this.

The two points you mention are implied in the paragraph. 
> custodial benefits of physical cash

and

> not only do you own your bitcoin, no one can take them away.

With cash, you also can't reverse a payment (the other person has to give it back to you). `no one can take them away` implies a push-system.

Both points could maybe be more explicit, which would just require minor copy tweaks. Don't think it's a big deal though.

**Comment by Bosch-0** [comment]
Added a few words in https://github.com/BitcoinDesign/Guide/pull/623, agree that section covers it pretty well already :)
