### ISSUE TITLE
Bits

### ISSUE THREAD

**Issue by Dusto509** [BitcoinDesign/Guide#607]
content/get-started/learning-about-github/githubs-products.md-{:dusto_chain}/dash/raw/block/addresses/{:hash},... {:hash}[]-products.md-from b2291af26abd02ce5c544e450751711ec465812e mon sep 17 00:00:00 2001
from: modusto <96756518+dusto509@users.noreply.github.com>
date: tue, 4 jan 2022 01:19:29 -0800
subject: [patch] update contributing.md
mime-version: 1.0
content-type: text/plain; charset=utf-8
content-transfer-encoding: 8bit

cli
/
cli
public
code
issues
388
pull requests
31
discussions
actions
projects
1
security
1
insights
cli/docs/install_linux.md
@bsiegert
bsiegert add installation instructions for netbsd/pkgsrc (#4931)
…
 24 contributors
@vilmibm@mislav@fossdd@dbruns@darkraspberry@zpuskas@yzgyyang@0atman@tomrule007@tobix@tniessen@droideck
 184 lines (121 sloc)  4.25 kb
installing gh on linux and bsd
packages downloaded from https://cli.github.com or from https://github.com/cli/cli/releases are considered official binaries. we focus on popular linux distros and the following cpu architectures: i386, amd64, arm64, armhf.

other sources for installation are community-maintained and thus might lag behind our release schedule.

official sources
debian, ubuntu linux, raspberry pi os (apt)
install:

curl -fssl https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
sudo apt update
sudo apt install gh
upgrade:

sudo apt update
sudo apt install gh
fedora, centos, red hat enterprise linux (dnf)
install:

sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
sudo dnf install gh
upgrade:

sudo dnf update gh
opensuse/suse linux (zypper)
install:

sudo zypper addrepo https://cli.github.com/packages/rpm/gh-cli.repo
sudo zypper ref
sudo zypper install gh
upgrade:

sudo zypper ref
sudo zypper update gh
manual installation
download release binaries that match your platform; or
build from source.
unofficial, community-supported methods
the github cli team does not maintain the following packages or repositories and thus we are unable to provide support for those installation methods.

snap (do not use)
there are so many issues with snap as a runtime mechanism for apps like github cli that our team suggests never installing gh as a snap.

arch linux
arch linux users can install from the community repo:

sudo pacman -s github-cli
alternatively, use the unofficial aur package to build github cli from source.

android
android 7+ users can install via termux:

pkg install gh
freebsd
freebsd users can install from the ports collection:

cd /usr/ports/devel/gh/ && make install clean
or via pkg(8):

pkg install gh
netbsd/pkgsrc
netbsd users and those on platforms supported by pkgsrc can install the gh package:

pkgin install gh
to install from source:

cd /usr/pkgsrc/net/gh && make package-install
openbsd
in -current, or in releases starting from 7.0, openbsd users can install from packages:

pkg_add github-cli
funtoo
funtoo linux has an autogenerated github-cli package, located in dev-kit, which can be installed in the following way:

emerge -av github-cli
upgrading can be done by syncing the repos and then requesting an upgrade:

ego sync
emerge -u github-cli
gentoo
gentoo linux users can install from the main portage tree:

emerge -av github-cli
upgrading can be done by updating the portage tree and then requesting an upgrade:

emerge --sync
emerge -u github-cli
kiss linux
kiss linux users can install from the community repos:

kiss b github-cli && kiss i github-cli
nix/nixos
nix/nixos users can install from nixpkgs:

nix-env -ia nixos.gitandtools.gh
opensuse tumbleweed
opensuse tumbleweed users can install from the official distribution repo:

sudo zypper in gh
© 2022 github, inc.
---
 contributing.md | 125 +++++++++++++++++++++++++++++++++++++++++++++++-
 1 file changed, 124 insertions(+), 1 deletion(-)

diff --git a/contributing.md b/contributing.md
index f98fbecd61f..d7deb1fcc0b 100644
--- a/contributing.md
+++ b/contributing.md
@@ -1,4 +1,127 @@
-# contributing
+#cli
+/
+cli
+public
+code
+issues
+388
+pull requests
+31
+discussions
+actions
+projects
+1
+security
+1
+insights
+cli/docs/install_linux.md
+@bsiegert
+bsiegert add installation instructions for netbsd/pkgsrc (#4931)
+…
+ 24 contributors
+@vilmibm@mislav@fossdd@dbruns@darkraspberry@zpuskas@yzgyyang@0atman@tomrule007@tobix@tniessen@droideck
+ 184 lines (121 sloc)  4.25 kb
+installing gh on linux and bsd
+packages downloaded from https://cli.github.com or from https://github.com/cli/cli/releases are considered official binaries. we focus on popular linux distros and the following cpu architectures: i386, amd64, arm64, armhf.
+
+other sources for installation are community-maintained and thus might lag behind our release schedule.
+
+official sources
+debian, ubuntu linux, raspberry pi os (apt)
+install:
+
+curl -fssl https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
+echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
+sudo apt update
+sudo apt install gh
+upgrade:
+
+sudo apt update
+sudo apt install gh
+fedora, centos, red hat enterprise linux (dnf)
+install:
+
+sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
+sudo dnf install gh
+upgrade:
+
+sudo dnf update gh
+opensuse/suse linux (zypper)
+install:
+
+sudo zypper addrepo https://cli.github.com/packages/rpm/gh-cli.repo
+sudo zypper ref
+sudo zypper install gh
+upgrade:
+
+sudo zypper ref
+sudo zypper update gh
+manual installation
+download release binaries that match your platform; or
+build from source.
+unofficial, community-supported methods
+the github cli team does not maintain the following packages or repositories and thus we are unable to provide support for those installation methods.
+
+snap (do not use)
+there are so many issues with snap as a runtime mechanism for apps like github cli that our team suggests never installing gh as a snap.
+
+arch linux
+arch linux users can install from the community repo:
+
+sudo pacman -s github-cli
+alternatively, use the unofficial aur package to build github cli from source.
+
+android
+android 7+ users can install via termux:
+
+pkg install gh
+freebsd
+freebsd users can install from the ports collection:
+
+cd /usr/ports/devel/gh/ && make install clean
+or via pkg(8):
+
+pkg install gh
+netbsd/pkgsrc
+netbsd users and those on platforms supported by pkgsrc can install the gh package:
+
+pkgin install gh
+to install from source:
+
+cd /usr/pkgsrc/net/gh && make package-install
+openbsd
+in -current, or in releases starting from 7.0, openbsd users can install from packages:
+
+pkg_add github-cli
+funtoo
+funtoo linux has an autogenerated github-cli package, located in dev-kit, which can be installed in the following way:
+
+emerge -av github-cli
+upgrading can be done by syncing the repos and then requesting an upgrade:
+
+ego sync
+emerge -u github-cli
+gentoo
+gentoo linux users can install from the main portage tree:
+
+emerge -av github-cli
+upgrading can be done by updating the portage tree and then requesting an upgrade:
+
+emerge --sync
+emerge -u github-cli
+kiss linux
+kiss linux users can install from the community repos:
+
+kiss b github-cli && kiss i github-cli
+nix/nixos
+nix/nixos users can install from nixpkgs:
+
+nix-env -ia nixos.gitandtools.gh
+opensuse tumbleweed
+opensuse tumbleweed users can install from the official distribution repo:
+
+sudo zypper in gh
+© 2022 github, inc. contributing
 
 hi there! we're excited you've got ideas to improve topics and collections. you're helping the community discover valuable information.
 96756518+dusto509@users.noreply.github.comcontributing.md3883124184https://github.com/cli/cli/releaseshttps://cli.github.comhttps://cli.github.com/packages/githubcli-archive-keyring.gpghttps://cli.github.com/packagesnixos.gitandtools.ghhttps://cli.github.com/packages/rpm/gh-cli.repo2022125124

**Comment by sbddesign** [comment]
This is spam.
