### ISSUE TITLE
Foundations / Units & Symbols

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Guide#61]
```meta
type: page
title: Units & Symbols
permalink: /guide/payments/units-and-symbols/
file: guide/payments/units-and-symbols.md
```

Looking for someone to research and write this foundations page relating to payments.
Below is a rough outline to get you going.

### Units

Currently there are two units that are widely used in apps, bitcoin and satoshi (sats). Satoshi seems to be what is used mostly within apps that support lightning payments. Bitcoin with 8 decimals is the unit common to onchain payments. Making a 1 satoshi payment in a transaction onchain isn't going to be so economical.

On lightning network the base unit is millisatoshi/msats which is a subunit of satoshis (I've never seen this exposed in a UI though).

There are also other units which are less used colloquially, and it's an interesting the process of how these units come into use. Should they also be included in the guide (see [Units](https://en.bitcoin.it/wiki/Units))? 

### Symbols / Codes
- What symbols and codes exist?
- What are different symbols/codes which are popularly used?
- Are there cases where one should be used over another?
  - e.g. What is the impact by the limited support for the bitcoin unicode symbol (see #5) ?

### Consider Amount Display

Once these foundations are written - you should have a good base to explore Amount Displays more deeply. @GBKS has captured some of the early conversations around amount display in the community slack in issue #3 and can actually be included as is for a first version.

### REF
- [The visual language of bitcoin](https://deploy-preview-20--sad-borg-390916.netlify.app/guide/getting-started/visual-language/)
- https://en.bitcoin.it/wiki/Satoshi_(unit)
- https://en.bitcoin.it/wiki/Units
- https://en.wikipedia.org/wiki/Denomination_(currency)
- [First time contributors read these Content Guidelines](https://bitcoin.design/guide/content-guidelines)
- https://blog.lolli.com/stacking-sats/
- https://wiki.ion.radar.tech/tech/bitcoin/satoshi-unit-of-currency#history

**Comment by ConorOkus** [comment]
Interesting thread on why we should start using bits and sats as denominators.

https://www.reddit.com/r/BitcoinBeginners/comments/nxi96h/lets_start_using_bits_as_a_main_denominator/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by ConorOkus** [comment]
Proposal by Mark Nugent - https://medium.com/@mark.nugent.iv/grouping-bitcoins-fractional-digits-an-idea-whose-time-has-come-22d9dad8ac51

**Comment by pavlenex** [comment]
A question from Slack:

> Hey all I have a question, how is this symbol used exactly? It’s not explained in the Open Source guide “₿” is it supposed to be the equivalent of the “$” sign?
