### ISSUE TITLE
Update header images in `Onboarding` chapter

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#610]
Current Onboarding images can be found [here](https://www.figma.com/file/qzvCvqhSRx3Jq8aywaSjlr/Bitcoin-Design-Guide-Illustrations-CO?node-id=263%3A918). These need to be updated to reflect the new structure as well as more accurately depict the more fluid nature of onboarding - some apps won't follow our steps in sequence so this should be reflected in the header image.

@sbddesign @GBKS said you had some ideas around how to tackle this?

**Comment by GBKS** [comment]
I'd keep the images to match the page sequence. There is specific rationale behind the order of pages, and I don't think people will feel forced to follow it just because of the header images.
