### ISSUE TITLE
Add ⚡ to `Case Studies` > `Daily spending`

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#615]
This page requires overhaul to add LN content as LN is for daily spending.

**Comment by sbddesign** [comment]
Here are some initial thoughts on updating the cash account / daily spending page:

📄 [First Draft](https://docs.google.com/document/d/15Ra-z9pTkywV-yN2UNpiLNljjQaCrzqVhC3QrFgP040/edit?usp=sharing)
