### ISSUE TITLE
Revise ⚡ to `Case Studies` > `Savings account`

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#616]
Revise if this page even needs Lightning content adding.

**Comment by sbddesign** [comment]
IMO, this page doesn't need any Lightning content. It seems pretty focused on a multi-sig wallet for performing on-chain transactions.
  
I could foresee a future situation where somebody might wish to submarine swap from a Lightning channel to  2-of-3 on-chain address, but I feel like that's a design problem for the Lightning wallet and not the multi-sig wallet.

**Comment by pavlenex** [comment]
Agreed, we can def close this one if others agree.

**Comment by GBKS** [comment]
Also don't think this needs any tweaks at the moment.
