### ISSUE TITLE
Revise ⚡ to `Case Studies` > `Upgradeable account`

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#617]

**Comment by sbddesign** [comment]
IMO, no Lightning updates are needed here.

The idea of an upgradeable account is interesting. I'll refer to [my comment](https://github.com/BitcoinDesign/Guide/issues/618#issuecomment-1011224839)s on #618:

> I'm not sure about having more than one private key responsible for one side of a Lightning channel. (Would it work? Has it been implemented?)

I'm not sure that (at this point in time) Lightning fits well into this multi-sig security model for the user.

**Comment by GBKS** [comment]
Could be a situation where the wallet starts as a Lightning wallet (based on a single-key on-chain wallet). Once the user has an amount that seems deserving of better security, an additional multi-sig wallet could be created to store funds that aren't used for daily spending. That leaves the user with two accounts, so not strictly an upgrade. Either way though, I think the idea is to allow users to effortlessly use a setup that fits their use, and we can probably provide some good guidance on how to think about this and design for it, independent of a specific scenario.

**Comment by Bosch-0** [comment]
I really like this concept, the term progressive sovereignty has been thrown around in the past which I think is a more 'bitcoin-esque' way to describe this. We should explore this concept in greater depth and maybe add content around it in various sections in the guide. Zeus is looking to explore a 'gamifying sovereignty' feature which is essentially the same. In essence, you give incentives to push people from a wallet like Phoenix to something like Zeus (though all within the same application).

**Comment by GBKS** [comment]
I propose not making any changes to this page right now. As @sbddesign wrote, it's not totally necessary, the page still holds up as is. We can get back to this with the bigger case study overhaul we discussed, and for now focus on wrapping up our Lightning update.

**Comment by Bosch-0** [comment]
Agree with @GBKS.
