### ISSUE TITLE
Create header image for `Getting to know your users` page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#620]
Currently using the old header images from the onboarding chapter: https://bitcoin.design/guide/designing-products/getting-to-know-your-users/

**Comment by toporas** [comment]
Hey guys,

I created a header img for the page but for some reason I'm not able to see the branch?
added the link to src in the description, you can find it here:
https://www.figma.com/file/eepTzz238Jkb5WAt5DTWw8/getting-to-know-your-users?node-id=12%3A1

Let me know if something doesn't seem right :)

**Comment by toporas** [comment]
@Bosch-0 - made the changes to the page itself but can't push for some reason, neither with ssh nor https.
Do I need to be authorised first?

**Comment by Bosch-0** [comment]
Sorry just seen these comments, looks like you got it working :) What was causing the issue?

**Comment by toporas** [comment]
No worries, thanks for reviewing it. :+1:   
It was on my side: I had cloned the repo without forking it first.
