### ISSUE TITLE
Reconsider framing of the "Case studies" section

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#622]
This came up during the [last jam session](https://github.com/BitcoinDesign/Meta/issues/216). "Case studies" might not be the name for [the section](https://bitcoin.design/guide/case-studies/).

Ideal is probably if we start from the top and figure out what the purpose of the section is.

For example, it could be renamed to "reference designs". Goal would be that designers/developers could find a design that is fairly close to what they are working on, and quickly dive deep into product specs, features, user flows, etc. The guide includes many individual pieces of content (like key management techniques) that can be implemented in various ways. A reference design would link many of these together to form a coherent whole, and add important considerations, unique flows, etc.

The case studies could also be matched to the [Personal finance](https://bitcoin.design/guide/designing-products/personal-finance/) categories we identified. This would unify the content a bit further.

A different content approach would be to create case studies from results of the Wallet Improvement Project. These could be built around wallets, features or user-flow (see [Built for mars](https://builtformars.com/case-studies/signing-up-to-cash-app)). This would open up the section to external content (meaning screenshots, analysis, etc of IRL projects). Additionally, we could add case studies of use cases that otherwise don't fit well into the guide, like wallets for kids, merchant interactions, etc.

What do you think?

**Comment by Bosch-0** [comment]
> A different content approach would be to create case studies from results of the Wallet Improvement Project.

100% this, I think the case studies currently shown should be re-purposed and relevant content added to other sections of the guide / potentially removed. This section should be focused on case studies where we apply the guide's content. Are we still planning on going with the "mega case study" structure? I think we should, and if so what's the point in a spending case study here when we have a "mega" spending case study (Onboarding, payments) that covers things in so much more depth. We can eventually make mega savings / progressive etc. case studies.

**Comment by GBKS** [comment]
Looking at Wikipedia:

> [Reference design](https://en.wikipedia.org/wiki/Reference_design) refers to a technical blueprint of a system that is intended for others to copy. It contains the essential elements of the system; however, third parties may enhance or modify the design as required. The main purpose of reference design is to support companies in development of next generation products using latest technologies. The reference product is proof of the platform concept and is usually targeted for specific applications. Reference design packages enable a fast track to market thereby cutting costs and reducing risk in the customer's integration project.

> A [case study](https://en.wikipedia.org/wiki/Case_study) is an in-depth, detailed examination of a particular case (or cases) within a real-world context. For example, case studies in medicine may focus on an individual patient or ailment; case studies in business might cover a particular firm's strategy or a broader market...

Those two terms seem very appropriate.

**Comment by Mogashni** [comment]
I like the terms Reference design (for the current case study section) and Case study (then for a longer more detailed UX approach; showing more of the UX research process/steps etc). Maybe showing how the principles from the design guide are implemented into the wallet being reviewed (during the wallet improvement project).

**Comment by GBKS** [comment]
I think we can consider this done. The guide now has a "Reference designs" title on the [landing page](https://bitcoin.design/guide/). With #752, the sidebar will also have this title. And #757 changes the last few spots in the text where we still refer to case studies.

Anything else we should do here?

**Comment by pavlenex** [comment]
Done in #757 and #752
