### ISSUE TITLE
Provide guidance for mobile UX background channel monitoring

### ISSUE THREAD

**Issue by moneyball** [BitcoinDesign/Guide#630]
LN channels need to be monitored to ensure channel peers do not try to close the channel with an old state and steal money. The window of time for a wallet to exact punishment is configurable but often 5-7 days*. As long as the mobile app is used by the user in that window, OR, has background tasks scheduled by the OS to monitor this, then the user is safe. However, the app is not run during this window, the user would be at risk of having funds stolen. To guard against this, a mobile wallet can do a few things:
1. Allow the user to configure and use 1 or more watchtowers
2. Schedule a notification with the mobile OS to be displayed after X amount of time that the mobile app is not run on the phone. This notification could warn the user they should open the app promptly.

An open design question is what should be the value of X relative to the N (eg 5 or 7) day window? Is 24 hours too short of period of time that could lead to too many notifications that either annoy or scare users? Perhaps an optimal value for X would be N minus 1 or 2 days? Such that if it is a 5 day window, a user is warned after 3 or 4 days if the mobile wallet was unable to monitor the channels?

One piece of data that would help answer optimize the guidance we give to builders would be to collect data on how often iOS and Android do NOT schedule a mobile app's background tasks after, say, 24 hours or 72 hours. If it is the case that there is a significantly greater chance of getting sufficient CPU time in 72 hours vs. 24 hours that would heavily suggest delaying a warning notification.

* For example, Breez uses 720 blocks, or about 5 days https://medium.com/breez-technology/the-only-thing-better-than-minimal-trust-is-none-at-all-34456f650332

**Comment by GBKS** [comment]
We should be able to come up with guidelines for the watchtower configuration. The exact scheduling and timing details would require technical validation by app devs, ideally under various conditions, different devices, etc. I am curious if this behavior is even consistent or if it largely depends on the context.

I am also curious how this works if the OS decides to uninstall the app. iOS does this with infrequently used apps (can be disabled via Settings -> App Store -> Offload unused apps) if it needs/wants space. Are background tasks still scheduled and run if the app is removed? I would assume not as the code is probably not on the device anymore. When this feature first came out, I ended up not seeing various messages from friends because iOS had offloaded the apps. They seem to have fixed this, but that is just my assumption from my own experience.

**Comment by moneyball** [comment]
By "uninstall the app" I think you mean kill the process. I'm told that even in this case, it is possible for an app to register for a notification if the app has not been active for N amount of time. Would be great to get verification of this and precisely what the APIs are on iOS and Android to be confident. Note that this API is distinct from whether or not apps get background task time.

**Comment by Bosch-0** [comment]
I don't see Breez's watchtower being of much benefit if all channels a Breez user has are with the Breez node (which is likely the case). The only person that can cheat the user is Breez so why would you use a watchtower also run by them? Would be ideal to have a third-party watchtower automatically used but also give the option to users to configure their own, progressive sovereignty and all, but knowing what a watch tower is, finding one to use, connecting to it is a big task for a novice user. 

> The exact scheduling and timing details would require technical validation by app devs, ideally under various conditions

Agree with this, figuring this out would be challenging without data. One idea could be to employ reverse spaced repetition where the notifications start of infrequent, say after 4 days of not using Breez, then become more frequent if the user does not address the notification, next is after 2, then 1 then 12 hours.

**Comment by GBKS** [comment]
@moneyball with offloading, iOS pro-actively removes the application code from the device (it keeps user setting). Those apps have a small cloud icon next to their name, as in the [following image](https://149493502.v2.pressablecdn.com/wp-content/uploads/2018/03/offloaded-apps-to-free-up-storage-space.jpg):

![](https://149493502.v2.pressablecdn.com/wp-content/uploads/2018/03/offloaded-apps-to-free-up-storage-space.jpg)

I have a lot of Bitcoin wallets on my phone that I tested but rarely use. Most of them are now offloaded. I am assuming that background tasks for those also don't run.

**Comment by moneyball** [comment]
Oh I see, thanks. I guess I don't consider that a top priority thing to address. More like what should be the guidelines for UX for a wallet that a user uses daily, or weekly, or monthly, but is not offloaded.

**Comment by GBKS** [comment]
I just created a PR to address this, see #798.

It looks like each channel has its own setting for the delay of a forced close. Seems like it would then be ideal if applications can be sensitive to these invididually with respect to notifying users (meaning there's no one best number we can give).

Not sure we should have a recommendation on the force close delay itself in the guide. I'd assume this really depends on the relationship of the channel partners (user - wallet provider, merchant - customer, exchange - exchange), channel purpose, amount of funds, etc, and also if watchtowers are available and set up. This could be a pretty lengthy discussion and write-up. What do you think?
