### ISSUE TITLE
Adopt lower case b for bitcoin

### ISSUE THREAD

**Issue by danielnordh** [BitcoinDesign/Guide#635]
Prompted by [this comment](https://bitcoindesign.slack.com/archives/C015856BDME/p1643396147867949) by @moneyball in Slack.

I suggest we move away from distinguishing the spelling between:
- Bitcoin - when talking about the technology
- bitcoin - when talking about it as 'money'

It achieves very little, and introduces unnecessary confusion for beginners and experienced people alike. 

Just taking an example from the work creating the guide, so many review comments stemmed from this artificial distinction, and creates unnecessary work for both the author and reviewer.

My proposal is simply to use lowercase bitcoin everywhere, unless it is the start of a sentence.

**Comment by Bosch-0** [comment]
Yep I agree, if extra context is needed other words could be appended - such as saying "bitcoin network" rather than "Bitcoin."

**Comment by GBKS** [comment]
Sounds good to me. If people keep getting hung up on this, then let's change it.

**Comment by pavlenex** [comment]
> My proposal is simply to use lowercase bitcoin everywhere, unless it is the start of a sentence.

ACK, I give up on this 😄 

One note, the [Technology Primer ](https://bitcoin.design/guide/getting-started/technology-primer/#is-it-bitcoin-or-bitcoin)would have to be modified accordingly as well.
