### ISSUE TITLE
Add restoring wallet user flows to `Backup & recovery` section 

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#638]
In #631, I added this prototype for a Lightning enabled daily spending wallet. There are 2 user flows outlined here for an automatic cloud backup restore as well as a manual restore.

@GBKS pointed out that we don't portray these user flows in the restore section. It would be worth adding them to the "[Restoring a wallet](https://bitcoin.design/guide/onboarding/restoring-a-wallet/)" section. Specifically, I'm proposing we add the following user flows from [this Figma document](https://www.figma.com/file/dXSeWwzKoVvS0Xm9VT9HuJ/Daily-Spending-Case-Study---Bitcoin-Design-Guide?node-id=43%3A3320):

- Restore wallet
- Restore from cloud backup
- Advanced - Manual restore

**Comment by Bosch-0** [comment]
Should tackle this as part of https://github.com/BitcoinDesign/Guide/issues/763

**Comment by Bosch-0** [comment]
Is this addressed in your PR you have up Stephen?

**Comment by sbddesign** [comment]
Yes!
