### ISSUE TITLE
Provide deeper guidance on 0 amount settings for Lightning invoices

### ISSUE THREAD

**Issue by moneyball** [BitcoinDesign/Guide#641]
Attached is my own personal testing of wallets with 0 amounts. It is a total mess! Muun and Phoenix default to 0 amount, yet most wallets give an error when using them, including Muun!

Hopefully wallets converge on supporting this so this matrix isn’t a mess, but in the mean time the design guide could help a product builder out.

1. Should a wallet support 0 amount receiving? (I think yes)
2. Should a wallet default to 0 amount receiving? (I think it depends on use case…but also needs to take into account the current mess of wallet support)
3. Should a wallet support sending to 0 amount invoices (ie let sender enter amount)? (I think yes, obviously…only reason we’re in this mess is due to an LND security bug that has been fixed but wasn't broadly communicated so the ecosystem is unclear on this)

https://bitcoin.design/guide/payments/request/#amount

![image](https://user-images.githubusercontent.com/326147/152592348-99c3ba60-4624-4203-93a6-03dadc4d0db7.png)

**Comment by Bosch-0** [comment]
Muun allows sending to zero amount invoices on android but not iOS. An issue already existed for this https://github.com/muun/falcon/issues/15 

Breez Issue existed from back in August for generating zero amount invoices, bumped the issue up for better visibility https://github.com/breez/breezmobile/issues/556

**Comment by Bosch-0** [comment]
Interesting comment from Breez on this https://github.com/breez/breezmobile/issues/556#issuecomment-1037222108

> Receiving zero amount invoices requires changes to the on-the-fly channel creation infrastructure.
