### ISSUE TITLE
Sat Symbol at bitcoinicons.com is incorrect

### ISSUE THREAD

**Issue by AndyRibetz** [BitcoinDesign/Guide#642]
**Describe your content request**

The Sat Symbol at bitcoinicons.com is asymmetrical and displays off its intended design. The Figma and downloadable zip also reflect this.

**Link to the page**
https://bitcoinicons.com (Satoshi V2)

**Why would you like to change the content?**
The current presentation is shoddy and confuses new viewers

**Suggestions**
Attaching proper SVG file here (I didn't find a PR to bitcoinicons.com)

![satoshi-v2](https://user-images.githubusercontent.com/83780625/152669773-8f981ab4-604c-453f-bb34-39fa2f042e9f.svg)

**Comment by GBKS** [comment]
There's already an issue for this [here in the Bitcoin Icons repo](https://github.com/BitcoinDesign/Bitcoin-Icons/issues/79). You can access that repo directly from [bitcoinicons.com](https://bitcoinicons.com).
