### ISSUE TITLE
Create a banner image for `Requesting bitcoin` page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#645]
**Request the visual**

Currently the requesting bitcoin page has no banner image.

**Link to the page**

https://bitcoin.design/guide/payments/request/

**Visual Type**

Banner image

**Illustration guidelines**

If you're a contributor looking to tackle the issue, you can [preview our illustration guidelines](https://bitcoin.design/guide/contribute/illustration-guidelines/).

**Comment by pavlenex** [comment]
Hey @IamSanjana you can upload it here to get some early buy in. You can also submit a pull request if you know how, here's a tutorial. https://bitcoin.design/guide/contribute/propose-a-change/ You can alternatively post a figma link and someone may be able to submit it on your behalf.

**Comment by IamSanjana** [comment]
@pavlenex  This was helpful, thank you!
