### ISSUE TITLE
Revise the projects page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#649]
The [projects page](https://bitcoin.design/projects/) needs a quick update.

- Add the "Wallet Design Improvement Project" (consider whether to rename this to "Bitcoin Design Sprints" or similar, and create a sub-page for it)
- Create a [JoinMarket](https://github.com/joinmarket-webui/joinmarket-webui) collaboration issue and add it to this page
- Create a [Bitcoin Core collaboration](https://github.com/BitcoinDesign/Bitcoin-Core-App) issue and add it to this page
- Specter is not active anymore. Remove it or talk to the team and see if they need anything else? Do we keep non-active collaborations on this page? I'd argue this page is for active collaborations for people who want to contribute to projects now. Historical collaborations can still be accessed via the [linked board](https://github.com/BitcoinDesign/Meta/projects/2).

Anything else we should add or change here?

**Comment by Bosch-0** [comment]
Bitcoin Design Sprints sounds like something you do as part of a project, not a project itself, NACK on that name. 

PR is open for this https://github.com/BitcoinDesign/Guide/pull/665

**Comment by pavlenex** [comment]
@Bosch-0  We literally only do design sprint, how is that not the project itself?
It's a good branding and really gives a wider picture of what WIP project will become, people doing these initiatives on their own, regardless if they're helping a wallet or a different project.

**Comment by Bosch-0** [comment]
I'd disagree, the project seems to cover everything in the first diamond and partially overlaps with the analysis portion of the second with creating issues on the wallets GitHub.

![image](https://user-images.githubusercontent.com/55287964/154020554-6745b7a7-1f15-4a51-bcd0-e6c298699cb5.png)

Bitcoin Design Sprint is also very open ended, it really doesn't encapsulate what the project is doing. Design sprints for what? 

Design is also iterative, you don't just do a sprint and call it a day. You constantly go back and revise through the above diamond.

**Comment by pavlenex** [comment]
> Bitcoin Design Sprint is also very open ended

Which is exactly why we're renaming it. 

The wallet reviews are just kicking things off and opening what is hopefully a whole new initiative of community members using their learned skills and conducting design sprints for whatever there's a need for.

I think you should join one of the calls before giving a comment, the goal is to hopefully have iterative sprints. It's up to community members to venture into initiatives on their own.

**Comment by Bosch-0** [comment]
I thought it was being renamed to Bitcoin Design Sprint? 

Well it's confused me so I'm sure it would confuse others.

They are at 2AM in the morning otherwise I would attend, I've been watching the recordings / following everything on FigJam so I am in the loop.

**Comment by pavlenex** [comment]
It's already renamed. Wallet Improvement Project to `Bitcoin Design Sprints` because:
- Wallet improvement project doesn't mean anything to a new designer so better branding and communicates a process that designers are already familiar with
- The wider goal of the project is to educate designers on how to conduct sprints to solve problems in Bitcoin, problems aren't only in the "wallets" area. Hopefully in a while we'll have people conducting sprints independently, solving problems creatively regardless of the product.
