### ISSUE TITLE
Revise the `Contribute` page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#650]
[This page](https://bitcoin.design/contribute/) is all text with lots of bullet lists, does not feel like contributing is a fun time. Let's think of ways we can make this entry point to participation a bit more appealing.

Here's one idea, providing more practical entry points to what is happening.
<img width="881" alt="Slice 1" src="https://user-images.githubusercontent.com/695901/153391297-25923ac3-7df0-4ca3-afd3-f43926ff31e1.png">

What else can we do?

**Comment by IamSanjana** [comment]
Is there a need to make changes in contents of the page too?

**Comment by IamSanjana** [comment]
> We can make the page less congested, including the information drop downs 
draft idea:

![Screenshot (10)](https://user-images.githubusercontent.com/85779625/155693568-fceaeafc-e90d-416f-b002-49b8939ad1d4.png)

**Comment by GBKS** [comment]
@IamSanjana that is definitely visually less busy, it also hides a lot of information. As a user, I need to manually explore the dropdown content, there's almost more friction now between me and finding an interesting starting point.

What I am hoping we can do is to highlight the 4-6 most important options at the top as easy starting points. So if a user wants to read through all the options, they can still do that further down the page. If they want just the most important links, they are easy to find at the top. What do you think of that?

**Comment by IamSanjana** [comment]
Fair enough, your point makes sense!
We need to filter out the important tasks for an easier flow and active responses, got it. Will think in that direction 👍
