### ISSUE TITLE
Create a page for handling Contacts in wallets for P2P sending

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#652]
Whether it's a phone numbers a mailing address, most people rely on contacts on their devices to abstract away such information behind names and profile pictures. Bitcoin and Lightning identifiers are also quite complex, and a good system for managing contacts sounds like an appropriate solution to simplify their usage.

This is something that has been discussed since the start of the guide, so let's put together a page that covers this topic.

References:
- [Requesting entry points](https://bitcoin.design/guide/payments/request/#requesting-entry-points)
- [Payment entry points](https://bitcoin.design/guide/payments/send/#payment-entry-points)
- [Bitcoin UI Kit screens](https://www.bitcoinuikit.com/screens/flow/contacts)

Extracting a few bullets from #582:

- Contacts aren't used in Bitcoin applications yet but they seem evident to include in any type of payments / finance app. We should be designing for the future here.
- Explores how contacts UI should be designed and used.
- @johnsBeharry has done loads of work around contacts [here](https://bitcoin-contacts.netlify.app/)

**Comment by Bosch-0** [comment]
ACK

We should make this page apart of the Daily spending wallet chapter: https://github.com/BitcoinDesign/Guide/issues/655

**Comment by GBKS** [comment]
Yep, it ties a lot of things together between sending, receiving and activity. Also had a [conversation](https://bitcoindesign.slack.com/archives/C014J9ZKXB4/p1644988442314839) around this today around usefulness and trustworthiness of Lightning node aliases. Will start tackling this issue next as I already have a lot of screens in the Bitcoin UI Kit I can use as a foundation.

**Comment by Bosch-0** [comment]
Awesome! Have a lot of thoughts around this but I'll wait for your PR for feedback :)
