### ISSUE TITLE
Create a `Design challenges` page in the `Resources` section

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#657]
Yackni [posted](https://bitcoindesign.slack.com/archives/C014BHV38EA/p1643204243582489) a really cool self-imposed design challenge ([Figma](https://www.figma.com/community/file/1070445418194003799/Bitcoin-design-challenge-%E2%9A%A1%EF%B8%8F)) in the Slack recently. He wanted to sharpen his UX skills and was looking for a bitcoin-specific problem to solve. This is a great idea, so how about we create a "Bitcoin design challenges" page in the [Designing bitcoin products](https://bitcoin.design/guide/designing-products/introduction/) section?

This could be a good resources for self-learners, but can also be handy for efforts like [Summer of Bitcoin](https://www.summerofbitcoin.org), which ask applicants to do design/development challenges during the application process.

A few of us collaborated in a [Google Doc](https://docs.google.com/document/d/1JCQs20VfaiNFASDj6rSOG8pbGpCA7mqUtARxhalexGA/edit?usp=sharing) to flesh this out further. From this, I put together a [cleaned-up doc](https://docs.google.com/document/d/1W3--6U0YbrlYIXardwVkFlYOtzlLGe7wWyhWwfmG4KA/edit?usp=sharing) with the copy that might go on this new page. Based on feedback on this issue and the doc, I'd refine this a little bit further and then get a PR ready.

What do you think?

**Comment by Bosch-0** [comment]
This would be included in the new Resources section: https://bitcoin.design/guide/resources/
