### ISSUE TITLE
Add `Progressive Sovereignty` principle to `Principles` page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#658]
A principle we should have for the guide, and already do in many ways, is the idea of designing Bitcoin applications to be _Progressively sovereign_

**What is a progressively sovereign bitcoin application?** 

To put it simply, it's making flexible bitcoin applications that allow users to become more sovereign with their bitcoin and data when they are ready to do so. 

An example is Breez: It is a pretty basic wallet initially but if users want to they can minimize their trust from Breez the LSP and connect to their own Neutrino node and (coming soon) connect to different LSPs. 

Could even take this a step further and allow the wallet to be a Lightning node remote (like Zeus) if the user wants to do that. We are planning on attempting to 'gamify' this process of making users more sovereign once Zeus has mobile node functionality. 

We should instill this principle throughout the guide and ensure users aren't getting put in a walled garden that may over time slowly erode their sovereignty over their bitcoin.

**Comment by GBKS** [comment]
Isn't that already covered in [Interoperability](https://bitcoin.design/guide/designing-products/principles/#interoperability)?

**Comment by pavlenex** [comment]
We do a brief mention of both in `Self-custody` and `Security`.

![Screenshot 2022-11-22 at 11 41 35](https://user-images.githubusercontent.com/36959754/203293712-f5f8c15e-406c-4f0b-a882-d85ef1175c30.png)


If you feel we can add more, let's revisit and re-open the issue.
