### ISSUE TITLE
Update UX guidance to recommend single QR code for receiving

### ISSUE THREAD

**Issue by moneyball** [BitcoinDesign/Guide#663]
https://bitcoin.design/guide/payments/request/

Requiring users to choose a tab between "lightning" and "on-chain" is a horrible UX. Many users do not understand. Most should not need to understand. Most should not need to decide.

Let's recommend a single QR code using BIP21 + BOLT11 (switching to BOLT12 once available). This includes an on-chain address and a LN invoice. On-chain only wallets simply make the payment to the on-chain address. LN wallets can default to the LN invoice and use the on-chain address as a fallback if the LN payment fails.

**Comment by GBKS** [comment]
This is related to #653.

**Comment by Bosch-0** [comment]
Just some extra context

From Johns: https://github.com/peakshift/bitcoin-ux/blob/master/payments/qr-codes.md
From me: https://www.youtube.com/watch?v=f7QDlsiFeB4
