### ISSUE TITLE
Minor improvements on Activity Page

### ISSUE THREAD

**Issue by moneyball** [BitcoinDesign/Guide#664]
Love the speed of this community! As I was typing this feedback for #662 it was merged! :) So I'll open a new issue to see what @GBKS and others think to improve the new Activity page.

@GBKS thank you for being so responsive here! I looked at your preview and have this feedback:
* The purely technical perspective...just to be clear the guide is not recommending that be used right? Is it clear enough that it is more educational vs. what is recommended? For example, showing the LN invoice string IMO shouldn't be what we recommend on the Activity page.
* Should we include a generic icon in the activity page screenshot we're actually recommending so that guide users know that that icon is recommended (as a fallback)? I think we need to show at least one example that doesn't have rich data such as payee name and logo (as it will be common to not have this info).

**Comment by GBKS** [comment]
I'm assuming that apps have to support both scenarios. There may be no useful information available other than what's on-chain or in a bare-minimum Lightning invoice. Or a user may have added lots of useful meta data (or it came with the invoice, payment link, etc). Realistically, what users see might often be in the middle based on their unique usage patterns and how much they care about keeping things orderly (and how easy the app makes that).

Added some thoughts on the generic icon [here](https://github.com/BitcoinDesign/Guide/issues/660#issuecomment-1039943709).

As far as showing the LN invoice string, this could also replaced with `Sent` or `Received`. Showing parts of the invoice or address provides some text-based identifier users could try to work with (like how invoice numbers and payment reference codes are used in traditional payments). With `Sent` or `Received`, they can still use the amount and send date to identify a payment (or just go in and add a proper description, contact, etc). But the question to "has invoice XYZ been paid?" gets more tricky. Alternatively, that link of text could just be hidden altogether, so the date/time would become the primary label.

**Comment by moneyball** [comment]
Ok. I think the LN invoice string only belongs in a Details page as shown later in the Activity section of the guide. So if you agree, remove the LN invoice string from the 2 UI mocks for Activity pages.

I still think it makes sense to show an example UI mock that mixes both the rich name/logo for some items and other items with no name/logo, as that is what real world apps will look like.
