### ISSUE TITLE
Add a `User is offline` error state to `Sending bitcoin`

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#673]
Receiving wallets needing to be online is a major UX issue with Lightning that is unlikely to get resolved in the short-term in a custodial / trust-minimized way.

One way design can help remediate this problem somewhat, as well as educate users of this detail, is by offering a error state when a user attempts to pay a node that is offline.

It could read something like: "The person you are trying to pay appears to be offline, try contacting them so they can come online and receive your payment." 

This error will likely become much more common when things like BOLT12 roll out and users are attempting recurring payments to a reusable payment request.

**Comment by moneyball** [comment]
I also think offline/online vocabulary is not intuitive to people in this context. If you asked the average person which states their mobile wallet are or are not online they'd likely have no clue. Perhaps something closer to "try contacting them and suggesting they open their wallet."

**Comment by Bosch-0** [comment]
> "try contacting them and suggesting they open their wallet."

Much better suggestion!

**Comment by GBKS** [comment]
Addressed this in #680. Let me know how that looks.
