### ISSUE TITLE
Remove grey background on images

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#674]
Currently when using single images (not gallery) a grey background is shown (image on left below). It looks much cleaner to remove this (image on right).

Simply removing the -background does not suffice. Making the -background property white for these single use image instances would suffice. 

![image](https://user-images.githubusercontent.com/55287964/154619236-e63c8a7c-87ab-4f50-b10c-b671a7510011.png)

**Comment by Bosch-0** [comment]
Maybe on the gallery images too... Maybe just a personal preference but the background is unnecessary visual clutter. 

![image](https://user-images.githubusercontent.com/55287964/154620415-63016483-c0c2-4691-b700-7a34b9a260f8.png)

**Comment by GBKS** [comment]
I am not totally sold on this, for a few reasons:

- The light background provides extra contrast for people with less-than-optimal eye sight. Don't think the light shadow is enough on its own. White-on-white is tricky.
- It brings some extra visual structure to pages. Looks a bit too ragged at times.
- One of the initial ideas was to allow different background colors to let writers/designers be more expressive with this (see [here](https://www.figma.com/file/K5ahSqVzoMVBuhT5hAVRJr/bitcoin.design?node-id=33%3A875)). Been thinking about adding this in.

I don't think it's needed for dark images (and it is optional there), but screens that are mostly white, with white edges, need solid contrast.

**Comment by Bosch-0** [comment]
- Could just make the shadow less blurred for improved contrast.
- I'm not a fan of having custom colors, could make the guide look very cluttered / inconsistent.

**Comment by GBKS** [comment]
> I'm not a fan of having custom colors, could make the guide look very cluttered / inconsistent.

Could be just an option for black or white. I think it would be useful for pages like the case studies or reference designs that might intentionally use a more expressive style.

**Comment by peanutbutter003** [comment]
Hi, is there an update here? If yes, seems like an easy UI fix- I'd like to take it up!
@Bosch-0 @GBKS
