### ISSUE TITLE
Create a `Liquidity` page in `How it works` section

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#685]
As discussed in last weeks jam session @sbddesign mentioned a lot of designers and new people in general have a hard time wrapping their head around Lightning liquidity. We suggested in the call to create a Liquidity page that covers this.

This would likely be included as part of a `How it works` chapter of the guide we will be introducing at a later date.

**Comment by sbddesign** [comment]
On it.

**Comment by sbddesign** [comment]
[Rough draft here](https://docs.google.com/document/d/1tIk_Vv68FpEy6xVjbo5rWUuKygBxNlQAJu8yufSg7Kg/edit?usp=sharing)

My thinking is that we explain conceptually how liquidity works between nodes. Then, we talk about how this should be simplified for the user. We can mention specific techniques, but direct people to the LSPs page to learn more about these specific techniques.

**Comment by sbddesign** [comment]
Here is an updated draft, where I have taken it beyond just the outline and fleshed it out writing and images.

[Read latest draft here](https://docs.google.com/document/d/1k8CURJkzIjXHM2xpVxK382_ZTwkpE6q7LGFiDR3Bvqw/edit?usp=sharing)
