### ISSUE TITLE
The Ongoing Development of Bitcoin: A header image proposal for bitcoin design website

### ISSUE THREAD

**Issue by Susritachatterjee2020** [BitcoinDesign/Guide#688]
Hello everyone. I want to contribute the header for the bitcoin design website. Currently I am an undergraduate student and I am in the proposal round of "Summer of Bitcoin". I am slowly understanding bitcoin and its value. I want to contribute as per my understanding. Any type of feedback is most welcomed. 
Thank you
![Bitcoin Header Design](https://user-images.githubusercontent.com/60474018/156898417-6058b146-751d-461e-99a0-813b0b902fff.png)
### Figma Link: [Click here](https://www.figma.com/file/cJASW3oX4uKVw5T9D0yh4U/The-Ongoing-Development-of-Bitcoin?node-id=626%3A408)
![Bitcoin  (1) 2](https://user-images.githubusercontent.com/60474018/156898493-40b65b54-1001-4421-8001-77b66298f3a9.png)
### About the theme
My idea of making this header design is to showcase the cumulative efforts of developing bitcoin. Its just the visual representations of all developers and designers who are contributing for Bitcoin.

**Comment by Bosch-0** [comment]
Hey @Susritachatterjee2020, great stuff! Left a few comments on the Figma file - do you need help opening a PR for this? We have a small how-to for this [here](https://github.com/BitcoinDesign/Guide/blob/master/submit-header-design.md). Happy to do it for you if so :)

**Comment by Bosch-0** [comment]
LGTM, will get one more set of eyes then I can open the PR for you :) @GBKS do the honors? 

One minor thing could the CTA be this orange #F7931A

**Comment by Susritachatterjee2020** [comment]
Hi! I have updated the figma page with all the changes. Please have a look.

**Comment by Bosch-0** [comment]
Will get a PR up for this today, thanks again!

**Comment by Susritachatterjee2020** [comment]
Thank you

**Comment by GBKS** [comment]
I like the idea. The text looks a bit faded since it's all grey. Maybe could use a hint of color (doesn't have to be overpowering).

The image in Figma looks a little low resolution. Do you have a version of the illustration that is twice the pixel size? We would need that for export for retina screens.

**Comment by Susritachatterjee2020** [comment]
![Bitcoin  (375 × 375 px)](https://user-images.githubusercontent.com/60474018/159071418-ba066d67-3d7c-4271-ae44-6ef7af470433.png)
![Bitcoin  (720 × 720 px)](https://user-images.githubusercontent.com/60474018/159071428-f86bfd9d-012c-4d74-83a0-3f8f774364d5.png)
Hi! I have increased the resolution of the images.

**Comment by GBKS** [comment]
@Susritachatterjee2020 thanks for making the update. I implemented the theme and created a pull request. You can review it at [this preview link](https://deploy-preview-708--sad-borg-390916.netlify.app/). Note that the banner rotates randomly through all themes, so you may need to click "Next" a few times to see yours. Let me know how it looks (desktop and mobile) and if there are any changes you'd like to make.
