### ISSUE TITLE
Add `Users contact card` to `Contacts` page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#696]
The contacts page currently does not have any mention of how an application would deal with the users own local contact card, it only covers creating and dealing with contact cards of others.
 
 This being the place the user could add their own profile image, store their various addresses (reusable payment requests), other meta data (notes) and share this contact card with other people. Below is an example from Zeus - the contacts list being on the left and the users local contact card on the right.

![image](https://user-images.githubusercontent.com/55287964/157584948-1b013ede-fe95-4d3b-89d6-b988e9b2e83d.png)

**Comment by GBKS** [comment]
I can take this one on as a follow-up to my other work on the page.
