### ISSUE TITLE
Add ability to watch videos locally in the guide

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#701]
To make the guide more accessible, we will looking to add video content throughout in 2022. A first step to take is adding the ability to embed and watch videos locally in the guide  - currently we can embed a video image but the user is directly externally to watch it.

A good first video suggestion we could add would be [Hello bitcoin - Episode 1](https://www.youtube.com/watch?v=oubZGyDY4Dc) to the top of [Why bitcoin is unique](https://bitcoin.design/guide/getting-started/why-bitcoin-is-unique/) page as the content is very similar. 

Would you be okay with this being in the guide @ConorOkus ?

**Comment by ConorOkus** [comment]
Yeah if enough people think that's a good place for the video I'm very happy for it to be there, but linking out to it might be better to avoid third-party tracking issues.

I'm not sure if we need tons of videos directly embedded in the guide, but I'd love to see shorter videos that are based on pages in the guide, we could almost have a video version of the guide. That is each page has its own shortish video with an overview of the content and if appropriate some sample designing. 

A Design Guide playlist could be cool and good for discoverability.

**Comment by GBKS** [comment]
For the "Why bitcoin is unique" page, we should add a list of helpful resources (independent of any videos). Some ideas:

- [Hello Bitcoin](https://hellobitco.in)
- [Bitcoin only](https://bitcoin-only.com)
- [Bitcoin.org](https://bitcoin.org/en/you-need-to-know)
- [Getting started with Bitcoin](https://www.lopp.net/bitcoin-information/getting-started.html) on lopp.net

Probably some more good ones out there.

**Comment by sbddesign** [comment]
Videos could be cool. I'm personally more of a reader myself, but video is a powerful medium that's very effective. A lot of things can click for people when they see it in a video.

If we want to have videos on the site but avoid using YouTube and similar services, then we may need to consider how the videos are hosted. I'm handy with setting up these kinds of things, but we would need to consider a CDN or object storage so as not to clutter the repo with large video files.

**Comment by GBKS** [comment]
I added various videos (including the Hello Bitcoin one mentioned above) via the #877 PR. Hope that addresses this issue.

**Comment by Bosch-0** [comment]
Yep I'd say it does, closing this
