### ISSUE TITLE
Favicon not being used for site

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#702]
Unsure if this is something to do with my local setup but the new favicon only appears for me when I compile the site locally. The live site still uses the orange circle.

Using Firefox. 

Image for reference, live site is left my local copy is right.

![image](https://user-images.githubusercontent.com/55287964/158781551-5e761963-f53e-4b30-bb25-4e53be5d0758.png)

**Comment by GBKS** [comment]
I reviewed the icon files, and they are all correct. 

My Firefox shows the icon correctly. Do you have a custom theme or any other add-ons that might affect this?

**Comment by Bosch-0** [comment]
> My Firefox shows the icon correctly. Do you have a custom theme or any other add-ons that might affect this?

I have loads of add-ons and sometimes things like this don't work properly, I'd assume this is just on my end. Will figure out what is causing this and report back.
