### ISSUE TITLE
🎨 [Guide Re-org] - Update site navigation menu

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#711]
Idea: Have two navigation menus when clicking on “Guide.” Second would be below the main nav and focus on primary Guide sections. It would also sticky when scrolling similar to [Apple’s Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/)

This is an idea that came out of our [brainstorming session](https://docs.google.com/document/d/15sw-45Nxuhw-1G0WsEM4Nv4CO4MNzMsrna13cfXYjGE/edit#heading=h.x28s45jtix44) on re-organizing the Guide content. I think the idea here is that once the user gets into the Guide, we should provide some more contextually relevant navigation aside from just "Guide", "Contribute", "Calendar", etc.

Is this an idea worth implementing? If so, what content should we promote to this nav menu?

Samples below:

![Screen Shot 2022-03-22 at 12 40 33 PM](https://user-images.githubusercontent.com/2414177/159530659-80c75678-23e4-4c13-868e-8d8089201f6c.png)

![Screen Shot 2022-03-22 at 12 40 44 PM](https://user-images.githubusercontent.com/2414177/159530664-a9b4cf7c-5a84-4721-83b1-743c7aac21bf.png)

**Comment by GBKS** [comment]
TBH, I find this extra nav bar in the Apple site confusing and unnecessary. Those options could as well be in the sidebar.

**Comment by Bosch-0** [comment]
Yeah it would only be useful if the sidebar was hidden imo

**Comment by GBKS** [comment]
Seems like all agree that we don't want this. Will close this issue. Can open up a new one if it the idea warrants further exploration.
