### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#713]
The search capability is sub-par on the Guide. Results are not always the most relevant. The goal of this issue would be to improve the quality of search and have it provide more relevant results. This is an idea that came out of our [brainstorming session](https://docs.google.com/document/d/15sw-45Nxuhw-1G0WsEM4Nv4CO4MNzMsrna13cfXYjGE/edit#heading=h.x28s45jtix44) on re-organizing the Guide content.

## Ideas
- Test [Algolia](https://www.algolia.com/) or another third-party search provider for more sophisticated results (current search uses basic matching only, does not use a “relevance” sorting)
- Idea: Chapter overview pages have search bars that only look for content within that chapter. Helps simplify results / be more specific.

How do you feel about search on the Guide? Do you ever try to use it? Would it be useful if the search were improved? What's the best way to implement this?

**Comment by pavlenex** [comment]
Closing, in favor of #846
