### ISSUE TITLE
🎨 [Guide Re-org] - Update `Case studies`

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#716]
Rename “Case studies” to “Reference designs”. These are blue prints of specific products or UX solutions the community has come up with.

This is an idea that came out of our [brainstorming session](https://docs.google.com/document/d/15sw-45Nxuhw-1G0WsEM4Nv4CO4MNzMsrna13cfXYjGE/edit#heading=h.x28s45jtix44) on re-organizing the Guide content.

**Comment by GBKS** [comment]
For background on the use of the term "reference design", see [this discussion](https://github.com/BitcoinDesign/Guide/issues/622#issuecomment-1015396338).

**Comment by pavlenex** [comment]
Is this issue simply to rename without any other restructuring?

**Comment by Bosch-0** [comment]
For now yeah, I think we create a section called case studies once we have some content to put in their (Say from the Blixt design sprints).
