### ISSUE TITLE
🎨 [Guide Re-org] - Improvements to reference designs 

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#717]
Base structure of “Reference designs” on example of coding tutorials. Intro and end-result at the top, then step-by-step walkthrough, then the full final “deliverable”. For after #716 is closed.

Also, it would be good to update some of the reference designs to match the Daily Spending case study.

This is an idea that came out of our [brainstorming session](https://docs.google.com/document/d/15sw-45Nxuhw-1G0WsEM4Nv4CO4MNzMsrna13cfXYjGE/edit#heading=h.x28s45jtix44) on re-organizing the Guide content.

**Comment by sbddesign** [comment]
I can help with this one. While the integration into the Guide itself should wait until the [preceding milestones](https://github.com/orgs/BitcoinDesign/projects/2/views/4) have been hit, we could get a jumpstart on the actual Figma work.

**Comment by Bosch-0** [comment]
I removed https://bitcoin.design/guide/case-studies/cloud-backup/ in https://github.com/BitcoinDesign/Guide/pull/739 as it isn't really necessary with the mega reference design daily spending wallet. We should add a 'reference design' to the end of daily spending wallet though that will likely re-purpose some of this pages content.

**Comment by Bosch-0** [comment]
This would probably be better broken down into three separate issues, it isn't really re-organizing, it's more re-working content.

- One for savings wallet
- One for upgradeable account
- One for shared account

**Comment by GBKS** [comment]
As discussed in [jam session #24](https://github.com/BitcoinDesign/Meta/issues/260), I split this issue into #777 and #778. I did not create one for the "Savings wallet" reference design for now, as that has already been revised previously.
