### ISSUE TITLE
🎨 [Guide Re-org] - Consolidate `Onboarding` and `Payments` into the `Daily Spending Wallet` reference design

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#718]
Move the pages in “Onboarding” and “Payments” into the “Daily spending wallet” reference design.

- First use
- Assisted funding (Renamed from “Funding a wallet”, refocused on spending wallet that use LSPs)
- Manual funding (extracted from above page, focuses on funding a spending wallet without a LSP)
- Backup (renamed from “Backing up a wallet”)
  - Automatic cloud backup
  - Manual backup
- Requesting
- Sending
- Receiving (split out from the Requesting page, [issue 691](https://github.com/BitcoinDesign/Guide/issues/691))
- Activity
- Contacts
- Protecting a wallet
- Restoring a wallet
- Reference design

This is an idea that came out of our [brainstorming session](https://docs.google.com/document/d/15sw-45Nxuhw-1G0WsEM4Nv4CO4MNzMsrna13cfXYjGE/edit#heading=h.x28s45jtix44) on re-organizing the Guide content.

**Comment by Bosch-0** [comment]
This shiuld be done a long with https://github.com/BitcoinDesign/Guide/issues/721

**Comment by sbddesign** [comment]
> This shiuld be done a long with #721

Agreed

**Comment by Bosch-0** [comment]
Some other suggestions:

Rename `Backups` to `Backup & recovery` and put restoring a wallet in this section - these two concepts are heavily interconnected and are better discussed in parallel. 

I'll be addressing the funding a wallet stuff after we finish with the re-org

Rename `Protecting a wallet` to `Security`
