### ISSUE TITLE
Reconsider guide section landing pages

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#723]
- Idea: After larger restructure, reconsider each one individually and think about how they can be more effective - make similar to overview (more visual navigation) page but just for that chapter?
- Idea: Chapter overview pages have search bars that only look for content within that chapter. Helps simplify results / be more specific. (Related to #713).

This is an idea that came out of our [brainstorming session](https://docs.google.com/document/d/15sw-45Nxuhw-1G0WsEM4Nv4CO4MNzMsrna13cfXYjGE/edit#heading=h.x28s45jtix44) on re-organizing the Guide content.

**Comment by Bosch-0** [comment]
Pages this would be for:

- https://bitcoin.design/guide/getting-started/introduction/
- https://bitcoin.design/guide/getting-started/introduction/
- Daily spending wallet (once https://github.com/BitcoinDesign/Guide/pull/739 is merged)
- One for Reference designs (once https://github.com/BitcoinDesign/Guide/pull/740 is merged)
- One for case studies (once we have this section live)
- https://bitcoin.design/guide/how-it-works/
- https://bitcoin.design/guide/contribute/

**Comment by GBKS** [comment]
As discussed above, and in jam session #24, this task should be split into multiple issues. I created the following ones:
- #779 
- #780 
- #781 

Did not create one for "Design resources", as this page only shows two links at the moment. Also did not create one for "Contribute to guide", as we just had an issue on this with #650. Revising the one for the daily spending wallet should be done in [milestone 16](https://github.com/BitcoinDesign/Guide/milestone/17).
