### ISSUE TITLE
Guide re-org milestone issue tracker

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#725]
To avoid endless merge conflicts, we should tackle some of the issues in [Milestone #15](https://github.com/BitcoinDesign/Guide/milestone/16) in a specific order. This issue suggests an order and includes a to-do list we can work through one by one.

Merge conflicts happen when multiple PRs propose changes to the same files (or lines of code). This is likely to happen with this re-org, due the amount of cross-linking in the content.

Content restructuring (do these in order):

- [x] #720 
- [x] #719 
- [x] #714 
- [x] #715 
- [x] #718 
- [x] #721 
- [x] #726  
- [x] #716 
- [x] #717 
- [x] #723 

Other:

- [ ] #713 

Ideas (decide whether to do them and how):

- [x] #711 
- [x] #712 
- [ ] #722 
- [ ] #724

Feel free to propose changes to this sequence.

**Comment by Bosch-0** [comment]
I reckon we could wrap this milestone up when https://github.com/BitcoinDesign/Guide/issues/716 is done. All the remaining issues are more content changes, not so much content re-orgs.

**Comment by GBKS** [comment]
I think `re-org` has just somehow become the shorthand for this effort, but the big idea was to re-think the guide experience which is more broad. So I wouldn't focus too much on that term.

I am OK with this though. #717 and #723 could be split across multiple issues, and #724 could be also be pretty big thing on it's own. We also discovered a bunch of smaller tasks we may want to do first. So if we want to create a new milestone and re-prioritize, happy to do that.

**Comment by GBKS** [comment]
We discussed this milestone in [jam session #24](https://github.com/BitcoinDesign/Meta/issues/260). The remaining tasks have been lingering for a bit, some of them were not actionable and had to be split up, etc. Did some re-organizing and clean-up, we'll close this issue, and tackle the remaining (and new) tasks in upcoming milestones.
