### ISSUE TITLE
🎨 [Guide Re-org] - Revise the guide landing page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#726]
The page is not as effective as it should be at providing entry points to the whole guide for various user types.

Suggested changes based on this [example design concept](https://www.figma.com/file/g3psdWFFRzGgyQqZjLxth9/Bitcoin-design-guide-nav-rethinking?node-id=1%3A262):
- Remove header image or reformat so that it takes up less space in order to move content further up (keep image as link preview)
- Add search box on this page
- Add reference design section with larger, more visual previews of (formerly called) case studies
- Add “How it works” section with links to all sub-pages
- Add “Resources” section with links to 2-3 sub-pages
- Add “Contribute” section
- Decide whether to keep sidebar nav or remove it
- Page copy should allow different user types to identify relevant sections to them, and highlight the most important starting points.

This is an idea that came out of our [brainstorming session](https://docs.google.com/document/d/15sw-45Nxuhw-1G0WsEM4Nv4CO4MNzMsrna13cfXYjGE/edit#heading=h.x28s45jtix44) on re-organizing the Guide content.

**Comment by Bosch-0** [comment]
> Decide whether to keep sidebar nav or remove it

We should make it closed by default by can be opened with a toggle - I personally would use the sidebar more.

**Comment by GBKS** [comment]
So only on the guide landing page would you have it closed by default and an option to expand it?

**Comment by sbddesign** [comment]
Yes. The sidebar nav is pretty useful. Assuming the only reason we don't show it on landing is just to keep it tidier?

**Comment by GBKS** [comment]
Not a fan of different behavior of the sidebar across different pages. Let's say you start on the guide intro page, and the sidebar is collapsed. Then you click around some pages, and it's expanded. Then you go back to the guide intro page, and it's collapsed again? Like a cookie but only for this page? Let's have this behave consistently.

**Comment by sbddesign** [comment]
> Not a fan of different behavior of the sidebar across different pages. Let's say you start on the guide intro page, and the sidebar is collapsed. Then you click around some pages, and it's expanded. Then you go back to the guide intro page, and it's collapsed again? Like a cookie but only for this page? Let's have this behave consistently.

Let's say you start on the guide intro page, and the sidebar in't there. Then you click around some pages, and it's there again. Then you go back to the guide intro page, and it's not there again? Like a commented out jekyll include but only for this page? Let's have this behave consistently.
