### ISSUE TITLE
Create a banner image for the `Design source files` page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#735]
**Request the visual**

Hello, I would like to request a visual for the design source files section of the guide.

**Link to the page**

https://bitcoin.design/guide/resources/design-files/

**Visual Type**

Header banner image. 

**Illustration guidelines**
If you're a contributor looking to tackle the issue, you can [preview our illustration guidelines](https://bitcoin.design/guide/contribute/illustration-guidelines/).

**Comment by GBKS** [comment]
Just want to add that these types of tasks should start by proposing an idea or concept, and not by posting a final image. It's usually a bit more collaborative when starting this way, which ends up in a better result.

**Comment by GBKS** [comment]
Thanks for posting, @jakey-ads. While a file cabinet is not a super exciting thing in itself, this could probably work with the right style. Do you have something in mind for that?

**Comment by jakey-ads** [comment]
Thanks @GBKS. True, a cabinet by itself will have to rely heavily on styling to look engaging. 

Having dug around a little more, thinking it could be more like a combination of the attached. A dark wall of cabinets, cropped to give the impression it is endless. But with one different (Bitcoin) drawer open in middle which can be given bold contrast.

Taking the photograph and similar colours, but with maybe the simpler style of isometric graphic. See what you think, whether it might be a good direction or not.

![stock-photo--d-illustration-file-cabinet-1212461773](https://user-images.githubusercontent.com/129902365/234965120-8a220115-5f91-4a6f-8afd-36d2db437c84.jpg)
<img width="753" alt="Screenshot 2023-04-27 at 20 00 32" src="https://user-images.githubusercontent.com/129902365/234965185-0da4e14e-bc35-43ba-81ee-9f871b4c3e8d.png">

**Comment by GBKS** [comment]
You can also go wild a bit if you want. Here's a quick image I generated in Midjourney (`isometric filing cabinet, open drawer with files, bitcoin stickers, thick jungle background with tall grasa and vines, pixelart, retro, neon colors, --ar 3:2 --v 5`). Neon file cabinets in the jungle? Why not, maybe with some bitcoin stickers photoshopped on there.

![GBKS_isometric_filing_cabinet_open_drawer_with_files_bitcoin_st_2eb59247-ece9-411d-beb8-146d3915162e](https://user-images.githubusercontent.com/695901/235071274-3a3c1c5b-05ab-4db5-9a31-a7be73ae3d50.png)

It's totally your call how you want to go about it, just wanted to throw out the idea to introduce some aspects to this that are not logically derived from bitcoin and having fun with it (fun to create and fun to look at).

**Comment by jakey-ads** [comment]
@GBKS nicee! 😎 I like that direction. Will have a play with Midjourney along those lines and post an update

**Comment by jakey-ads** [comment]
@GBKS I had a play around, taking it forward. Liked the jungle vibe so tried some different art styles, with a futuristic style cabinet. Here's an example which I chucked on a couple of Bitcoin quirks, (the extrusion more subtle and the sticker more explicit).

![Frame 2540](https://user-images.githubusercontent.com/129902365/235379378-5c1b1b29-91bf-4044-8963-06c161657bf4.png)

Another route was all out futuristic
![jakeyads_A_futuristic_filing_cabinet_made_of_translucent_glass__d9322a6d-5223-4233-9834-87d3be341a17](https://user-images.githubusercontent.com/129902365/235379763-3c0321dc-5d60-4485-aab7-38f77aa23222.png)

p.s. Will definitely be getting to grips more with Midjourney.. nuts what it can do.

**Comment by GBKS** [comment]
The quality and lighting is nice. Looks pretty serious. Maybe it can be more fun, since the page is about providing a diverse and creative collection of design files?

**Comment by jakey-ads** [comment]
How's about this sort of thing @GBKS? (Before I go any further with it)
A different style/direction. More fun, and illustrating the range of what can be found. Inviting the user to dive in.
![jakeyads_A_filing_cabinet_made_of_alluminum_its_drawers_partial_e31defa9-1266-4653-a278-4eba19852d73](https://github.com/BitcoinDesign/Guide/assets/129902365/0d781dc9-3c26-4ca5-a292-65e3eb2d52db)

**Comment by GBKS** [comment]
Looks great. You clearly get the idea of a filing cabinet with its associated use case, but filled with diverse and interesting stuff.

By the way, if you want to increase the resolution and crispness of images, [Upscayl](https://www.upscayl.org) is really good.

**Comment by jakey-ads** [comment]
@GBKS ok great! And thanks, yeah as I was making variations the quality wavered a bit. I'll check Upscayl out and then see how I might Bitcoinify it a bit.

**Comment by jakey-ads** [comment]
@GBKS Damn, Upscayl really _is_ good. With increased res, I've added a couple of stickers. See what you think, and if all good I'll sort the optimisations/PR etc.

![Frame 2544](https://github.com/BitcoinDesign/Guide/assets/129902365/4e97e5fe-b101-4751-b903-049c909adfda)

**Comment by GBKS** [comment]
Love it. I think it's going to work really on the resources page.

**Comment by jakey-ads** [comment]
@GBKS when you say Resources page, do you mean on https://github.com/BitcoinDesign/Guide/issues/734? (Assuming not as it looks like it's already in progress)
Just checking to be sure the PR I create in the right place.

**Comment by johnsBeharry** [comment]
Looks sleek especially love the sticker easter egg! I really need to get on this midjourney train, just been in ChatGPT land dealing with text for the last 5 months.

**Comment by johnsBeharry** [comment]
@jakey-ads I'd say it should go on the main page for resources instead of just the design files subpage but can be applicable to both. +1 for [main resource page](https://bitcoin.design/guide/resources/) because it adds visual interest to the main section to draw people into the deeper section if they're just browsing casually.

**Comment by jakey-ads** [comment]
> Looks sleek especially love the sticker easter egg! I really need to get on this midjourney train, just been in ChatGPT land dealing with text for the last 5 months.

Thanks @johnsBeharry. Yeah it's pretty amazing, and a lot of fun. I made some use of [AIPRM](https://www.aiprm.com/) via ChatGPT - and that helped create inspiration for more complex prompts in Midjourney.

**Comment by GBKS** [comment]
Sorry, I meant "design source files" page, not "resources" page. Mixed things up, but as Johns said it also works for the resources page.

**Comment by mouxdesign** [comment]
Super cool @jakey-ads. Nicely done!
