### ISSUE TITLE
Create a banner image for the `Wallet` page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#736]
**Request the visual**

Hello, I would like to request a visual for the glossary -> node page of the guide.

**Link to the page**

https://bitcoin.design/guide/glossary/wallet/

**Visual Type**

Header banner image. 

**Illustration guidelines**
If you're a contributor looking to tackle the issue, you can [preview our illustration guidelines](https://bitcoin.design/guide/contribute/illustration-guidelines/).

**Comment by Bosch-0** [comment]
Awesome! Let me know if you need any assistance with the design / getting a PR up for it. You can just share your early designs in this issue or Slack for feedback

**Comment by Bosch-0** [comment]
Assigned this issue to you @fakoredeDamilola

**Comment by fakoredeDamilola** [comment]
Thank you very much, I will get started with it right away but please like you said, I will need assistance with the design if possible. I am not actually a UI person

**Comment by jeffreyweier** [comment]
Hi @Bosch-0, i've playing around with the attached image. Let me know what you think!
![hot and cold wallets](https://github.com/BitcoinDesign/Guide/assets/98287483/ad7e5e95-1833-4561-8bc6-85e7d00b6d6e)

**Comment by GBKS** [comment]
I like it. Funny how one of the lines doesn't go all the way through in the bitcoin symbol (typical AI-generator thing). You think that could be fixed?

**Comment by jeffreyweier** [comment]
![jeffweier_two_small_wallets_with_bitcoin_logo](https://github.com/BitcoinDesign/Guide/assets/98287483/e6993b90-3ec3-4052-8b76-b1d567ef3729)

variation with a better BTC logo.

**Comment by GBKS** [comment]
Great, that does it. I'll post in the Discord to see if anyone else has feedback.

**Comment by mouxdesign** [comment]
Looks great @jeffreyweier. Nice and simple and good complimentary colors.

**Comment by GBKS** [comment]
I implemented the image in #1056, you can find a preview link there as well. If that looks good to you, we can merge it in.

**Comment by GBKS** [comment]
#1056 is live and the new banner is up on the [wallet page](https://bitcoin.design/guide/glossary/wallet/) now. Thanks for your contribution @jeffreyweier, I really appreciate it. Have a good one.
