### ISSUE TITLE
Create a banner image for the `How it works` section

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#738]
**Request the visual**

Hello, I would like to request a visual for the how it works section of the guide.

**Link to the page**

https://bitcoin.design/guide/how-it-works/

**Visual Type**

Header banner image. 

**Extra context**

[Jeff on Slack](https://bitcoindesign.slack.com/archives/C015856BDME/p1648789779102219?thread_ts=1648781045.710589&cid=C015856BDME) made a suggestion about making the visuals for this sections pages have a level of consistent aesthetic / visual harmony applied throughout to communicate a flow of the ideas. We did something similar with the [onboarding](https://bitcoin.design/guide/onboarding/introduction/) section where the banner images are connected. 

**Illustration guidelines**

If you're a contributor looking to tackle the issue, you can [preview our illustration guidelines](https://bitcoin.design/guide/contribute/illustration-guidelines/).

**Comment by GBKS** [comment]
Just want to add that these types of tasks should start by proposing an idea or concept, and not by posting a final image. It's usually a bit more collaborative when starting this way, which ends up in a better result.

**Comment by jakey-ads** [comment]
Hey guys, is this issue still to be done? I'd be happy to give it crack.
An initial thought was to show something along the lines of an **instruction manual or book**. Conveying that this area contains comprehensive, structured sections for a user to gain new knowledge.

**Comment by jakey-ads** [comment]
Ignore the last comment, I've seen the mention of moving to a mini-project approach 👍 . I'll keep a tab and hopefully can help contribute :)

**Comment by GBKS** [comment]
You're welcome to work on this if you'd like. The mini-project approach is for the "regulars" to bundle their efforts, but anyone is welcome to work on other tasks as well.

**Comment by jakey-ads** [comment]
Thanks @GBKS. Ok great I'll take a look.

**Comment by jakey-ads** [comment]
@GBKS @Bosch-0 

I've had another thought on concept which I believe is a bit stronger, and taken the liberty of putting something together to see what you guys think. I appreciate this isn't in line with ideal process, so am more than happy to go back to the drawing board! But to explain this one:

A set of cogs to convey how Bitcoin (as the central piece) consists of many interconnected things. Each being a cog that is part of the greater whole. Having gone with flat/simple/subtle styling in the hopes of making this section feel accessible (particularly for those new to BTC), reducing the risk of making it feel too technical/daunting. 

![how-it-works-v1](https://user-images.githubusercontent.com/129902365/231589872-a9682f7d-6b0f-4e48-99e5-33dbc0db1fca.jpg)

**Comment by GBKS** [comment]
Sorry, never got back to you on this one. I think it works. Gears are a very mechanical metaphor for high-tech crypto money, but it communicates clearly.

**Comment by jakey-ads** [comment]
No worries @GBKS. Ok great! I'll take a look at the image guideline resources and get this into the necessary shape.

**Comment by jakey-ads** [comment]
@GBKS I've sized and optimised as required. And the [link to Figma here](https://www.figma.com/file/EhWhvRUaUHzfOlJ4MtAHGR/Banner-image-%7C-How-it-works?type=design&node-id=0%3A1&t=mNgc5EFAsuBI3u6l-1)

Just having a bit of trouble on the 'testing locally' steps as haven't done that before. So in the meantime here is the folder of images: [how-it-works.zip](https://github.com/BitcoinDesign/Guide/files/11455820/guide.how-it-works.zip)

You might have thoughts on the bg pixelation. It gives some texture but I can't quite tell if it works.

Anyway, I'll try to look at testing locally over the coming days.

**Comment by GBKS** [comment]
Awesome, looks good. Let me know how local testing and creating a pull request works out. I know it can be tricky if you haven't done it before.

**Comment by GBKS** [comment]
Looks like we forgot to close this issue. The task is complete, closing it.
