### ISSUE TITLE
Make image on `Backup & Recovery` page less imposing

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#746]
Via [this comment](https://github.com/BitcoinDesign/Guide/pull/739#issuecomment-1088886709).

[Live page](https://bitcoin.design/guide/daily-spending-wallet/backup-and-recovery/landing-page/).

**Comment by Bosch-0** [comment]
This issue could be part of our bigger milestone focusing on revising the newly formed Daily spending wallet reference design we now have in the guide.

**Comment by enyipreshious** [comment]
I'd like to solve this. How do I go about it? 

I have check the issue, and if I get it correctly the image size and colour doesn't blend well with the content.

I could recreate the illustration in figma and make appropriate changes

**Comment by Bosch-0** [comment]
Here is the Figma file for that image: https://www.figma.com/file/q9EgLqOKcIVc0Cq7khtpNm/Onboarding-%3E-Backups?node-id=0%3A1 by @sbddesign 

This can be found in the markdown file which if you go to Code at the top, go the guide -> Daily spending wallet -> Backup & recovery -> landing-page.md file you can see there is a illustration sources section at the top of the page. 

Details on how to size the images can be found here: https://bitcoin.design/guide/contribute/illustration-guidelines/ 

If you need help opening the PR for this, happy to help!

**Comment by enyipreshious** [comment]
Thank you @GBKS and @Bosch-0 for your help. The repo has been cloned on my computer to make the appropriate change. The option of removing the `layout = "full-width"` line is what I for. The purple colour seems to still work fine, so I left it at that.

Here are the two images for comparison. I also need help with PR
![image](https://user-images.githubusercontent.com/57605607/163453059-a89a11e5-a827-4506-906d-b9efba9696de.png)
![image](https://user-images.githubusercontent.com/57605607/163453203-b2bbff42-0670-46fd-8e98-f13a387855c2.png)

**Comment by sbddesign** [comment]
@enyipreshious [Here is a good place](https://bitcoin.design/guide/contribute/propose-a-change/#getting-started) to learn about making a PR. There is a video tutorial you can watch and instructions underneath the video. Let us know if you have any questions, we can help.

**Comment by GBKS** [comment]
This is complete with the merge of #775.
