### ISSUE TITLE
Create a page about accessibility

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#754]
If we really want to design bitcoin for everyone, we need to have an eye on accessibility. From my experience, this topic is usually mostly ignored (by me, too) and there's usually a lot of low-hanging fruit. Even just spending a few hours of testing and implementing fixes can remove blockers for certain users that would otherwise prevent them from moving forward in an app at all.

I'm really not an expert on this, but here are some areas to look into that come to mind:

- Accessibility of recovery phrases (is it intuitive for non-English speakers)?
- Recovery phrases and screen readers (not good for privacy if it's read out loud)
- Essential flows like onboarding, sending, and receiving
- QR codes for visually impaired people
- Readability (I heard that 4th-grade level writing is required to be understandable by most) & localization
- Color contrast, text sizes, etc - probably best tested on specific apps

This topic is not unique to bitcoin, so there are probably a lot of good resources out there. So we could just focus on UI patterns and elements that are unique to bitcoin, and testing open-source bitcoin apps to help improve IRL implementations.

A first version of a new page in the guide could include more general tips and tools, and then later become more detailed.

**Comment by Bosch-0** [comment]
Yeah as simple as we can go the better for readability. 

> Over 75% of the world's 781 million illiterate adults are found in [South Asia](https://en.wikipedia.org/wiki/South_Asia), [West Asia](https://en.wikipedia.org/wiki/West_Asia), and [sub-Saharan Africa](https://en.wikipedia.org/wiki/Sub-Saharan_Africa), and women represent almost two-thirds of all illiterate adults globally.

A lot of these more developing nations and demographics are ones who seek to benefit the most from bitcoin so agree this is a very important area we need to focus more on. 

Crazy statistic from https://en.wikipedia.org/wiki/List_of_countries_by_literacy_rate

**Comment by Bosch-0** [comment]
Another thing on QR code visibility that Twitter does is turn your screen brightness up when you click on the QR code to share your profile.

**Comment by Mogashni** [comment]
I am really happy that there will be a page in the guide about this topic. Indeed a low hanging fruit that we can start by learning step by step how to incorporate it and just take our key learnings from there. Is it an idea to start with a simple google document about:

1) What does accessibility mean?
2) Why is it important to users?
3) What accessibility areas specifically do we need to pay attention to with regards to designing bitcoin products for everyone; 
areas mentioned by Christoph;

- Accessibility of recovery phrases (is it intuitive for non-English speakers)?
- Recovery phrases and screen readers (not good for privacy if it's read out loud)
- Essential flows like onboarding, sending, and receiving
- QR codes for visually impaired people
- Readability (I heard that 4th-grade level writing is required to be understandable by most) & localization
- Color contrast, text sizes, etc - probably best tested on specific apps

4) Some visual examples of how we think this can be improved. 
So take  a screenstate of an LN wallet for example and apply accessibility best practices to it and then see what it it would look like before and after.

Just some ideas but this has the potential to be built upon quite a bit and there could be eventually some sort of accessibility checklist created after we have gone deeper into it.

**Comment by Mogashni** [comment]
Have made a small start by creating a Google doc about accessibility, this is just the tip of the iceburg from what I can see as there is quite a bit around accessibility.
Link to Google doc:
https://docs.google.com/document/d/1xl2tKD66uRmn5WSKYwAyO202M3-6_kX-D11jPyr8olY/edit?usp=sharing

**Comment by Mogashni** [comment]
Google doc has been updated.

[Link](https://docs.google.com/document/d/1xl2tKD66uRmn5WSKYwAyO202M3-6_kX-D11jPyr8olY/edit#)
