### ISSUE TITLE
📱 Revise `Daily spending wallet` -> `Privacy` page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#758]
This issue will be part of a bigger milestone that focuses on revising the newly formed `Daily spending wallet` reference design we now have in the guide. 

The current privacy page in `Daily spending wallet` is more of a general overview of wallet privacy and isn't specific to a daily spending wallet. We should make the content of the page specific to daily spending wallets and add some UI designs illustrating the concepts. 

Some of the more general content may be more suited for a `Privacy` page in the `How it works` section which covers the technology / general considerations outside of specific contexts like a daily spending wallet. Though this is an issue for another time. 

Page: https://bitcoin.design/guide/daily-spending-wallet/privacy/

**Comment by Bosch-0** [comment]
Need to add new content around NFC privacy considerations https://github.com/BitcoinDesign/Guide/issues/580

**Comment by Bosch-0** [comment]
Relevant info for tackling this page:

- https://www.youtube.com/watch?v=Cjxc9ERz2mU 
- https://abytesjourney.com/lightning-privacy/
- https://en.bitcoin.it/wiki/Privacy
- https://voltage.cloud/blog/bitcoin-education/how-taproot-improves-the-lightning-network/ 

Also want to look into LSPs and lightning wallet servers and the privacy trade-offs with using them in your applications. 

- https://www.youtube.com/watch?v=jXjsxvuxByc
- https://bitcoin.design/guide/how-it-works/lightning-service-providers/

**Comment by Bosch-0** [comment]
For these revision pages the images should also be  generally updated:

- Ensure they reflect what is shown in the UI kit
- Apply [new modal](https://bitcoin.design/guide/contribute/formatting/#image-viewable-in-larger-modal-with-alternate-mobile-image) formatting to images  
- Remove grey area on the iPhone 'dip' at the top of the phone (see below). 

![image](https://user-images.githubusercontent.com/55287964/163140077-2a560b16-09bc-4dcb-b468-2b8031629795.png)

**Comment by GBKS** [comment]
As noted [here](https://github.com/BitcoinDesign/Guide/issues/656#issuecomment-1114660367), we should move the "Privacy checklist" and "Hiding sensitive information" part of the [Security](https://bitcoin.design/guide/daily-spending-wallet/security/) page to this page. This will add more UX guidance to this page that is otherwise more focused on techniques. For those, we should also consider how we can make them more practical (-> mockups).

**Comment by GBKS** [comment]
I can take on this page. As we discussed in a recent jam session, some of the more under-the-hood content from this page is better suited for "How it works". Instead, we can include more mock-ups that show where privacy considerations surface in the UI (like a receive screen showing a new address every time). Designers should understand some of the basics, like that on-chain transactions are public and preserved forever and lightning transactions aren't. So we'll have to explain a few things for sure, but maybe not go all the way down to inputs and outputs here. I'll start this with a draft in a Google Doc.

**Comment by Bosch-0** [comment]
Good idea, yeah it makes sense to have a privacy page in How it work to cover the nuances. We could even go over various privacy tech available similar to what Seth did [here](https://sethforprivacy.com/posts/proposed-bitcoin-privacy-improvements/) but with a more design emphasis.
