### ISSUE TITLE
Add "Bitcoin for Local Business Trifold" to design resources

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#759]
@pedromvpg put together a design and content for a pamphlet for local businesses to better understand and accept bitcoin. Should we add this to the [design files](https://bitcoin.design/guide/resources/design-files/) page? I could imagine this become a Figma community file and encourage others to tweak the copy, localization, etc and use in their own communities.

- [Tweet](https://twitter.com/pedromvpg/status/1507743744149397513?s=20&t=2SQBlpapIcDn8Ya-Aattvw)
- [Figma file](https://www.figma.com/file/DFX1838ZUNICK9ufFQavAf/Bitcoin-for-Local-Business-Trifold?node-id=0%3A1)
- [Slack convo](https://bitcoindesign.slack.com/archives/C014J9ZKXB4/p1648066118039439)

**Comment by pavlenex** [comment]
Could as well be part of merchant's section.

**Comment by GBKS** [comment]
Pedro created a [website](https://bitcoinforlocalbusiness.com) for this ([announcement](https://twitter.com/pedromvpg/status/1516800912584552450?s=20)).

**Comment by GBKS** [comment]
Addressing this in #823.
