### ISSUE TITLE
Add bitcoin wallet backup file to `Resources` -> `Design files`

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#760]
Add [this](https://www.figma.com/file/sJYnyi2amehFJ2JpDgj978/Bitcoin-Wallet---Paper-Backup-Template?node-id=1%3A535) bitcoin wallet backup figma template file to the design files page in resources

**Comment by GBKS** [comment]
Starting to tackle this. Prepared a [Figma file](https://www.figma.com/file/3SYzu5YZOjW2Tyfa1Ai7d7/Bitcoin-paper-wallet-template?node-id=0%3A1) and started a conversation on Slack.

We could put the design on Figma community, and also offer printable PDFs for download.
