### ISSUE TITLE
Small error on the Calender Page.

### ISSUE THREAD

**Issue by Bangalisch** [BitcoinDesign/Guide#771]
Yo, 

When you goto Calender. 
https://bitcoin.design/calendar/

It shows a little piece of code, didn't get put properly :) 

Cheers.

![screenshot 4](https://user-images.githubusercontent.com/102448109/163029536-72f7ba54-0a86-469d-af68-3e7832ed2677.jpg)

**Comment by GBKS** [comment]
Good catch. That is an unwanted side-effect of a recent code change [here](https://github.com/BitcoinDesign/Guide/pull/751). Will have to make that a bit smarter.
