### ISSUE TITLE
Create a page about node connection options

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#78]
Every (well, almost every) Bitcoin application at some point needs to connect to the Bitcoin network to retrieve data or publish transactions. This can happen in different ways, each one with advantages and disadvantages. I think it would be helpful to lay these out, so designers and developers can choose the one that is most appropriate for their product.

This stems from a Twitter/Slack conversation a few days ago that led me to create this image ([Figma](https://www.figma.com/file/qzvCvqhSRx3Jq8aywaSjlr/Bitcoin-Design-Guide-Illustrations-CO?node-id=940%3A6914)): 

![Note options 201215](https://user-images.githubusercontent.com/695901/102195259-9fc30a80-3ebe-11eb-972d-b549b02fb30b.jpg)

**Comment by GBKS** [comment]
Existing content to tie in is on the [software overview](https://bitcoin.design/guide/getting-started/software/#nodes) and [hardware overview](https://bitcoin.design/guide/getting-started/hardware/#nodes) pages, as well as the upcoming [glossary](https://deploy-preview-31--sad-borg-390916.netlify.app/guide/glossary).

**Comment by Bosch-0** [comment]
Keen to take this on, I was thinking this would be suitable within the Onboarding section of the Guide @ConorOkus @pavlenex

**Comment by Bosch-0** [comment]
I think there is enough content for there to be a Nodes chapter. Below is a rough outline of the content it would cover:

- Nodes chapter: This section covers best design practices for setting up, using and managing your own Bitcoin Full node 
	- Node types - explain what a full node is first
		- Desktop node
		- Hardware node
		- Hosted (cloud) node
		- Light nodes 
			- SPV
			- Neutrino 
	- Node management 
		- Bootstrapping 
		- Storage 
			- Pruned mode
				- Block filters should be used
			- Archive mode
		- Bandwidth 
		- Privacy 
		- Mining mode 
	- Connecting your wallet and node
		- Local
		- Remote 
	- Node applications

**Misc**
- Add ‘Connecting to the Bitcoin Network’ to onboarding section

Eventually lightning node content would also fit in here.
