### ISSUE TITLE
📱 Revise `Daily spending wallet` section landing page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#782]
This page is mostly a list of links. How can it be made more informative and effective.

This issue is extracted from #723.

**Comment by sbddesign** [comment]
Here is [a first crack at the DSW home page](https://www.figma.com/file/1Lffm4lwEZQ3b3xlajJWYG/Daily-spending-wallet-prototype?node-id=70%3A725). I'm including a low-res picture below for quick reference, but please see the above Figma link for a more thorough review.

Things I tried to address

- Model it after coding tutorials - I think this is a format people building in tech are accustomed to
- Bring back a clear way to see the entire prototype
- Explain more clearly that this is a reference design you can use to model your own product
- Explain the idea that every page may have "alternate options" -- I liken them to lego pieces. You might decide you want to build a product that's a lot like this reference design, but you want to swap out some of our design choices with alternate options.
- Responded to feedback that we should add more details to the backup, sending, and receiving tabs.

It might be better to finalize the text on this page after we have a better idea of the structure of the other pages. (Like, is there still going to be a funding page, splitting out requesting and receiving, etc).

![Image](https://user-images.githubusercontent.com/2414177/168808264-b549b362-55b0-4d82-b7ee-9efcb755aea5.png)

**Comment by Bosch-0** [comment]
Looks great, left a couple comments on the Figma

**Comment by sbddesign** [comment]
I have updated this document based on the feedback left in Figma. I have moved much of the text over into [this google doc](https://docs.google.com/document/d/1uLccJln7G-AMcr0CpUgFhAOckp5IMRrdgquCpezjp3A/edit?usp=sharing) so we can polish that up, but I did tweak the layout some in Figma.

**Comment by sbddesign** [comment]
As we discussed on [yesterday's Design Guide Jam](https://github.com/BitcoinDesign/Meta/issues/333), we can get this merged without the completed prototype. When #800 is complete, this page can be updated.

**Comment by sbddesign** [comment]
Regarding @Bosch-0's comments on yesterday's call about making the chapters list more visual, here are some ideas.

![ChaptersVisual2](https://user-images.githubusercontent.com/2414177/189154778-c3f95852-0410-41a2-994a-172772d7b1c9.png)

![ChaptersVisual1](https://user-images.githubusercontent.com/2414177/189154779-8c5a593f-d1b8-4835-894d-b90c792871a2.png)

I prefer the second one. If we use the page heading visuals, they will not carry over well at a small size. Let's just use an icon to represent each idea and a color.

I think it's a good idea to keep the content in a somewhat linear fashion. While they can also be read and appreciated independently, they do work together to tell a story about how this product works. I think this makes more sense than a very visual grid layout.
