### ISSUE TITLE
📱 Revise `Daily spending wallet` -> `First use` page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#783]
With our recent [re-org milestone](https://github.com/BitcoinDesign/Guide/milestone/16?closed=1), various pages were bundled into this new `Daily spending wallet` reference design. The content now needs to be revised for consistency in general, and more specifically to ensure that the guidelines are focused on a mobile lightning wallet for daily spending.

This issue is for revising the [First use](https://bitcoin.design/guide/daily-spending-wallet/first-use/) page.

**Comment by Bosch-0** [comment]
Review of this page

Rename from `First use` to `Onboarding`
- We could salvage some content from the old onboarding landing page and include it here
- Focus this section on everything that happens before the user enters the app. 
    - We could cover a few different onboarding styles - more educational ones, ones that explain certain quirks of the DSW (how fees work for example) etc or both.
- Add info around setting a PIN on nboarding, nothing too in-depth - we can link to the security page for a deeper dive on this (this is all round a good practice imo). 
- Make sure every onboarding frame has an action to take and it isn't just blindly showing copy

Maybe this is a page is something @Mogashni and Milli would be interested in tackling as an extension of their work with Blixt?

**Comment by GBKS** [comment]
@Bosch-0 renaming to onboarding and focusing on what happens before the app seems like replacing this page with something different, no?

**Comment by Bosch-0** [comment]
> happens before the app

Sorry wasn't super clear, this is in the apps sections before you get into the apps home screen

**Comment by Mogashni** [comment]
Would the educational onboarding flow created for Blixt be useful in [First use](https://bitcoin.design/guide/daily-spending-wallet/first-use/), I think so yes. There were quite a few screen states that were designed during the sprint (still being finalized) that could go into the first time a user would be using a wallet, they would then be educated first before they practically start first using it. Atleast this was the idea with Blixt to educate first based on the main pain points described by the users. 

The current educational screens when onboarding with Blixt is more for advanced users though so all text/education with regards to channel management would have to be removed from the educational section. (UI)

**Comment by GBKS** [comment]
I started working on this page today. Something I'd to do is to present a more comprehensive user flow of a first-use experience, like the one below, to replace the current carousel of info screens (which are just static information). Each screen is an action that allows the user to configure the app to their needs. The final step is funding, and afterwards the user should be in the know how things work and comfortable using the app.

![Daily spending first use sequence 220623](https://user-images.githubusercontent.com/695901/175329765-3169176f-c5ef-441e-b7a7-6acba387e55b.png)

Some of these screens can be moved to later points, like only asking for cloud backup once bitcoin have been received. Generally, I am leaning a little more towards being explicit, to ensure users understand what is going on. We could also describe both approaches. Either way, this is something I am looking into.

**Comment by GBKS** [comment]
Building on the flow above, here is a comparison of the two approaches. Either way, we need to ask the user to back up their wallet and enable security settings. Question is just whether we do this right away or later.

1. Doing it right away (with the option to skip) makes the first use a little longer, but also provides a good moment to inform users about how their funds will be protected right away. Users may be more comfortable actually depositing funds, knowing that the wallet is backed up and secure.
2. Doing it after first deposit gets users more quickly into the app, but also requires us to nag them later about backup and security. 

I think both approaches are fine, it's just moving the complexity from one place to another. Looking at the two next to teach other, the first one feels more trustworthy as it explicitly takes me through a good setup. What do you think?

![Daily spending first use sequence 220624](https://user-images.githubusercontent.com/695901/175496687-cd6fbf3a-c0ca-4a35-8033-f408b37c040e.png)

What are your thoughts on the "Two things you must understand" and "Enable automated connection services" screens?

**Comment by mouxdesign** [comment]
Nicely done Christoph. 

I think it might be interesting to explore the backup option as also possibly being something that will pop up as a reminder should the user choose to skip that step whilst onboarding. 

Also to perhaps look at giving the user confirmation of the actions they have completed, this could be in the form of a screenstate or a modal. Confirmation of their behavior then builds trust. 

I like the addition of the screen "two things you must understand", however the question I would also ask myself is;
What are the most important pain points that the users encounter in these initial stages? Does the addition of this screen cover the most critical thing/things they need to be educated on?

These could be the most common questions they ask or have been asking. Then if there would be one/two education screens during the onboarding flow, make those screens focused on those pain points that recur. 


![Group 2240 (1)](https://user-images.githubusercontent.com/90313394/175509882-93b7883d-3424-426f-9569-c512920b101d.png)

**Comment by Bosch-0** [comment]
Left some feedback on this here: https://www.figma.com/file/b1LNO172h5yZgdWlPJWO6k/First-use-feedback?node-id=0%3A1

Would be handy to link the original Figma file I find it much easier to give feedback there

**Comment by GBKS** [comment]
Here's an update, trying to address the feedback here and from Slack. Figma source is [here](https://www.figma.com/file/VB3GQdAnhl8yta44DY3PSV/Bitcoin-UI-Kit?node-id=3573%3A92556).
- Includes both initial setup (with obvious skip buttons) and reminders at later stages
- Removed "automated services" and detailed out fee disclaimers further
- Various small copy and visual tweaks for clarity

![Daily spending first use sequence 220628](https://user-images.githubusercontent.com/695901/176150180-a7347fa4-36e5-49d7-a546-33355d9b2a36.png)

**Comment by mouxdesign** [comment]
Very nicely done. I like the backup reminder on the last screenstate as well.
