### ISSUE TITLE
📱 Revise `Daily spending wallet` -> `Requesting bitcoin` page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#784]
With our recent [re-org milestone](https://github.com/BitcoinDesign/Guide/milestone/16?closed=1), various pages were bundled into this new `Daily spending wallet` reference design. The content now needs to be revised for consistency in general, and more specifically to ensure that the guidelines are focused on a mobile lightning wallet for daily spending.

This issue is for revising the [Requesting bitcoin](https://bitcoin.design/guide/daily-spending-wallet/requesting/) page.

**Comment by Bosch-0** [comment]
Going to address the unified QR toggle in this issue which I'm okay doing: https://github.com/BitcoinDesign/Guide/issues/690

**Comment by Bosch-0** [comment]
Just another suggestion for this page when using a home screen number pad.

When switching between units (sats <=> fiat) when an amount is already entered the input should be zeroed. This prevents inaccurate conversion calculations and makes it so the amount being sent is exactly what the user wants to send (in sats or fiat terms). 

Example with Zeus https://www.figma.com/proto/TqAM4LvuqvY7FBzFoaezJC/%E2%9A%A1-Zeus?page-id=134%3A661&node-id=5583%3A31966&viewport=405%2C48%2C0.2&scaling=scale-down&starting-point-node-id=5583%3A31966

**Comment by GBKS** [comment]
I'd use the toggle just to see how much the amount is in "the other currency", so I would not appreciate it getting reset to 0.

**Comment by Bosch-0** [comment]
You can show the other unit equivalent under the input so you don't have to click the toggle for that

**Comment by Bosch-0** [comment]
I touch on subscriptions in my requesting PR but thinking having a dedicated subscriptions page in daily spending wallet reference design may be needed. There is a lot of UX complexity to them which I felt like was going out of the scope of the requesting page

Comment related to https://github.com/BitcoinDesign/Guide/issues/767
