### ISSUE TITLE
📱 Revise `Daily spending wallet` -> `Activity` page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#786]
With our recent [re-org milestone](https://github.com/BitcoinDesign/Guide/milestone/16?closed=1), various pages were bundled into this new `Daily spending wallet` reference design. The content now needs to be revised for consistency in general, and more specifically to ensure that the guidelines are focused on a mobile lightning wallet for daily spending.

This issue is for revising the [Activity](https://bitcoin.design/guide/daily-spending-wallet/activity/) page.

**Comment by GBKS** [comment]
Also think this page doesn't need a ton of revision. The contacts feature is fairly generic and treats lightning and on-chain pretty much the same.

A small thing we can do is to switch the order of "A payment received on-chain" and "A payment made on Lightning".

**Comment by sbddesign** [comment]
Agreed, the order-switch sounds good.

**Comment by GBKS** [comment]
This is completed with the merge of #807.
