### ISSUE TITLE
📱 Revise `Daily spending wallet` -> `Contacts` page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#787]
With our recent [re-org milestone](https://github.com/BitcoinDesign/Guide/milestone/16?closed=1), various pages were bundled into this new `Daily spending wallet` reference design. The content now needs to be revised for consistency in general, and more specifically to ensure that the guidelines are focused on a mobile lightning wallet for daily spending.

This issue is for revising the [Contacts](https://bitcoin.design/guide/daily-spending-wallet/contacts/) page.

**Comment by GBKS** [comment]
Some feedback on this page was to narrow the payment formats on the ones that we actually recommend for implementation in a mobile lightning wallet focused on spending.

What makes this difficult:
- For interoperability, it's best to support as many formats as possible
- It's a moving target with BOLT 12 on the horizon and varying support for LNURL and Lightning addresses
- Even if a format is not supported, the wallet should still recognize it as legitimate and state why it is not supported

The "Supporting various payment request formats" section seems to be the one that causes this feedback, as it shows how to handle edge cases (user manually adding on-chain addresses and xpubs). Logically, there's a good case for keeping this, as the main point is about showing how to address different scenarios. It's similar to the [Errors section](https://bitcoin.design/guide/daily-spending-wallet/sending/#errors) in the "Sending" page. Maybe it's enough to move this to the bottom of the page?

What do you think?

**Comment by sbddesign** [comment]
Agreed that interoperability is something to strive for. However, that doesn't mean promoting every single format.

- Moving this section to lower in the page could help.
- It could also help to make some of the screens in this section more apparent that they are error states.
  - For example, it doesn't matter if the user types in a lightning address or an xPub, it all looks valid when you eye-ball it. These screens are very similar.

IMO, the stuff closer to the top of the page should really focus on correlating a Transaction (paid through BIP21, an on-chain address, or a BOLT11) with a Contact. Then focus on how to edit transactions and re-link them to different contacts. And after all that, then focus on the edge cases.

**Comment by GBKS** [comment]
Great review. I'll try to integrate as possible. There are some things I will not, do you want rationale to those?

Just a thought on the requests for adding bottom-fixed buttons. This is problematic on screens that include input fields, specifically on smaller phones. On an iPhone SE, the keyboard covers about half of the screen estate. Example:
![iphone-se](https://user-images.githubusercontent.com/695901/167365880-06c5957c-24bc-4652-a716-db6a043e340f.png)
This is why I've not used bottom-fixed primary CTAs for input-focused screens, they dominate the screen and make it hard to interact with the input.

**Comment by Bosch-0** [comment]
> Just a thought on the requests for adding bottom-fixed buttons.

Good point! Maybe if there is something inputted in the form highlight the Save button orange to give it some more importance.
