### ISSUE TITLE
🛒 Merchants > Use Cases and Personas

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#789]
This should be based on the interviews and research done by @beanandcheeseburrito, and be a first stepping stone towards a merchant section. Use cases and personas will then allow us to create more content step by step.

**Comment by sbddesign** [comment]
Pasting in some notes on this one from the [Merchants TOC planning doc](https://docs.google.com/document/d/1FY2yMtAu4prxlWT280K8Sd_zkvrm1UkypVTnt5jFzLA/edit?usp=sharing):

- Breaking down business needs by size:
  - Large Businesses
  - Think "corporation"
- Medium Business
  - 10+ People
- Small Business
  - Family with a restaurant
  - Guy with a hot dog stand
  - Solo freelance designer
- Breaking down business needs by sales method:
  - Online
  - In-person

I think we can hit all these bullet points using info we glean from the Merchant Product Review calls.

**Comment by GBKS** [comment]
Don't think we get to see the outcome of this research, so going to close the issue. We can re-open if there's new momentum.
