### ISSUE TITLE
Refer to hardware wallets as signing devices / signers in the guide

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#792]
The term hardware wallet is something that has always added a bit of friction when it comes to explaining bitcoin and the different hardware / software categories to people. A more accurate, and better way to convey the concept, is using the term signing device instead.

I propose we switch all reference of Hardware wallets to Signing devices, or simply signers, in the design guide. We can still mention that these are also referred to as hardware wallets while we transition but in general we should push for this terminology.

https://signingdevice.com/

https://twitter.com/nvk/status/1518756527649271809?s=20&t=Z_QJK8GX6rtooEAeg9p82w

**Comment by GBKS** [comment]
Interesting that the landing page for [Tapsigner](https://tapsigner.com), made by the same people that created https://signingdevice.com/, still calls Tapsigner a bitcoin wallet... 

I like both terms. One is a bit more intuitive, the other a bit more accurate.

**Comment by sbddesign** [comment]
Let me ask this: given all the "hardware wallets" on the market, are the examples of situations where a hardware wallet might be used for something _other_ than just signing?

**Comment by Bosch-0** [comment]
You can use Ledger to login to sites with U2F, but it's essentially still signing. A good HWW imo will be limited to signing to limit it's attack surface

**Comment by GBKS** [comment]
I'd stick with "hardware wallet" as a consumer-facing term. "Signing device" is fine for technical discussion.

To me it's a bit like renaming "smartphone" to "mobile computing device". Yes, it's more accurate, but what's the goal? To be precise or to be easily understood?

From the website:
> "Hardware Wallets" are not Bitcoin wallets, they are signing devices. A device to store and manage private keys securely. Bitcoin wallets have chain state (access to the blockchain/ledger) and are capable of creating transactions. With the term "Signing Device" or ["Bitcoin Signer"](http://bitcoinsigner.com/) we hope to disambiguate.
> 
> This is a better term because it frames the process in terms of speech/action. "This is my signature", "using my signing device". It also help show how non-signing wallets (ie "hosted" or "web" wallets) take away your capacity to trully own, sign.

Not sure the term "signing device" makes it clear that this thing has no chain state and is not capable of creating transactions. I think you need to have a good understanding of how things work under the hood to start drawing this type of conclusion.

The idea to focus on action is good, but not totally sold on the logic. Isn't it a stronger message to focus on the device holding your keys to indicate that you control them?

Good thing about keeping "hardware wallet" would be that people can keep their general mental model of "wallet", and don't have to think about this "signing device" maybe being a whole different thing and try to figure out how it relates to wallets.

**Comment by Bosch-0** [comment]
I think `Signer` is a better consumer facing term. You can't use a hardware wallet without interfacing with a wallet. This confuses people as they need a wallet to interact with their wallet. Confusion when it comes to private key management is a serious issue as messing it up means you could lose your bitcoin. 

The hardware wallet term adds more friction than having to learn a new term imo. I've seen this problem countless times when onboarding people to bitcoin. 

The term also helps educate people on a soft level about private keys - this is necessary UX friction point as no matter what private key custody is never getting abstracted away in the UX so people should have at least a basic understanding.

**Comment by sbddesign** [comment]
I am warming up to the idea of calling a hardware wallet a "signer".

@GBKS I hear and understand your comments that context matters. I think the bitcoin community devotes a lot of energy to trying to find new terms for things.

If we're talking about a "signer" that's used in a single-key setup -- sure, that's effectively a "wallet". You plug your wallet in, do your transaction, and unplug your wallet.

But consider a 2-of-3 multi-sig setup. What is a "hardware wallet"? Is my hardware wallet one of the key-holding devices, or is my wallet **all 3 of the devices put together**? Is this like Voltron? Do all 3 of my hardware wallets do a dance and combine to form a giant mega hardware wallet capable of defending my bitcoin from attack? In my mind, the wallet skeumorph starts to fall apart for multi-sig.

Multi-sig is where I really see the value in the term "signer". I've got a multi-sig _wallet_, and I've got 3 _signers_ for it.

**Comment by GBKS** [comment]
Multi-sig is just tricky in general. You have to differentiate between:

- One owner (personal multi-sig)
- Multiple owners ([shared wallet](https://bitcoin.design/guide/shared-wallet/) reference design)
- Assisted (a third-party service managing one key, like Muun or our [Savings Wallet](https://bitcoin.design/guide/savings-wallet/) reference design)

That means the term "signer" by itself can refer to:
- An application
- A hardware device
- Another person in a shared multi-sig setup
- A third-party service

That makes it a good umbrella term, which is fine for a general statement like `I've got a multi-sig wallet, and I've got 3 signers for it.`, but not specific when getting into UX or to describe dedicated hardware devices for key management in the design guide.

A while back, I tried to think through the UX of this [here in Figma](https://www.figma.com/file/VB3GQdAnhl8yta44DY3PSV/Bitcoin-UI-Kit?node-id=649%3A2024). I ended up using the term `signer` and `co-signer` in the context of shared wallets, referring to other people. For personal multi-sig wallets, I ended up primarily using the term `key`. So a user is asked to "set up your 3 keys" during wallet creation. Then they are asked "how do you want to set up key #2" and can choose whether they want to connect to a hardware wallet (bluetooth, cable, NFC), or import a key (which could also come from a ColdCard or other device). Using `keys` here was better language-wise because it created a contrast to `signer` which implies a person (or third-party service). Both `hardware wallet` and `signing device` would work in this context, and both terms would probably be complemented with a more detailed description (like [here](https://www.figma.com/file/VB3GQdAnhl8yta44DY3PSV/Bitcoin-UI-Kit?node-id=3253%3A87971)). Again, context matters.

To get back to the main point on whether to use `hardware wallet` or `signing device`, I think we're in opinion-land. We could ask peeps on Slack or stage a fencing duel.

[Words are hard](https://youtu.be/PTsSk0r_Tq8).

**Comment by sbddesign** [comment]
Considering there's already been discussions about it on slack, a fencing dual seems like the only logical next step.

**Comment by GBKS** [comment]
I'm cool with using signing device in the guide. Since "hardware wallet" is still the most commonly used term, we'd just have to ensure that people searching for it can still find the content.

What the broader market will use is TBD by the hive mind anyways.

**Comment by sbddesign** [comment]
Yeah, agreed. For SEO purposes, we'd want the word hardware wallet on the page. We also would want to point out that some people may call it a hardware wallet.

And to your point about context, same thing applies with a "signer".

- It's a "signing device"
- But when we're being casual or doing marketing, we might like to call it a "signer"
- And when we're talking about human beings who participate in this multi-sig quorum, they are "signers" who use their "signing devices" or "signers" to get the job done

**Comment by Bosch-0** [comment]
To get things moving https://github.com/BitcoinDesign/Guide/pull/804

**Comment by GBKS** [comment]
Looking at #804, I don't think we're on the same page yet. "Signer" is fine for casual use, but not specific enough to refer to hardware wallets in the context of this guide.

Repeating [from above](https://github.com/BitcoinDesign/Guide/issues/792#issuecomment-1116960424):

> That means the term "signer" by itself can refer to:
> - An application
> - A hardware device
> - Another person in a shared multi-sig setup
> - A third-party service

**Comment by danielnordh** [comment]
First, apologies for being late to this discussion.

I am not in favor of replacing `hardware wallet` with `signing device`.

When a newcomer to bitcoin asks where they should 'store' their bitcoin, the alternative to custodial solutions is a self-custody `bitcoin wallet`, which is then a choice between a `software wallet` and a `hardware wallet`.

The key distinction is that one type is on a device likely connected to the internet/blockchain, while the other type is not, and therefore in theory better protecting the private keys from a third party.

This makes sense, and can be easily explained. 

Being able to sign, or being a device, are NOT key distinctions between the two in my opinion.
They both perform signing, and an iPhone / Android phone / laptop with a software wallet can all be signing devices in a multi-sig setup.

I do not think we have anything to gain by trying to rename or redefine hardware wallets in the guide, in fact I think we would lose clarity and increase confusion. Calling them something else, when there is a defined category in public perception and Ledger, Trezor, Coldcard etc all use hardware wallets in their PR would be futile IMO.

I do however think signing devices (or just signer), is what we should call all the participants in a multi-key wallet.

There will also be a new hardware category that will fit 'signing device / signer' better, which will not be marketed as a wallet. Square/Block already seem to be working on one, which would be a signer in a 2-of-3 multi-sig wallet.

**NACK** from me

**Comment by Bosch-0** [comment]
> When a newcomer to bitcoin asks where they should 'store' their bitcoin, the alternative to custodial solutions is a self-custody bitcoin wallet, which is then a choice between a software wallet and a hardware wallet.

What about when they find out they need wallet software to use the hardware wallet? This always adds a lot of friction to onboarding and makes it unclear where the bitcoin is kept. From personal experience, people seem to think the bitcoin is stored on the software wallet and the hardware device acts like a 2FA. 

Maybe we can disagree on the term, but agree that having hardware and software wallet in the lexicon adds confusion?

> when there is a defined category in public perception and Ledger, Trezor, Coldcard etc all use hardware wallets in their PR would be futile IMO.

This issue was brought up because these entities are renaming it to signing device over hardware wallet, Coldcard already has: https://coldcard.com/, I expect others to follow suite

> I do however think signing devices (or just signer), is what we should call all the participants in a multi-key wallet.

Yep agree, signer in this situation makes a whole lot of sense!

> There will also be a new hardware category that will fit 'signing device / signer' better, which will not be marketed as a wallet.

How is blocks wallet different from a Coldcard when talking about its function?

**Comment by danielnordh** [comment]
> This issue was brought up because these entities are renaming it to signing device over hardware wallet, Coldcard already has: https://coldcard.com/, I expect others to follow suite

I see `hardware wallet` being used on Ledger, Trezor and Coinkite's sites. From the latter:
_"COLDCARD Mk3 is the cypherpunk's ultimate in secure hardware wallets."_

> Maybe we can disagree on the term, but agree that having hardware and software wallet in the lexicon adds confusion?

As long as the terms are widely used by the public, and the industry, it makes sense to have them in the glossary.

> How is blocks wallet different from a Coldcard when talking about its function?

I am just speculating that they won't be marketing it as a hardware wallet, like Coinkite does on their site.

**Comment by Bosch-0** [comment]
![image](https://user-images.githubusercontent.com/55287964/167525942-b6959e8b-b04a-4063-917e-ed9880da8bf2.png)

Other will follow suite, just thinking ahead for the guide. 

There has been a huge amount of discussion about this on Twitter starting here: https://twitter.com/nvk/status/1518756527649271809?s=20&t=okRzoterx0bK3uFq7sFtEQ

> In my view, renaming things are rarely worth the effort.

If it is globally established in the lexicon of the world I agree, but I think we forget how early bitcoin is and how little people use it. This is a period were defining things is important to limit confusion in the future when mass adoption comes.

**Comment by sbddesign** [comment]
> There will also be a new hardware category that will fit 'signing device / signer' better, which will not be marketed as a wallet. Square/Block already seem to be working on one, which would be a signer in a 2-of-3 multi-sig wallet.

I don't see the distinction between products that are marketed as "hardware wallets" vs. those marketed as "signing devices". They are _all_ signing devices. They all require interfacing with software that runs external to the hardware.

IMO, best to just clarify that hardware wallet and signing device both refer to the same type of device, but one is recommended.

**Comment by GBKS** [comment]
Totally unrelated, but I think this is a very nice shed here that also accommodates bikes.
![](https://images.squarespace-cdn.com/content/v1/5981123de3df287005ec442e/1527711277383-287FEJ2UIPV6U3NF281Z/3x3+Custom+DIY+Bike+Storage+Shed?format=1000w)

I don't see consensus, or even formation of consensus towards a change. I agree with Stephen and also recommend to stick with "hardware wallet" with an aka. I'd also say that the terms can be used as deemed appropriate in the context, similar to how we ended up in the discussion around payments vs. transactions.

**Comment by sbddesign** [comment]
_Well, actually_, that shed has scooters in it, so...

**Comment by ConorOkus** [comment]
I agree with the premise that we are still very early, none of these terms are mainstream or globally adopted. If we want users to have a more accurate mental model of bitcoin and its blockchain, we should seriously consider the change toward `Signer/Signing Device`. 

When I look back at our Hello Bitcoin video on [How Bitcoin Actually Works](https://youtu.be/6vQB3XGB7ig?t=293) we make a concerted effort to ensure the user knows a wallet is just an app used to track their bitcoin. The actual bitcoin is at the "Bitcoin bank in cyberspace". 

```When my wallet sent my transaction, some fancy math called cryptography was used to “sign it” with my private key. This proves that I had the permission to unlock and transfer the bitcoin I want to send... ``` 

A `Hardware Wallet` is just a more secure dedicated piece of hardware for moving money on the bitcoin blockchain. `Signer` helps emphasise this. Do we want users to think they have bitcoin on these devices or just the ability to move and track the bitcoin they own on-chain? Maybe the term `wallets` needs to go entirely LOL Bitcoin Apps + Signers...

**CACK** from me

**Comment by Bosch-0** [comment]
So I rang up Merriam-Webster and we've decided on this: 

**Signer** = Someone who uses a signing device to sign bitcoin transactions.

**Signing device** = A hardware device used by a signer to sign bitcoin transactions.

**Signing app** = An application used by a signer to sign bitcoin transactions.

I like how ColdCard also puts 'Bitcoin' at the start of Signing device, just to make things that little bit more clearer. You could even say Bitcoin signer instead of just signer for extra clarity. Just saying signer in a general convo may not be as clear, signing what exactly? 

I threw a third definition in the mix as well to make the distinction between a signing device like a Coldcard, and signing app like blue wallet which could be apart of a multisig setup for example. 

Wallets can act as Signing apps (if they have hot keys) to. 

Also I completely disagree that these type of discussions are bike sheds. Maybe for people who don't build products from the outside think they are but we are product designers, this kind of stuff is very important for usability. If that's your view, you don't have to participate in these discussions.

**Comment by danielnordh** [comment]
Signing Device (and its variations) definitely have a place in the guide, and I support the idea of pioneering better definitions or names for 'things' that users of bitcoin products come across. 

I also believe that there is a lot of common ground among the people in this thread. 
What there doesn't appear to be though, is rough consensus on 'switch all reference of Hardware wallets to Signing devices, or simply signers, in the design guide', which was the original suggestion. 

I believe we have a better chance of moving this forward by looking at specific usage of these terms in the guide, on specific pages in isolation. Where it seems we can improve the clarity by updating the usage of these terms, let's do so.

I suggest we close this more general issue, and create separate issues/PRs for each page where we think we can do better, and judge it in the context where they appear.

**Comment by moneyball** [comment]
> Signing device = A hardware device used by a signer to sign bitcoin transactions.

What about a 2-of-3 wallet with a dedicated hardware device as a signer, a phone hardware device as a signer, and a cloud/server hardware device as a signer? All 3 are technically signing devices.

**Comment by GBKS** [comment]
Closing this for now due to lack of activity. @Bosch-0 said in a jam session that he is likely going to reconsider this during his upcoming work on the savings wallet reference design.
