### ISSUE TITLE
Add info around hiding home screen balances by default

### ISSUE THREAD

**Issue by paulosacramento** [BitcoinDesign/Guide#799]
Hi guys.

On the [Security/Spending Wallet](https://bitcoin.design/guide/daily-spending-wallet/security/) we already have recommendations about:

1. Quickly hiding/displaying balance by tapping: https://bitcoin.design/guide/daily-spending-wallet/security/#quickly-hiding-balances
2. Moving the hide/display balance toggle from the home: https://bitcoin.design/guide/daily-spending-wallet/security/#an-application-wide-setting

But I would like to support @Bosch-0 proposal of adding a third recommendation, described by him here: 

> A good design practice we should add to the guide **is not showing wallet balances as the first screen when opening your application**. Below is an example of cashapps **initial screen which does not show a balance and jumps straight into a user pay flow** as an example.

I think we should also this specific recommendation to https://bitcoin.design/guide/daily-spending-wallet/security/ 

I can see that [this issue](https://github.com/BitcoinDesign/Guide/issues/578) has been closed, but I think this is very important and that @sbddesign would also support this addition.

**Comment by GBKS** [comment]
Good point. We switched most of the home screens to a cash-app like layout ([example](https://bitcoin.design/guide/daily-spending-wallet/requesting/#single-use-payment-requests)) for that reason, but not everywhere yet. We'll get to that in [milestone 16](https://github.com/BitcoinDesign/Guide/milestone/17).

I put together these examples of home screen approaches some time back. Maybe it would be good to add these somewhere to visualize for designers what some of the options are, along with their benefits and drawbacks.

<img width="1846" alt="Home screen approaches 211207" src="https://user-images.githubusercontent.com/695901/166417382-4c2e3119-bb75-402e-915c-b3c7bc3c45ff.png">

**Comment by sbddesign** [comment]
Yeah, agreed we should start shifting our UIs to reflect something like this. Probably requires changes on many pages.

**Comment by GBKS** [comment]
Looking through the daily spending wallet reference design, we only need to update the Requesting and Funding pages. The others are good to go.
