### ISSUE TITLE
Improvements regarding address validation

### ISSUE THREAD

**Issue by paulosacramento** [BitcoinDesign/Guide#806]
Hi everyone,
I was reading Patricia's research this week and have found an interesting discovery regarding the topic of address validation:

> One of the most repeated issues concerning common wallet operations was the address verification performed when the user prepared to send a transaction. Multiple participants, among the ones with a less technical background, described how cumbersome it was to verify the address digit by digit before sending, assuming it was a necessary security step to avoid sending their money into nothingness.
> 
> It was undeniably surprising to encounter a significant pool of the participants, many of whom have relevant sums of money invested into Bitcoin, who never heard about the address checksum.
> 

[Source](https://patestevao.com/work/bitcoin-ux-research/#address-validation)

After reading this and trying to find what we already had about address validation in the guide, the following three ideas came to my mind: 

**Suggestion 1**

- Add a sort of “This address has been verified as valid” text notification to the Sending Bitcoin screens of the UI Kit.

I imagine that this notification could appear directly under the address field and be shown as soon as the last address character has been entered, in the case of manual entering. This notification could also be presented on other steps of the sending flow, like at the review step, for example.

An invalid entered address would obviously display the opposite: “This address seems to be invalid.”

![Screen Shot 2022-05-07 at 19 30 14](https://user-images.githubusercontent.com/76049494/167267618-62574e3b-0d4b-462a-9972-f0e3d3a6d236.png)

**Suggestion 2**

Add more detailed information about address validation in the [Manual payment initiation](https://bitcoin.design/guide/daily-spending-wallet/sending/#manual-payment-initiation) section.

**Suggestion 3**

- Add content about address validation to the Address/Glossary page: https://bitcoin.design/guide/glossary/address/ 

What do you guys think about it?

**Comment by GBKS** [comment]
Good addition. I think a simple green check is enough.

If I understand correctly, for certain mistakes, it's possible to point out with character is incorrect. But, this might be very different across address formats, and maybe some further research would be helpful.

**Comment by Bosch-0** [comment]
Good suggestion, like Christoph said a simple tick to the right of the address would suffice. Addresses are always checked to be valid, but the user isn't aware of that. Making it so would give users some extra peace of mind as it seems to be a point  of friction as pointed out in the research. 

This may be out of the scope of this issue but some other _validations_ would also be helpful. Listed a few below:

- User enters a legacy address: Give the user some feedback saying that could save on fees if they use a SegWit address
- User enters an on-chain address that has been used: Alert the user that this is bad for their privacy. 

Also wanted to note that a lot of on-chain stuff will be removed from the Daily Spending Wallet in the coming weeks.

**Comment by sbddesign** [comment]
cACK.
  
I think the simple green checkmark would suffice, but it might make sense to have a more descriptive message in cases when the address is not valid. Error message, basically.

**Comment by GBKS** [comment]
Addressing this in #822.
