### ISSUE TITLE
Can I write the 'Unique aspects of bitcoin design" chapter?

### ISSUE THREAD

**Issue by paulosacramento** [BitcoinDesign/Guide#81]
I'm very interesting in writing this chapter and already have a lot of ideas. 

[Sorry, if this is not the place the ask this question. I'm still learning how to use Git Hub. 😂]

**Comment by GBKS** [comment]
That would be great, thank you for the initiative. There are two existing pages with similar titles "[Why bitcoin is unique](https://bitcoin.design/guide/getting-started/why-bitcoin-is-unique/)" and "[Why design for bitcoin](https://bitcoin.design/guide/getting-started/why-design-for-bitcoin/)", we should make sure that there isn't a lot of overlap if we now add "Unique aspects of bitcoin design". I wouldn't worry too much about it right now though. More important is to get your ideas out, have discussions about them, and then everything else becomes easier to decide.

As far as the right place, this issue works. Generally, issues are a bit like to-dos. Also, the "Discussions" tab is great if you want to ask a general question, as well as the #bitcoin-design-guide channel in Slack. "Discussions" is a new feature by Github (just released last week, I think), so we haven't used it much yet. Let me know if you have any other questions on these organizational things.

**Comment by paulosacramento** [comment]
All right. My idea of what should come into this new page shouldn't overlap much. Thanks for explaining everything in detail. :)

**Comment by paulosacramento** [comment]
Hi

**Comment by paulosacramento** [comment]
Hello everybody.

I've just finished writing the first section of the chapter: https://docs.google.com/document/d/18GbLjnfif7tvINL0yygSd14HzqRD34D8gRUVoAkrxP8/edit?usp=sharing

Feel free to comment, rewrite, and change as you wish.

**Comment by paulosacramento** [comment]
I've just finished writing the second section: **Lack of basic understanding of the technology**

https://docs.google.com/document/d/18GbLjnfif7tvINL0yygSd14HzqRD34D8gRUVoAkrxP8/edit?usp=sharing

Feel free to comment, rewrite and make suggestions.

**Comment by GBKS** [comment]
@paulosacramento is this issue something you are planning to pick up again?

**Comment by paulosacramento** [comment]
I think I should take what I have already written and see how it fits in the content of other pages, instead of a standalone section or topic. 

I intend to move forward like this.

**Comment by GBKS** [comment]
Great, thanks for the update.

This week, I am trying to go over all the old issues floating around to see which ones we can close or continue with. Just a bit of housekeeping.
