### ISSUE TITLE
Feerate dialogue example has feerates increase as transaction priority falls

### ISSUE THREAD

**Issue by Xekyo** [BitcoinDesign/Guide#814]
**Describe the bug**
The example image for the fee dialogue in the [on-chain fees section](https://bitcoin.design/guide/daily-spending-wallet/sending/#fees) has higher fees for slower confirmation targets and lower fees for faster confirmation:
- Fast: 1,000 sats
- Normal: 2,000 sats
- Slow: 3,000 sats

**To Reproduce**
1. Stare at [image on-chain fees section](https://bitcoin.design/guide/daily-spending-wallet/sending/#fees). 
2. Realize that fees should be higher if transactions are more urgent

**Expected behavior**
Fees should start high with quick confirmation targets then get lower for less urgent confirmation.
- Fast: 3,000 sats
- Normal: 2,000 sats
- Slow: 1,000 sats

**Screenshots**
![image](https://user-images.githubusercontent.com/4060799/168439447-92d36e21-8260-43ba-a096-34960941dbb1.png)

**Comment by moneyball** [comment]
haha whoops

**Comment by GBKS** [comment]
Good catch. @paulosacramento came in with the fix for this in #815 .
