### ISSUE TITLE
Adding Dark Theme

### ISSUE THREAD

**Issue by serhack** [BitcoinDesign/Guide#82]

**Comment by GBKS** [comment]
There is am mock-up for it [here](https://www.figma.com/file/K5ahSqVzoMVBuhT5hAVRJr/bitcoin.design?node-id=33%3A875). Has not been finalized or prioritized, as we just got a basic version of the site up. Would be cool to have though.

**Comment by Bosch-0** [comment]
Interested to try this approach to achieving this - https://dev.to/ekaterina_vu/dark-mode-with-one-line-of-code-4lkm. Will play around with this soon!

**Comment by GBKS** [comment]
The approach I've been [using](https://www.exploremonero.com) is via CSS variables, which is really easy to work with. It's explained [here](https://dev.to/ananyaneogi/create-a-dark-light-mode-switch-with-css-variables-34l8). You basically use a handful of CSS variables for all colors. Then you can add or remove classes or attributes to the HTML body which change those variables. This allows for multiple themes with pretty detailed control (as long as your theme styling is architected well).

The one-line-of-code approach inverts color, which brings some problems that are addressed in the article.

As far as requirements, my thinking was that we can apply different styling/themes to different pages and sections. That means that the site is not either white or black, but it can vary per page and section based on the authors preference (like making a privacy section always black). Just my thoughts though.

**Comment by GBKS** [comment]
As this issue has not had any activity for 6+ months, I'll close it. If someone wants to actively work a dark theme, a new one can be opened.
