### ISSUE TITLE
Pending transactions: vague time frames instead of precise number of minutes

### ISSUE THREAD

**Issue by paulosacramento** [BitcoinDesign/Guide#834]
Hello, I would like to know your opinion about a possible addition to the [Activities page](https://bitcoin.design/guide/daily-spending-wallet/activity/).

I was reading [Patricia's research](https://patestevao.com/work/bitcoin-ux-research/#transaction-confirmation-uncertainties) today and found an interesting suggestion.

As we all know, the confirmation time for an on-chain transaction can vary a lot, specially if the user decides to pay a lower fee.

At the same time, a lot of users may have an expectation of having their transactions cleared in about 10 minutes.

To avoid frustration, it may be a good idea to give a vague time frame for when the transaction should be confirmed, instead of an precise number of minutes.

An example:
Instead of
- **Pending** - _12 minutes_

Maybe it would be better to have something like
- **Pending** - _Around half an hour_

What do you think about that?

**Comment by paulosacramento** [comment]
Excellent!

**Comment by pavlenex** [comment]
Addressed here https://bitcoin.design/guide/daily-spending-wallet/sending/#fees
