### ISSUE TITLE
Update bitcoin.design title

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#838]
Currently bitcoin.design uses the sites description as the tagline on Google searches. This description is also shown in the sub-text so its showed twice. For better SEO / less redundancy we should update the tagline to state the communities tagline of 'Design bitcoin for everyone'. 

See image below for how bitcoin.design appears on Google - description is showed twice. 

![image](https://user-images.githubusercontent.com/55287964/171006783-8f78237e-63f1-4f50-a9bc-04895acfdbca.png)

I can do this just posting the issue so I don't forget

**Comment by GBKS** [comment]
Let's figure out the exact text we should use for the `title` and `description` tags?

**Comment by Bosch-0** [comment]
What was wrong with my suggestion?
