### ISSUE TITLE
Use Algolia for Guide search 

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#846]
Opening this issue as a place to discuss us upgrading the guide's search engine to using Algolia: https://www.algolia.com/ 

It will make our search much more advanced and help users find the content relevant to them. 

There is also Docsearch which uses Algolia and gives some extra features. It's offered for open-source projects so they can use Algolia for free (Algolia is free up until a certain amount of queries). https://docsearch.algolia.com/

I already have us Docsearch Bitcoin Design account setup fyi 

Part of this would mean creating some new UI for the search bar too.

**Comment by Bosch-0** [comment]
Can address this with this update also: https://github.com/BitcoinDesign/Guide/issues/844

**Comment by GBKS** [comment]
Using Algolia sounds like a good idea. How about we set up a draft PR to test the quality of the results before we decide?

Docsend seems like overkill. I'd prefer having a simpler, more elegant UI that fits in better with the rest of the site design. Looks like Algolia provides [libraries](https://www.algolia.com/doc/guides/building-search-ui/getting-started/js/) that should make this fairly simple.

**Comment by Bosch-0** [comment]
Docsearch is pretty much the exact same as Algolia

1. We get it it for free (unlimited queries)
2. They give some out of the box frontend UIs which imo look fine (saves up re-inventing the wheel).

**Comment by sbddesign** [comment]
The DocSearch might be worth looking into. The unlimited free search they provide for FOSS projects would be a huge value add. I think we add our own styling to the search components by overriding our crafting our own stylesheet.

**Comment by Bosch-0** [comment]
I got us an account setup that we can use, was a bit of a waiting list to get accepted. They had to verify we are FOSS / educational to get access

**Comment by GBKS** [comment]
A further interest in this issue? The last activity was 1.5 years ago. We should close this one and open a new issue if someone wants to work on search.
