### ISSUE TITLE
Reference Design: Multi-sig & Time Lock

### ISSUE THREAD

**Issue by wild-kard** [BitcoinDesign/Guide#847]
**Describe your content request**

Hey guys, I would like to request/contribute some of the work I've been doing on a project which heavily relies on multisig and time locked bitcoin wallets. I would love for some of the UX I've thought through to make it back into this project as the UI kit was a huge help in helping me framework these designs.

The figma for my design work can be found here (I also have a very comprehensive technical design document if you are trying to understand this project at a higher level, reach out to me on slack -Heavily Armed Clown)
https://www.figma.com/file/KcE9byRVhSntYcTITn1OvY/Bitcoin-Wallet-UI-Kit-(Arctica)?node-id=3345%3A84800

**Additional context**

As well, I have done some video walk throughs of the UX if you are interested in seeing some of this talked through more in depth.
https://youtu.be/DIn2xZ43JoY part 1
https://youtu.be/UjN7BGleI40 part 2

**Suggestions**
I have done quite a lot of thinking on how to deliver a good UX to multisig and one of the biggest pain points I've come across is signing multiple transactions quickly becomes quite cumbersome. My solution to this is to allow and encourage output batching in an intuitive way, which I believe I've achieved with these screens below that would allow a user to generate, review, and sign for each output of a transaction, iteratively. 
![image](https://user-images.githubusercontent.com/43704663/173373624-ee3f7979-fdcc-40e5-a92c-d8a26246db1e.png)

Additionally, communicating time locked components to a user in such a way that you avoid any misunderstandings about the implications of time locked Bitcoin.
![image](https://user-images.githubusercontent.com/43704663/173373776-a9e53c20-e918-4af6-b8ee-61b6b287b446.png)
![image](https://user-images.githubusercontent.com/43704663/173373846-2de55e02-2582-41ec-a9a7-78b44361f835.png)

Furthermore, a large focus of this project is provided some ability for the user to break their time lock early, which I think will be a very demanded/important UX feature for products that make use of any sort of Bitcoin time lock. This is a very niche case study because Arctica is fairly complex technically, but it might also make for a good case study on "breaking time locks". I have an entire UX flow designed here that walks through how a user breaks their timelock in our product. It may be of use, but it's a large number of screens, and the below overview doesn't even include the setup process which makes this recovery possible. 
![image](https://user-images.githubusercontent.com/43704663/173374512-e77a6eb9-77c5-4e83-a3cd-b41593009b42.png)

**Comment by GBKS** [comment]
Thanks for being so open and public with your progress. I am wondering if this is a good fit for a "case study"? It's a section of the guide that we discussed but we don't have any content for yet. Half of the guide is generally relevant content, the other half are reference designs (basically made-up projects). Case studies would be documentation of real projects, their design decisions, specs, screens, etc.

**Comment by pavlenex** [comment]
@wild-kard are you still interested on tackling this one?

**Comment by GBKS** [comment]
@rabbitholiness is now working on a reference design for custom spending conditions that includes miniscript and time locks, via #1043. There is some overlap to this issue.

@wild-kard are you still interested in creating this page? Or should we close in favor of what Michael is doing if that also covers the content you were looking to add?

**Comment by wild-kard** [comment]
> @rabbitholiness is now working on a reference design for custom spending conditions that includes miniscript and time locks, via #1043. There is some overlap to this issue.
> 
> @wild-kard are you still interested in creating this page? Or should we close in favor of what Michael is doing if that also covers the content you were looking to add?

WIll go ahead and close the issue.

I am happy to aid by providing notes or screen caps @rabbitholiness if you'd like to see how I've worked through this issue, but if not I'm just glad that I could help keep the conversation moving!

**Comment by GBKS** [comment]
Yes, thank you, you were very early to this topic IMHO. Would be great to see a collab.
