### ISSUE TITLE
Add content around receiver paying network fee

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#852]
Something not addressed in the guide is having the receiver pay the network fee instead of the sender which is the usual way it is paid. 

This is useful in some scenarios such as if a service offers to pay the fee as an added benefit to the for users. 

How this can be done on the application layer is simply having the network fee deducted from the sent amount when it is sent.

This content would be best suited in the sending bitcoin page in the daily spending wallet reference design: https://bitcoin.design/guide/daily-spending-wallet/sending/

**Comment by GBKS** [comment]
Aren't fees usually an estimate and not finalized until the transaction is made?

**Comment by pavlenex** [comment]
@Bosch-0 I am not sure I understand this one, can you elaborate on the use-case here?

**Comment by GBKS** [comment]
We have this covered since a few months ago in the [Send fees page](https://bitcoin.design/guide/daily-spending-wallet/sending/send-fees/#including-the-fee-in-the-amount). Going to close, feel free to re-open if there is something missing in the linked page.
