### ISSUE TITLE
Add more graphical wordmark for homepage header

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#854]
The current wordmark in the top left of the bitcoin.design site is a little bland

Was thinking we add a little bit of 'design flair' to the wordmark to make it look a little less bland. Here is one suggestion, but the main point of this issue that is it would be nice to have something a little more 'designed.' 

![image](https://user-images.githubusercontent.com/55287964/174575774-ef111c5b-588c-40b1-b463-bc5e93e625bd.png)

[Figma source](https://www.figma.com/file/qr4P17z6WSPADm6oW0cKw2/Design-Guide-Bosch?node-id=1032%3A5995)

**Comment by peanutbutter003** [comment]
Hi @Bosch-0 ! I'd like to work on this, can I be assigned here?

**Comment by GBKS** [comment]
Closing this issue as it has gone stale. If there's renewed interest, we can re-open it.

Bigger picture, this task would not just be about tweaking the text in this one spot. It would be more of a larger branding discussion. If this text becomes more graphical, then that treatment should go hand-in-hand with other uses of the wordmark.
