### ISSUE TITLE
Fiat Over Lightning - How it Works

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#866]
As we discussed [on this call](https://github.com/BitcoinDesign/Meta/issues/323), representing fiat within a bitcoin wallet is becoming important. Price volatility is UX problem for using bitcoin for daily spending, and fiat over LN is one solution for this.

Often this involves things that don't always mesh with the principles of the Guide (Strike, Chivo). Then there are wallets like Bitcoin Beach which are technically custodial but make these trade-offs in a more transparent way. And finally, there are discussions around things like stabilized lightning channels with DLCs, TARO, etc.

This is not specific to merchants, however is important within the conversation about merchant adoption.

With this issue, I am proposing we create content for the [How it Works](https://bitcoin.design/guide/how-it-works/) section that describes at a high-level some of the proposed solutions and what the trade-offs and risks are.

**Comment by sbddesign** [comment]
I'll take this one. I've had my head in this space a lot lately.

**Comment by sbddesign** [comment]
Super rough early draft. Will polish it up some next week. I welcome feedback, comments, suggestions, but keep in mind this draft is early and rough. Spellcheck will come later.

📝 [Rough Draft](https://docs.google.com/document/d/1V_04hDVKqCfXGZoO2Amb7biLSO4ayfLLmb1UWd03suM/edit?usp=sharing)

**Comment by mouxdesign** [comment]
Good job @sbddesign. Reviewed the Google doc and added in some comments.

**Comment by GBKS** [comment]
Is it OK if I take this one over? Seems like it's mostly about tidying up the document, and it would be nice to get this into the guide.

**Comment by mouxdesign** [comment]
I'd say go for it. 🎉Happy to review the content as we move through the process of pushing it live.

**Comment by sbddesign** [comment]
> Is it OK if I take this one over? Seems like it's mostly about tidying up the document, and it would be nice to get this into the guide.

Sure. One comment was that we should have image diagrams, so I started building those [here](https://www.figma.com/file/V0XlTUU4g7dEtSQ81nYzSt/Fiat-Over-LN?type=design&node-id=0%3A1&mode=design&t=8t4zKl4vJbebJX2R-1). Feel free to scrap it if you like. Let me know if you need a rubber duck to discuss any of this with.

**Comment by GBKS** [comment]
Thanks, Stephen, I duplicated your document and made a bunch of edits and updated illustrations. Would love to get your feedback. I find it a pretty tricky topic, and I am not sure I understand everything correctly, so I recorded a video with my thoughts.

- [Video](https://youtu.be/w3taOC4Rxms)
- [Draft doc](https://docs.google.com/document/d/1fvWbN6BkCq36K2dtOJgKpBl5J9F1E1JwQXvlKOdl_b8/edit?usp=sharing)

I just focused this on the "How it works" part and removed the bottom section that was intended to show screenshots and mock-ups. We could add that in a second step, or as a separate page or reference design.

Do you know if more projects have implemented these mechanisms in recent months?

**Comment by mouxdesign** [comment]
Looked through this one and added in some comments and ideas to the google doc:
- Agree that Fiat over lightning might not be the best title. Ideas might be something to do with the word "stability" as this feels like the use case for a person. 
- The write-up itself is very concept heavy so felt there might be a need to intro in with concepts such as custodian, tokens and so forth. Also an option to link out to them.
- Also saw an opportunity to create a visual summary table at the end to which presents the pros and cons of each method. This might result in there being less text in the body itself. Although it might also dismantle the way the info is presented. 
- Also took a stab at refining the explanation of DLC's which is a combo of two concepts so tried to rephrase how it was explained to make it a bit easier to understand.

**Comment by GBKS** [comment]
Thanks for the feedback. PR #1067 is now set up and ready for further review of the page in HTML clothes.
