### ISSUE TITLE
Update activity screens to include the wallet balance (daily spending wallet)

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#875]
We focused the [home screen](http://localhost:4000/guide/daily-spending-wallet/sending/#payment-entry-points) on initiating a transaction and removed the balance for privacy purposes. But we didn't add the balance anywhere else (!?). I can go over all the screens and add it to the [activity](http://localhost:4000/guide/daily-spending-wallet/activity/) screen (seems logical to have it there).

Example:
![activity-labeling](https://user-images.githubusercontent.com/695901/180774956-6b9d74b2-f0bf-4ce2-9bc6-222aef743fcb.png)

**Comment by Bosch-0** [comment]
Yep activity page makes sense to me!
