### ISSUE TITLE
Add Slack Channel list to Contribute page

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Guide#884]
**Describe your content request**

**Link to the page**
[Contribute Page](https://bitcoin.design/contribute/)

**Why would you like to change the content?**
Add a list of the current Slack channels as well as a description of each so that that the guide also links back to Slack and there is an overview of the current channels.

**Notes**
- The list is currently in a rough form, including the channel descriptions, they have been taken straight from Slack.
- Will add a list here as well of Channels on Slack that are currently inactive/not very active
1. Bitcoin core gui
2. Bitcoin core gui preview
3. Bitcoin core qml
4. Onboarding
5. Payments
6. Private Key Management
7. Project Ideas
8. Sustainability

**Google Doc with list of channels and descriptions**

[Doc](https://docs.google.com/document/d/1yYSokBOyQx5LOZrfjLigFD3aWlROZ8ZoutfqmE_whvM/edit?usp=sharing)

**Comment by rupam870** [comment]
Hey @mouxdesign 
I am interested in this. Would like to know about the deliverables. Is it a figma file of the Contribute page with the section of slack channels added?

**Comment by GBKS** [comment]
Now that we're on Discord, do we still need this? Unlike Slack, all channels are instantly visible to new members, so there's no discovery.

**Comment by mouxdesign** [comment]
Indeed. Good to close as all channels are visible on Discord.
