### ISSUE TITLE
Add UX research resources to the Bitcoin Design guide

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Guide#888]
Part of the UX research toolkit will include a competitive analysis. I thought it might be an idea to add in a write up of:

Why competitive analysis is important in UX Research

- What we can learn from it

- How to conduct it

Then to link the Figma file itself of the UX research Toolkit.

Created an initial [write up](https://docs.google.com/document/d/1LYfU2C0SgAkyk5cU04T9R17Yj3rRfEayAzhdWdrZv94/edit?usp=sharing), still very much in its early stages

At the moment within the UX research toolkit the following tools have been created:

- Competitor analysis

- Usability analysis

- Usability testing

- User stories

It would be interesting to add content with regards to these UX Research processes within the design guide to help product builders who are looking to do this themselves.

At this early stage that might be in the form of:

### 1. Educational content
 How to conduct a competitive analysis (why its beneficial, what results/insights you can gain from it)

### 2. Case study 
A walk through how a competitive analysis was done and then show the steps and thought process.

So far the users that we have been interviewing for the bitcoin design guide have mentioned wanting to see or learn from more case studies. It might be interesting to think how the learning is taken on best, whether that is seeing it in the form of a case study or in an educational write up.

Do you think it is beneficial to have a call within the community to identify what sort of content they would like to see with regards to  UX research in the guide?

**Comment by GBKS** [comment]
Maybe you could build on the "[Getting to know your users](https://bitcoin.design/guide/designing-products/getting-to-know-your-users/)" page we already have? Could be revising the page itself, and/or adding sub-pages with different how-to instructions?

**Comment by ShalomOhuegbe** [comment]
@mouxdesign I am interested in writing this article. Should I begin to draft it out? This is my first contribution and I have experience in user research. Looking forward to hearing from you.

**Comment by ShalomOhuegbe** [comment]
I have gone through your initial write-up @mouxdesign , can I add my ideas to the doc, or am I to draft a totally new doc for the UX research?

**Comment by mouxdesign** [comment]
@ShalomOhuegbe  Would be lovely to have your contribution. Yes please feel free to comment on the Googledoc with your ideas and suggestions. If you click on the suggestion top right inside the googledoc it will allow you to make suggestions. Let me know if it works out!

**Comment by mouxdesign** [comment]
@ShalomOhuegbe Are you also part of the bitcoin design community [slack](https://bitcoindesign.slack.com/ssb/redirect)?

**Comment by ShalomOhuegbe** [comment]
@mouxdesign no I am not, I will join right now. Thank you. Can i draft my idea too or i am only allowed to suggest? I would like to write from scratch and submit for review if that's fine

**Comment by mouxdesign** [comment]
Feel free to draft an idea from scratch @ShalomOhuegbe, together we can merge the 2 ideas together.

**Comment by ShalomOhuegbe** [comment]
@mouxdesign I am done with the article. Kindly go through it and let me know what you think.

**Comment by ShalomOhuegbe** [comment]
[https://docs.google.com/document/d/1LYfU2C0SgAkyk5cU04T9R17Yj3rRfEayAzhdWdrZv94/edit#])

**Comment by aassoiants** [comment]
Curious how we should leverage the UXR Toolkit to support this issue

**Comment by mouxdesign** [comment]
Closing issue as we will be addressing it here #1021
