### ISSUE TITLE
Add more interaction/share options to each page

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#889]
We've discussed a few times that it's not obvious how to ask a question about a page, or propose a change. As shown in the mock-up, we could add options to the bottom of each page that lets the user take various questions. The design is pretty non-intrusive. 

![image](https://user-images.githubusercontent.com/695901/184121928-0c011719-9060-490d-aeb6-4ffdfa7e846a.png)

If we implement something like this, we'd have to keep an eye out if more people do end up asking questions in Slack or opening up discussions on Github, etc.

What options should should we provide?

**Comment by jakubszwedo** [comment]
I think a good option would be "Send feedback" with an input that when entered will appear in the dedicated Slack channel. Something for people that have some suggestions, but do not necessarily feel like opening a discussion or expecting any back and forth from the community

**Comment by GBKS** [comment]
Created a draft PR for this. You can try it out via #899 .
