### ISSUE TITLE
Resolve lightning network capitalisation inconsistencies 

### ISSUE THREAD

**Issue by jakubszwedo** [BitcoinDesign/Guide#890]
Hello

As it was advised in #886 I retracted the PR and I'd like to open a discussion regarding capitalisation of "lightning network" across the Guide. For now, the guide uses 2 styles of capitalisation:

- Lightning network
- lightning network

We should decide on one rule and just keep it consistent. 

Here are two take from the mentioned PR (mine, and the second one is @danielnordh ):

> I suggest capitalising both words in Lightning Network. It is the way it is used the most, makes it more intuitive to understand alongside abbreviations like LN or LND and is advised by [Optech Style Guide](https://github.com/bitcoinops/bitcoinops.github.io/blob/master/STYLE.md). That is also how it was written in the [original Lightning Network paper](https://lightning.network/lightning-network-paper.pdf).

> In terms of the actual suggestion here, adopting Lightning Network in capitals everywhere, I am not in favor of this.
I'm basing my opinion on similar thoughts as in the discussion about Bitcoin vs bitcoin https://github.com/BitcoinDesign/Guide/issues/635 In addition, I don't like calling out the lightning network in a way that comes across as 'branded' and extra important when it is capitalized: Lightning Network. The focus should as much as possible be on bitcoin, and lightning is a supporting subset of bitcoin technology (that should be less and less important to know by name over time IMO).
My suggestion to the problem of it being using in mixed case throughout the guide would be to use lower case everywhere:
I.e. bitcoin and the lightning network.

**Comment by danielnordh** [comment]
As I mentioned in the related PR:

- I fully support updating to a consistent capitalisation across the guide
- My suggestion is 'lightning network', following the same arguments that led to us using lowercase 'bitcoin'

**Comment by moneyball** [comment]
While I have a strong opinion on bitcoin (lower case), I don't have a strong opinion on Lightning Network / Lightning network / lightning network. I personally don't think the rationale I've used for lower case bitcoin applies to LN though as bitcoin, like the internet is or is becoming a ubiquitous term known by everyone. LN is and should be a technology hidden away from users as much as possible (except perhaps now with early adopters who are technology enthusiasts).

**Comment by GBKS** [comment]
I've tended towards lowercase "lightning network" and "lightning", simply because it looks/feels off capitalizing both words everywhere. No strong opinion though. Can we just pick one and run with it?

**Comment by Bosch-0** [comment]
Lets just lower case

**Comment by jakubszwedo** [comment]
Most agree it can be lowercase, so [here's a PR ](https://github.com/BitcoinDesign/Guide/pull/930)
