### ISSUE TITLE
Descriptors for printable backup template community file

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#897]
I would like to consider adding an output descriptor to the [printable template community file](https://www.figma.com/community/file/1110806582648546839), but want to make sure it's done accurately.

Benefit: a descriptor could be a scannable QR code to store important info for restoring the wallet. This would make this data usable without asking a user to type in complicated strings. To my understanding, this may be necessary for P2TR wallets.

However, such a descriptor should not include any private key data as we wouldn't want that passing through a printer. So we should first explore what kinds of descriptors are most appropriate for this situation. Seeking developer consult on this.

**Comment by Bosch-0** [comment]
Great idea, something else to think about is how would importing this descriptor in a recovery situation look like in-app?

**Comment by sbddesign** [comment]
Looking into this one now.

**Comment by sbddesign** [comment]
Alright, here's a mockup of a descriptor added to a print template. Thanks to @notmandatory for helping me with the correct descriptor formatting.

![bitcoin-wallet-backup-template-12-letter](https://user-images.githubusercontent.com/2414177/208540218-20d67727-bef4-4e33-9803-bcfc333139ed.png)

I'd like to add this to the [manual backup section of the daily spending wallet](https://bitcoin.design/guide/daily-spending-wallet/backup-and-recovery/manual-backup/). Upon closer inspection of the [community file](https://www.figma.com/community/file/1110806582648546839) for the printable template, I'm not sure it's the right place. The reason is because when I read the text (such as "Write down the following information if it is provided. It is not absolutely necessary, but may simplify the wallet recovery process.") it makes me think the community file is meant to be used as a resource external to the software. Meaning, the printable file was provided by someone other than the wallet developer.

This descriptor QR is something that would be generated by the wallet software itself, and is unique to each wallet. So it's a related but slightly different use case.

**Comment by notmandatory** [comment]
Also note that some (most?) wallets will need to record two descriptors, one for external addresses `tr(.../0/*)` and one for internal (change) addresses `tr(.../1/*)`. @achow101 has a [BIP 389 proposal](https://github.com/bitcoin/bips/pull/1354) that could combine these two into one descriptor, not sure if/when this will make it's way into any wallet projects.
