### ISSUE TITLE
New header image for Automatic cloud backup

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#912]
We are in need of a new header image for this page: [Automatic cloud backup](https://bitcoin.design/guide/daily-spending-wallet/backup-and-recovery/landing-page/)

## What are we looking for in a header image?

The image should be relevant to the topic of the page, however, don't be afraid to get creative with it. Examples of other pages that are both creative and relevant to the topic: [Settings](https://bitcoin.design/guide/daily-spending-wallet/settings/), [Coin selection](https://bitcoin.design/guide/how-it-works/coin-selection/), [Sending bitcoin](https://bitcoin.design/guide/daily-spending-wallet/sending/).

## Why is a new image needed?

The reason is because the current image was designed when this page was part of a section that no longer exists called "onboarding". It was meant to show a structured order of steps. Now, it is part of the [daily spending wallet section](https://bitcoin.design/guide/daily-spending-wallet/). Half of the other pages in the daily spending wallet do not follow this pattern. The structured order no longer makes sense.

## Illustration guidelines

If you're a contributor looking to tackle the issue, you can [preview our illustration guidelines](https://bitcoin.design/guide/contribute/illustration-guidelines/).

## Tips

If you are interested in working on this issue, leave a comment so we can assign it to you.

Please also share your initial ideas and ideally **work-in-progress** updates _before_ suggesting a final visual. This allows for better collaboration and ensuring the visual goes well with the page content.

**Comment by sachinsejwal** [comment]
Hi @sbddesign  ,
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?
