### ISSUE TITLE
New header image for Manual backup

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#913]
We are in need of a new header image for this page: [Manual backup](https://bitcoin.design/guide/daily-spending-wallet/backup-and-recovery/manual-backup/)

## What are we looking for in a header image?

The image should be relevant to the topic of the page, however, don't be afraid to get creative with it. Examples of other pages that are both creative and relevant to the topic: [Settings](https://bitcoin.design/guide/daily-spending-wallet/settings/), [Coin selection](https://bitcoin.design/guide/how-it-works/coin-selection/), [Sending bitcoin](https://bitcoin.design/guide/daily-spending-wallet/sending/).

## Why is a new image needed?

The reason is because the current image was designed when this page was part of a section that no longer exists called "onboarding". It was meant to show a structured order of steps. Now, it is part of the [daily spending wallet section](https://bitcoin.design/guide/daily-spending-wallet/). Half of the other pages in the daily spending wallet do not follow this pattern. The structured order no longer makes sense.

## Illustration guidelines

If you're a contributor looking to tackle the issue, you can [preview our illustration guidelines](https://bitcoin.design/guide/contribute/illustration-guidelines/).

## Tips

If you are interested in working on this issue, leave a comment so we can assign it to you.

Please also share your initial ideas and ideally **work-in-progress** updates _before_ suggesting a final visual. This allows for better collaboration and ensuring the visual goes well with the page content.

**Comment by nityagupta6** [comment]
@sbddesign Can you assign this to me would love to work in this issue

**Comment by nityagupta6** [comment]
So about the idea- I have thought of 3 major elements in the header image, in the center there would be an illustration of the 12 seed recovery phrase, from which 2 outward pointing arrows will be there, one with a dashed line and the other with a solid line, the solid one would lead to the illustration of manual backup and the dashed line arrow would lead to cloud backup illustration. For the manual backup illustration, I would display the print template of the paper backup mentioned in the guide and for cloud backup, I would display an illustration of the cloud. And finally, there would be a small green tick at the top right of the manual backup illustration. I hope you like the idea, Pls give any suggestions and opinions on this idea so that I could move forward and work on this.

**Comment by nityagupta6** [comment]
I'm considering using minimalist flat illustrations, and I believe I can better demonstrate my idea once I provide a rough implementation of it.

**Comment by nityagupta6** [comment]
I'm a little unsure about the exact dimensions needed for the frames, even though I've reviewed the illustration guide. While the guide specifies the widths, it doesn't provide the full dimensions. Could you please clarify this for me?

**Comment by nityagupta6** [comment]
@GBKS how do I share my implementation for review? Should I send a screenshot or the Figma file or something else?

**Comment by GBKS** [comment]
You can share in the Slack or here, as you prefer.

**Comment by nityagupta6** [comment]
@GBKS As the previous idea was utilised in designing the header image for backup and recovery, I have thought of a different idea for the manual backup header.

The idea goes like this: there will be 2 parts of illustrations in the first one there is a person who is holding his phone in one hand and a pen in the other, above his phone will be a loading symbol. No just behind the person is a huge paper which is vertical (standing) on it some seed phrase is written. Now from the side of the paper there is one shield illustration which is half hidden behind that paper and half is showing from the side.

I hope you understood the idea. I am attaching a rough sketch for the same. Pls give your suggestions...Should the positions of certain things change here or its perfect pls let me know.

![WhatsApp Image 2023-04-05 at 17 34 17](https://user-images.githubusercontent.com/97425446/230075039-f71269d4-de16-42a5-b779-19a51ada57c1.jpeg)

**Comment by GBKS** [comment]
Here's an idea for a header image. Shows a stylized safe/vault, communicating the idea of a non-digital thing that is appropriately and securely stored. What do you think?

![image](https://github.com/BitcoinDesign/Guide/assets/695901/1ee446a3-e3fe-4371-96b1-c74595f173a8)

**Comment by GBKS** [comment]
I created PR #1050 to implement the image in my comment above.
