### ISSUE TITLE
New header image for Recovery

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#914]
We are in need of a new header image for this page: [Recovery](https://bitcoin.design/guide/daily-spending-wallet/backup-and-recovery/recovery/)

## What are we looking for in a header image?

The image should be relevant to the topic of the page, however, don't be afraid to get creative with it. Examples of other pages that are both creative and relevant to the topic: [Settings](https://bitcoin.design/guide/daily-spending-wallet/settings/), [Coin selection](https://bitcoin.design/guide/how-it-works/coin-selection/), [Sending bitcoin](https://bitcoin.design/guide/daily-spending-wallet/sending/).

## Why is a new image needed?

The reason is because the current image was designed when this page was part of a section that no longer exists called "onboarding". It was meant to show a structured order of steps. Now, it is part of the [daily spending wallet section](https://bitcoin.design/guide/daily-spending-wallet/). Half of the other pages in the daily spending wallet do not follow this pattern. The structured order no longer makes sense.

## Illustration guidelines

If you're a contributor looking to tackle the issue, you can [preview our illustration guidelines](https://bitcoin.design/guide/contribute/illustration-guidelines/).

## Tips

If you are interested in working on this issue, leave a comment so we can assign it to you.

Please also share your initial ideas and ideally **work-in-progress** updates _before_ suggesting a final visual. This allows for better collaboration and ensuring the visual goes well with the page content.

**Comment by mouxdesign** [comment]
Idea for this header. Just a very rough sketch.

A wallet, a key and then the background would be the seedphrase...so a bunch of words that are in the bacground...as it move towards the bottom they fade out. 





![Image](https://user-images.githubusercontent.com/90313394/226342611-7f83b627-261a-4dfe-8795-a8254869c4eb.jpg)

**Comment by pragya1976** [comment]
@sbddesign I would like to work on the issue, can you please assign this issue to me.

**Comment by GBKS** [comment]
This has been completed, so we can close the issue.
