### ISSUE TITLE
New header image for Security

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#915]
We are in need of a new header image for this page: [Security](https://bitcoin.design/guide/daily-spending-wallet/security/)

## What are we looking for in a header image?

The image should be relevant to the topic of the page, however, don't be afraid to get creative with it. Examples of other pages that are both creative and relevant to the topic: [Settings](https://bitcoin.design/guide/daily-spending-wallet/settings/), [Coin selection](https://bitcoin.design/guide/how-it-works/coin-selection/), [Sending bitcoin](https://bitcoin.design/guide/daily-spending-wallet/sending/).

## Why is a new image needed?

The reason is because the current image was designed when this page was part of a section that no longer exists called "onboarding". It was meant to show a structured order of steps. Now, it is part of the [daily spending wallet section](https://bitcoin.design/guide/daily-spending-wallet/). Half of the other pages in the daily spending wallet do not follow this pattern. The structured order no longer makes sense.

## Illustration guidelines

If you're a contributor looking to tackle the issue, you can [preview our illustration guidelines](https://bitcoin.design/guide/contribute/illustration-guidelines/).

## Tips

If you are interested in working on this issue, leave a comment so we can assign it to you.

Please also share your initial ideas and ideally **work-in-progress** updates _before_ suggesting a final visual. This allows for better collaboration and ensuring the visual goes well with the page content.

**Comment by ConnectBhawna** [comment]
@sbddesign Can you assign this to me would love to work in this issue

**Comment by Bosch-0** [comment]
Just assigned you @ConnectBhawna, feel free to share updates here!

**Comment by pragya1976** [comment]
@sbddesign I would like to work on the issue

**Comment by GBKS** [comment]
@ConnectBhawna you are assigned to this issue, but have not posted an update on it in the past 3 weeks. Are you still working on it? Or is it OK to assign it to @pragya1976? You two could also collaborate.

**Comment by GBKS** [comment]
@pragya1976 I assigned this to you, since @ConnectBhawna did not reply within a week. Thanks for tackling this one.

**Comment by pragya1976** [comment]
@mouxdesign @GBKS 
![security-header](https://user-images.githubusercontent.com/97403447/229801642-8309d7b9-c35e-4a57-94ff-c307d1cb6b91.png)
This is a rough sketch of header for security page . Hope you like the idea .Please give your suggestions

**Comment by pragya1976** [comment]
@mouxdesign 
![security-header](https://user-images.githubusercontent.com/97403447/230050313-fb5a6727-7872-4df4-bd07-a0ffa50c5dfa.png)
This is my idea for header image for security

**Comment by rabbitholiness** [comment]
@sbddesign  shouldn't this issue be closed? looks like it was merged with #1004

**Comment by johnsBeharry** [comment]
Yep it should. Thanks for that @rabbitholiness !
