### ISSUE TITLE
Create a case study for the Blixt design sprint

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#927]
@mouxdesign already started putting content together in [this comment](https://github.com/BitcoinDesign/Guide/issues/722#issuecomment-1237283786). Let's refine it and add it as our first case study in the guide.

**Comment by ShalomOhuegbe** [comment]
Hello, i am interested in this project. What are the steps i should take please

**Comment by mouxdesign** [comment]
Have worked on the case study further an incorporated alot of the feedback such as copy and visuals. Its ready for another review.

Link to [Googledoc](https://docs.google.com/document/d/199BOVnTFpseWmiOWm2wyj1D1bfkSrTENGlESV2ii0YM/edit?usp=sharing)

**Comment by sbddesign** [comment]
Thanks @mouxdesign, left some comments in the doc. Looking good to me from a content perspective. Mostly just grammatical and typographical nits.

**Comment by GBKS** [comment]
Nice update. I left some comments in the doc, and Stephen did as well. Maybe time to move it to code after this revision? Or would you like to get feedback from others (did you already ask some UX researchers for input?).
