### ISSUE TITLE
Make website translation ready

### ISSUE THREAD

**Issue by danielnordh** [BitcoinDesign/Guide#936]
For a long time we have been wanting to translate the website and guide content into other languages than English, starting with Spanish. For this to happen, there are two main things we need to take care of:

1. Set the site up for handling more than one language
2. Make the actual translation of content

We have some interest in 2 from a Spanish part of the community, so once we have 1 figured out we can start getting help from a wider group.

Regarding 1, I'm a beginner when it comes to the technical details with Jekyll and the options we have so would love input from someone with more experience. I imagine we either need to use translation keys in the current pages or have duplicate files for each new language. I am more used to the former, coming from mobile development, but am not really knowledgable enough to make a call.

Some Jekyll plugins that seem relevant:
- [Polyglot](https://github.com/untra/polyglot) - Seems good for handling links etc, but looks like it requires duplicate page files for each language?
- [Language](https://github.com/vwochnik/jekyll-language-plugin) - uses translation tags in single md file, but seems not to have been updated for 7 years?
- [Multiple langages](https://github.com/kurtsson/jekyll-multiple-languages-plugin) - similar to above with translation tags

Several others seem to not have been updated for even longer. 
If you have experience with translating Jekyll sites please help us decide on a tech choice!

**Comment by sabakhilji** [comment]
Hi @danielnordh I am also a beginner but I want to share
https://leo3418.github.io/collections/multilingual-jekyll-site/choose-multilingual-plugin.html
where I have learned a little bit about Jekyll and Polyglot. I thought might be useful for you.
Thanks!

**Comment by GBKS** [comment]
We discussed this in [today's jam session](https://github.com/BitcoinDesign/Meta/issues/606). Generally, there has been no real interest in helping out with localization. A second aspect is that browsers these days have excellent automated localization built-in for many languages ([Safari](https://www.macrumors.com/how-to/safari-webpage-translation-ios/), [Chrome](https://support.google.com/chrome/answer/173424?hl=en&co=GENIE.Platform%3DDesktop#:~:text=Translate%20webpages%20in%20Chrome&text=Go%20to%20a%20webpage%20written,will%20translate%20your%20current%20webpage.)). Those are not perfect, but are often really good. Safari can even translate text in images. That means any localization effort we provide will take a long time until it can match those free and automated features. Combined with our lack of resources, we came to the conclusion that this is not an urgent priority.

I'm going to therefore close this issue. If there is renewed interest, we can re-open or create a new one.
