### ISSUE TITLE
Create a new page on the site about the newsletter

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#967]
Let's give this more visibility and invite more community contributions. We have a tiny bit of content about the newsletter in our [social media guidelines](https://github.com/BitcoinDesign/Meta/blob/master/Social-Media-Guidelines.md#the-newsletter) in the meta repo.

I imagine this residing at `bitcoin.design/newsletter`. It would include the following content:

- Purpose of the newsletter
- Sign up
- How to contribute (submit content, content and writing guidelines, review and publishing process)
- Thank you to current and previous editors

With the latest newsletter edition, we're trying something new. We create a Google Doc and share it in the community. Anyone is invited to add content in the 3 weeks to publishing. Then in the last few days, our official editors come in and refine the content then publish it. This open process ideally invites more contributors in general, and also more diverse and interesting content as a result.

**Comment by GBKS** [comment]
First draft for this page. [Check it out](https://docs.google.com/document/d/1yo-JEqz_MthMtVkfDr9IKgC4eeQsVBMuehox1rY-jnk/edit?usp=sharing).

**Comment by danielnordh** [comment]
Looks great. Just added a suggestion to also have links to previous newsletters on the page.

**Comment by GBKS** [comment]
Thanks for the review. I'd like to avoid having to update this page every 3 weeks. Maybe we just pick one really good issue and link to that as an example?
