### ISSUE TITLE
🛒 Merchants > Personal Finance

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#971]
Review [Personal Finance](https://bitcoin.design/guide/designing-products/personal-finance/) and look for opportunities to talk about running a small business on bitcoin. Perhaps it could be its own category. It seems to me like a distinctly different use-case than the other categories.

**Comment by GBKS** [comment]
Going to close this issue, as discussed [here](https://github.com/BitcoinDesign/Guide/issues/864#issuecomment-1881207007). We can re-open if there's renewed momentum around merchant content.
