### ISSUE TITLE
🛒 Merchants > In-person Point-of-Sale Reference Design

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#972]
Add a reference design for an in-person merchant POS terminal. Here are some ideas from the [merchants planning doc](https://docs.google.com/document/d/1FY2yMtAu4prxlWT280K8Sd_zkvrm1UkypVTnt5jFzLA/edit?usp=sharing):

- Focus it first on small business and in-person
- Onboarding / First Use
  - Setting up a brand new wallet?
  - OR, using an existing wallet and setting up the POS functionality
- Customer Facing
  - Presenting invoices
  - Deposit and withdrawal of funds
  - Displaying multiple currencies
- Merchant Facing
  - Managing funds
    - Merchant may be holding bitcoin and fiat within their wallet/POS system
  - Inventory management ❓
    - Maybe too deep and too off-topic. Are there special considerations here in a bitcoin world?
  - Key management
  - Security & privacy
    - Considerations for granting employees access to specific functions

**Comment by GBKS** [comment]
Going to close this issue, as discussed [here](https://github.com/BitcoinDesign/Guide/issues/864#issuecomment-1881207007). We can re-open if there's renewed momentum around merchant content.
