### ISSUE TITLE
Expand how PINs work in secure wallets

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#973]
Steyn has been investigating exactly how PINs can protect user wallets - see [the Slack thread](https://bitcoindesign.slack.com/archives/C02VCHSQECT/p1672753881385489). This came up due to a brief mention of PINs in the [savings wallet reference design](https://bitcoin.design/guide/savings-wallet/), without further explanation. He'll create and share a write-up that we can then add to the existing page, or create a new page for.

**Comment by steynviljoen67** [comment]
Thanks for creating the issue. You can assign it to me.
