### ISSUE TITLE
Add "fiat" to glossary

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Guide#975]
This came out of a discussion on my rough draft for #866. We use the term "fiat" many places in the Guide, but never define it. Not everyone is accustomed to this term outside of bitcoin. A simple glossary entry would help.

**Comment by LiQuiD-404** [comment]
@sbddesign Hello there! Wanted to know whether this issue is still up for grabs.

**Comment by sbddesign** [comment]
Yes @LiQuiD-404, till up for grabs.
