### ISSUE TITLE
Add guidelines on how to contribute a case study to the BDG

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Guide#978]
**Content request**

Add in a content about how to contribute a case study to the BDG

**[Contribute to guide](https://bitcoin.design/guide/contribute/)**
**[Content guidelines](https://bitcoin.design/guide/contribute/content-guidelines/)**
I've added in two pages here where this content could possibly go. At this stage totally open to where the content would ideally fit in. 

**Why would you like to change the content?**
We are looking to build out the case study section of the BDG and so having a resource which people can use to easily and quickly create a case study would be useful to have. 

Created a document on how to contribute a case study to the bitcoin design guide.
[BDG Case Study Guidelines](https://docs.google.com/document/d/1lkipBAdo-re_TCIXgMhddFpGnZU3u6f1svJ06ctjkrk/edit?usp=sharing)

**To do Mo**
Create a question document and link it to the bottom of this Google doc which was a good suggestion from Stephen so that next to this guideline doc people can quickly answer those questions and create a draft of a case study.

**Comment by mouxdesign** [comment]
@sbddesign Suggested creating a question document which could accompany the guidelines document. Linked below is a document with a list of questions which can then be used to create the case study.

It could be a google document that someone could make a copy of and edit to form a case study around the project they worked on.

[Case Study Questions](https://docs.google.com/document/d/1B6qcry5Wb-jjtMpTyuTk5WqGvF8WKScc4NAIK-SK1go/edit#)

**Comment by mouxdesign** [comment]
@pavlenex Thanks for offering to take a look. Link to [google doc. ](https://docs.google.com/document/d/1lkipBAdo-re_TCIXgMhddFpGnZU3u6f1svJ06ctjkrk/edit#heading=h.9pv80f3tnh68)

**Comment by pavlenex** [comment]
Concept ACK. I like how you're helping people structure their case-study by answering questions. I think @ConorOkus has mentioned that that's what they did with LDK Case-studies, send questionnaire to people to answer and then structure it accordingly.

**Comment by mouxdesign** [comment]
Reviewed this content and made some changes to the content based on suggestions based on the comments on the google doc. Would appreciate another review on it.

**Comment by mouxdesign** [comment]
[Figma file ](https://www.figma.com/file/EvnGOkdLF5NEsA7xkSZn4n/Case-studies-Images?type=design&mode=design&t=0VdCfSkShmtcP2a7-0)linking to images
