### ISSUE TITLE
Footer breaks in Mobile View

### ISSUE THREAD

**Issue by soustab10** [BitcoinDesign/Guide#984]
**Describe the bug**
The bottom part of the footer breaks in mobile view as there is not enough space to accommodate all the menu options.

**To Reproduce**
1. Go to 'https://bitcoin.design/'
2. Scroll down to footer section
3. See error

**Expected behavior**
In mobile view, the footer menu items should be arranged in  a well-presented manner, preferably as a dropdown or a grid of options.

**Screenshots**
![image](https://user-images.githubusercontent.com/95632583/216966244-a884e0fe-b0ac-48c2-9642-ba4edddb1b58.png)

**Smartphone (please complete the following information):**
 - Device: All Devices
 - OS: NA
 - Browser: NA
 - Version: NA

**Additional context**

**Comment by GBKS** [comment]
Thanks for noticing and creating the issue. I just opened #985 to address it. Let me know if that works for you.
