### ISSUE TITLE
Add an `App screens` page to resource section of the guide

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Guide#988]
I'd like to add a page in the [resources](https://bitcoin.design/guide/resources/) of the guide called "App screens" that houses a list of static screen states from various bitcoin apps. 

These are primarily used for UX research and can save a bunch of time as well as give a good historical record of the development of apps (if the files are kept up to date that is). 

I went ahead and made one of these files for [Phoenix iOS](https://www.figma.com/community/file/1208636222589756469) we can start with for this page. Would be great to get as many bitcoin apps as possible here. I published this to Figma community in hopes people remix and keep things up to date if I can not.

**Comment by GBKS** [comment]
This could be a pretty useful resource. I created a screen browser for the UI Kit [here](https://www.bitcoinuikit.com/screens) ([source](https://github.com/GBKS/bitcoinuikit.com)), which shows a grid of screens that can be filtered by user flow and has a search field that looks at title & description, as well as text used inside the images. We could just re-use that design and/or code. The code setup does not mash with how the guide is set up, maybe this could even live under its own domain?

To do this properly, I think this needs more than just a flat grid. The Phoenix Figma file you linked contains around 85 images. Let's say we do this for 5 wallets, then we're at 425 images, an amount that really needs some filtering and search. I also think meta data is important to tag things like operating system, user flows, keywords, etc.

I also have a custom Figma plug-in for exporting UI Kit screens for the screen browser that we can use. It automatically creates a JSON file in Figma and preps screens for export. This would allow us to work primarily in Figma for collecting and annotating screens, and then adding them into the site would just take a few minutes.

Quite a bit of work. To kick things off very simple, maybe it's enough to create a static page with links to various Figma files, with each one having a cover image like in the [design source files page](https://bitcoin.design/guide/resources/design-files/).

Screenshot Figma files we already have:
- [Phoenix](https://www.figma.com/file/uaAarmZzZBg9J1HaHaOcCX/Phoenix-Lightning-Wallet?node-id=0%3A1&t=xTsPXPqynEorFLgd-1)
- [Muun](https://www.figma.com/file/rPyJ0Y8xg0kN4FrHFCeDRg/Muun-wallet?node-id=0%3A1&t=jvLAiytEZcGMNlOg-1)
- [Breez](https://www.figma.com/file/Vgdr0fNIEEMVkd6SIs1GDi/Breez-Lightning-Wallet?node-id=0%3A1&t=wO84aq4h2lTCIMYC-1)
- [Green]()
- [Blixt](https://www.figma.com/file/LqzHtcW5dLKXa54DDwRxTI/Blixt-Wallet?node-id=0%3A1&t=Q8G5c8PHdxjfRgSq-1)
- [Wallet of Satoshi](https://www.figma.com/file/vWxA4SRJq7RdXWiKrB032y/Bitcoin-app-accessibility-tests?node-id=207%3A2433&t=nDvAXPpVZEGsS207-1) (accessibility test)
- [Blockstream Green](https://www.figma.com/file/vWxA4SRJq7RdXWiKrB032y/Bitcoin-app-accessibility-tests?node-id=139%3A2433&t=nDvAXPpVZEGsS207-1) (accessibility test)

There might be some more floating around.

**Comment by GBKS** [comment]
This issue is now almost 2 years old. The idea has come up 2-3 times since then, but no one is interested in acting on it. I suggest we close the issue.
