### ISSUE TITLE
Document UX best practices for multi-key wallets with complex spending conditions

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#992]
During [Advancing Bitcoin](https://www.advancingbitcoin.com), Kevin from Wizardsardine held a talk about the [Liana wallet](https://github.com/wizardsardine/liana), which allows for complex multi-sig setups and spending conditions. 

Kevin mentioned that we really need other wallets to support these types of configurations so people don't lose their money when migrating. Sounds like a bat signal for the design community.

Below are a few screenshots from the [Twitter account](https://twitter.com/Wizardsardine).

![image](https://user-images.githubusercontent.com/695901/223135748-d2011ba0-b4c4-43f4-b256-0b05847983c3.png)

![image](https://user-images.githubusercontent.com/695901/223135982-04755972-f6ea-4eda-97fb-d344060cae7d.png)

![image](https://user-images.githubusercontent.com/695901/223136014-a2d42890-3a96-4528-91cf-c62342ef3e86.png)

![image](https://user-images.githubusercontent.com/695901/223136051-4d9977cb-f0b7-48c1-8845-c90228e0adac.png)

**Comment by GBKS** [comment]
Also see [this Slack thread](https://bitcoindesign.slack.com/archives/C015856BDME/p1678451460153359), there's interest from the BDK team on the topic.

**Comment by monishkajha17** [comment]
@GBKS can I work on this issue?

**Comment by GBKS** [comment]
All are welcome to help. I started gathering information in this [Google Doc](https://docs.google.com/document/d/1yvMqYk2-5YcADizaWoFtCHphkT9npVGL2YX8nx2fBY4/edit?usp=sharing). Feel free to leave comments, suggest additional resources, etc. After this intel gathering, I'd like to explore mocking up some of the basic user flows via [Bitcoin UI Kit](http://bitcoinuikit.com). We can also discuss in Discord.

**Comment by rabbitholiness** [comment]
Closing this isssue.
